### PR TITLE
[P2] Shed tail hp cost rounds up

### LINKED ISSUE #956: [P2] Shed Tail's hp cost is rounded up instead of down
### Describe the bug

Shed tail's hp cost is rounded up instead of down

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes the user will see?

Shed tail's hp cost is rounded up instead of down

## Why am I making these changes?

Move was not accurate to mainline

## What are the changes from a developer perspective?

add-substitute-attr
* Replaced `hpCost` with a boolean for whether the move is shed tail

shed-tail.test
* Updated test

init-moves
* Updated Substitute and Shed tail's AddSubstituteAttr params

## Screenshots/Videos

image

## How to test the changes?

```ts
const overrides = {
  MOVESET_OVERRIDE: [MoveId.SHED_TAIL]
}
```

## Checklist

- [ ] ⚠️ If this is a PR for `main` (such as a hotfix), has the game version been updated (`npm run update-version:patch` / `npm run update version:minor`?
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

#### Are there any localization additions or changes? If so:

- [ ] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [ ] If so, please leave a link to it here:
- [ ] Have I added the `Localization` tag to this PR?

#### If there are no locale changes:
- [ ] Have I made sure **not** to commit any changes to the locale repo on this branch?

### CODE REVIEW

**Review by DayKev — DISMISSED** [review]

**Review by PigeonBar — DISMISSED** [review]

File: src/data/moves/move-attrs/add-substitute-attr.ts [hunk 1]
```diff
@@ -15,17 +15,22 @@ import i18next from "i18next";
  * @see {@linkcode apply}
  */
 export class AddSubstituteAttr extends MoveEffectAttr {
-  /** The ratio of the user's max HP that is required to apply this effect */
-  private hpCost: number;
+  /**
+   * This attr is only used for Substitute and Shed Tail.
+   * Substitute costs 1/4 of the user's max hp and rounds down
+   * Shed tail costs 1/2 of the user's max hp and rounds up
+   */
```
Comment (flx-sta) [inline src/data/moves/move-attrs/add-substitute-attr.ts]: This documentation should probably be put into the class docs then.

The class should probably be renamed too then.

File: src/data/moves/move-attrs/add-substitute-attr.ts
Comment (flx-sta) [inline src/data/moves/move-attrs/add-substitute-attr.ts:1]: I personally preferred the more general approach to the design of the attribute before. I would have just added a flag to define something like `roundUp = true` or so, but either way works

File: src/data/moves/move-attrs/add-substitute-attr.ts [hunk 2]
```diff
@@ -42,9 +47,15 @@ export class AddSubstituteAttr extends MoveEffectAttr {
...
+    /**
+     * Only works if
+     * - The user does not have a substitute out already
+     * - The user has enough HP
+     * - THe user has more than 1 max hp (wonder guard users)
+     */
     return (user, _target, _move) =>
       !user.getTag(BattlerTagType.SUBSTITUTE)
-      && user.hp > Math.floor(user.getMaxHp() * this.hpCost)
+      && user.hp > (this.forShedTail ? Math.ceil(user.getMaxHp() * 0.5) : Math.floor(user.getMaxHp() * 0.25))
```
Comment (flx-sta) [inline src/data/moves/move-attrs/add-substitute-attr.ts]: Apply DRY (Do not repeat yourself) principal here. 
The code
```ts
this.forShedTail ? Math.ceil(user.getMaxHp() * 0.5) : Math.floor(user.getMaxHp() * 0.25)
```

is used twice. Should probably create a private helper method returning the hpCost

File: test/moves/shed-tail.test.ts [hunk 3]
```diff
@@ -47,11 +47,7 @@ describe("Moves - Shed Tail", () => {
...
     expect(feebas).not.toBe(magikarp);
     expect(feebas.hp).toBe(feebas.getMaxHp());
-    // Note: Shed Tail's HP cost is currently not accurate to mainline, as it
-    // should cost ceil(maxHP / 2) instead of max(floor(maxHp / 2), 1). The current
-    // implementation is consistent with Substitute's HP cost logic, but that's not
-    // the case in mainline for some reason :regiDespair:.
-    expect(magikarp.hp).toBe(Math.ceil(magikarp.getMaxHp() / 2));
+    expect(magikarp.hp).toBe(magikarp.getMaxHp() - Math.ceil(magikarp.getMaxHp() / 2));
     expect(substituteTag).toBeDefined();
     expect(substituteTag?.hp).toBe(Math.floor(magikarp.getMaxHp() / 4));
```
Comment (flx-sta) [inline test/moves/shed-tail.test.ts:52]: Should this still be Math.floor though?

**Review by flx-sta — CHANGES_REQUESTED** [review]
see comments above

File: test/moves/shed-tail.test.ts (hunk 3 above)
Comment (DayKev) [reply test/moves/shed-tail.test.ts:52]: The substitute doll works the same for both moves.

File: src/data/moves/move-attrs/add-substitute-attr.ts
Comment (Tempo-anon) [reply src/data/moves/move-attrs/add-substitute-attr.ts:1]: I figured there wasn't a need to have two input variables since there's only two cases for this move: either it's 1/4 rounded down or 1/2 rounded up

File: src/data/moves/move-attrs/add-substitute-attr.ts (hunk 1 above)
Comment (Tempo-anon) [reply src/data/moves/move-attrs/add-substitute-attr.ts]: No idea on a good name 🤷

**Review by PigeonBar — APPROVED** [review]

File: src/data/moves/move-attrs/add-substitute-attr.ts (hunk 1 above)
Comment (flx-sta) [reply src/data/moves/move-attrs/add-substitute-attr.ts]: Meh.. I guess the shed tail also spawns a substitute

**Review by flx-sta — APPROVED** [review]
