### PR TITLE
[Ability][Checkup][Bug] Fur Coat Test + Documentation + Fixing incorrect damage calculations re: DefAtkAttr moves

### LINKED ISSUE #117: [Ability][Checkup] Fur Coat
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Fur Coat doubles the Defense stat of the Pokémon with this Ability. 
- [x] It has no effect on self-inflicted confusion damage. 
- [x] Does not boost damage of Body Press
- [x] Defense considered with special attacks that target Defense (Psystrike, Sacred Sword, etc.)  

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/172

## Flyout Behaviour

<details><summary>
Activate whenever a Pokemon would be attacked by a Physical Move
</summary>

https://github.com/user-attachments/assets/3a7f54b0-a242-49de-b644-72b34f0ec373

</details>

## Related Bugs

[[Bug] DefDefattr (Psyshock, Psystrike, Secret Sword) do not Consider Fur Coat in Damage Calculation #5066](https://github.com/pagefaultgames/pokerogue/issues/5066)

## References
- [Bulbapedia - Fur Coat](https://bulbapedia.bulbagarden.net/wiki/Fur_Coat_(Ability))
- [Smogon - Fur Coat](https://www.smogon.com/dex/sm/abilities/fur-coat/)

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?

Fur Coat should have the proper interactions with DefAtkAttr moves like Psyshock, Sacred Sword, etc. 

## Why am I making these changes?

Ability Checkups :)

## What are the changes from a developer perspective?

- the call of getEffectiveStat() in getBaseDamage() now considers if a move has the attr DefDefAttr when it determines which stat to calculate
- In getAttackDamage(), which calls getBaseDamage() and passes down an argument containing the move category, when that argument is created, it uses the function getMoveCategory() instead. 

## How to test the changes?
`npm run test fur_coat`

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -3100,13 +3101,16 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
     );
     applyMoveAttrs(VariableAtkAttr, source, this, move, sourceAtk);
 
+    /** The target's defense stat should be used if the move is physical or uses DEF to calculate its damage */
+    const useDefenseStat = isPhysical || move.hasAttr(DefDefAttr);
```
Comment (innerthunder) [inline src/field/pokemon.ts]: `DefDefAttr` is already applied in L3122

```ts
applyMoveAttrs(VariableDefAttr, source, this, move, targetDef);
```

**Review by innerthunder — DISMISSED** [review]
Please check this ability's interaction with [Body Press](https://bulbapedia.bulbagarden.net/wiki/Body_Press_(move)) and make a unit test for the interaction (or an `it.todo` if the interaction is incorrect).

> ... For example, the user's [Huge Power](https://bulbapedia.bulbagarden.net/wiki/Huge_Power_(Ability)) or a held [Choice Band](https://bulbapedia.bulbagarden.net/wiki/Choice_Band) will increase the stat used in calculation, whereas [Fur Coat](https://bulbapedia.bulbagarden.net/wiki/Fur_Coat_(Ability)) or a held [Eviolite](https://bulbapedia.bulbagarden.net/wiki/Eviolite) will not.

File: src/data/ab-attrs/stat-multiplier-ab-attr.ts [hunk 2]
```diff
@@ -58,7 +59,8 @@ export class StatMultiplierAbAttr extends AbAttr {
     args: any[],
   ): boolean {
     const move = args[0] as Move;
-    if (stat === this.stat && (!this.condition || this.condition(pokemon, null, move))) {
+    const target = args[1] as Pokemon;
+    if (stat === this.stat && (!this.condition || this.condition(pokemon, target, move))) {
```
Comment (innerthunder) [inline src/data/ab-attrs/stat-multiplier-ab-attr.ts]:
```suggestion
    const opponent = args[1] as Pokemon;
    if (stat === this.stat && (!this.condition || this.condition(pokemon, opponent, move))) {
```

to match where this is applied in `Pokemon#getEffectiveStat`

File: src/field/pokemon.ts (hunk 1 above)
Comment (frutescens) [reply src/field/pokemon.ts]: But then why does it not interact with Fur Coat properly?

Comment (innerthunder) [reply src/field/pokemon.ts]: `DefDefAttr`'s `getEffectiveStat` call is simulated. Fur Coat might still apply but not show itself applying.

**Review by MokaStitcher — DISMISSED** [review]
lgtm

**Comment by Tempo-anon** [comment]
Another edge case to consider: how does fur coat interact with moves that variably target def or spD like shell side arm?

File: src/data/ab-attrs/stat-multiplier-ab-attr.ts [hunk 3]
```diff
@@ -54,9 +55,9 @@ export class StatMultiplierAbAttr extends StatStageAbAttr {
     stat: BattleStat,
     statValue: NumberHolder,
     move: Move,
-    _target?: Pokemon,
+    target?: Pokemon,
   ): boolean {
-    if (stat === this.stat && (!this.condition || this.condition(pokemon, null, move))) {
+    if (stat === this.stat && (!this.condition || this.condition(pokemon, target!, move))) {
```
Comment (flx-sta) [inline src/data/ab-attrs/stat-multiplier-ab-attr.ts]: I'm not a fan of the `!`.
Isn't a fallback to `null` an option? 
```suggestion
    if (stat === this.stat && (!this.condition || this.condition(pokemon, target ?? null, move))) {
```

File: src/data/all-abilities.ts [hunk 4]
```diff
@@ -906,7 +906,7 @@ export function initAbilities() {
     new Ability(Abilities.PROTEAN, 6).attr(PokemonTypeChangeAbAttr),
     //.condition((p) => !p.summonData?.abilitiesApplied.includes(Abilities.PROTEAN)), //Gen 9 Implementation
     new Ability(Abilities.FUR_COAT, 6)
-      .attr(ReceivedMoveDamageMultiplierAbAttr, (_target, _user, move) => move.category === MoveCategory.PHYSICAL, 0.5)
+      .attr(StatMultiplierAbAttr, Stat.DEF, 2, (_user, target, _move) => !!target)
```
Comment (flx-sta) [inline src/data/all-abilities.ts]: NIT: No need for `_move` when it's **after** the required param
```suggestion
      .attr(StatMultiplierAbAttr, Stat.DEF, 2, (_user, target) => !!target)
```

**Review by flx-sta — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]
Code is fine but I'm still curious about the interaction with shell side arm

**Comment by frutescens** [comment]
> Code is fine but I'm still curious about the interaction with shell side arm

I believe it should be OK because ignoreOpponentAbility is set to 'true' in getBaseDamage() when ShellSideArmCategoryAttr is applied.

**Comment by frutescens** [comment]
Fur Coat should be ignored by Shell Side Arm
image
