### PR TITLE
[Audio] Implement critical catch sfx from Gen 5

### LINKED ISSUE #799: [Bug] Critical Capture Sound is "Demonic"
### Describe the bug

when a Critical Capture occurs, a sound is played. It's not a very pleasant sound.

### Reproduction

Get a Critical Capture; force Zigzagoon and start chucking balls.

### Expected behavior

Sword and Shield's

https://www.youtube.com/watch?v=rkEZvIvpEgQ

Black and White's

https://www.youtube.com/watch?v=rwusP4ButHs

### Screenshots / Videos

https://github.com/user-attachments/assets/6804eb09-1474-4569-9ec7-a33e1f0f6437

From the Critical Capture PR

image

### Session export file

[sessionData_Guest.pkty.txt](https://github.com/user-attachments/files/19135148/sessionData_Guest.pkty.txt)

### User data export file

_No response_

### Additional context

[**[Feature] [Balance] Add critical captures, update shake probability to match gen 6 #4791**](https://github.com/pagefaultgames/pokerogue/pull/4791)

### PR DESCRIPTION
**Pull request by SangaraSorama**
## What are the changes the user will see?

New sound effect for throw preceding critical capture, using the one from the mainline games

## Why am I making these changes?

Sounds better

From : https://github.com/pagefaultgames/pokerogue/pull/5131

Fixes #799

## What are the changes from a developer perspective?

Adds and implements `crit_throw.wav`

## Screenshots/Videos

<details><summary>Before:</summary>
<p>

https://github.com/user-attachments/assets/a8fcc9aa-2d69-4396-8fe4-eaa4401a42fe

</p>
</details> 

<details><summary>After:</summary>
<p>

https://github.com/user-attachments/assets/e2f04f9d-ff79-487f-bc0e-2d5a3838156e

</p>
</details> 

## How to test the changes?

- Change line 59 in `attempt-capture-phase.ts` to `const isCritical` = true; to guarantee critical capture
- Throw ball

## Checklist

- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

#### If there are no locale changes:
- [x] Have I made sure **not** to commit any changes to the locale repo on this branch?

### CODE REVIEW

**Comment by SangaraSorama** [comment]
All checks passed when put as Open, but put back as Draft until someone tests the changes manually

**Comment by SangaraSorama** [comment]
Tested the changes manually, added videos of before and after

File: src/phases/attempt-capture-phase.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class AttemptCapturePhase extends PokemonPhase {
     this.pokeball.setOrigin(0.5, 0.625);
     field.add(this.pokeball);
 
-    globalScene.audioManager.playSound("se/pb_throw", isCritical ? { rate: 0.2 } : undefined); // Crit catch throws are higher pitched
+    globalScene.audioManager.playSound(isCritical ? "se/crit_throw" : "se/pb_throw");
```
Comment (flx-sta) [inline src/phases/attempt-capture-phase.ts]: NIT: not sure if that makes it better or worse. I'll let you and allt he other reviewers judge
```suggestion
    globalScene.audioManager.playSound(`se/${isCritical ? "crit" : "pb"}_throw`);
```

Comment (Tempo-anon) [reply src/phases/attempt-capture-phase.ts]: My personal opinion is that there's no need to inline it.
```ts
if (isCritical) {
  globalScene.audioManager.playSound("se/crit_throw");
} else {
  globalScene.audioManager.playSound("se/pb_throw");
}
```
sneaky edit because the first instance had the two swapped

**Review by flx-sta — DISMISSED** [review]
Tested in-game ✅

File: src/phases/attempt-capture-phase.ts (hunk 1 above)
Comment (flx-sta) [reply src/phases/attempt-capture-phase.ts]: 3 Times the charm:
```suggestion
    let throwSound: string;
    
    if (isCritical) {
      throwSound = "se/crit_throw";
    } else {
      throwSound = "se/pb_throw";
    }
   
    globalScene.audioManager.playSound(throwSound);
```

------

### @Tempo-anon suggestion as ... suggestion

```suggestion
    if (isCritical) {
      globalScene.audioManager.playSound("se/pb_throw");
    } else {
      globalScene.audioManager.playSound("se/crit_throw");
    }
```

**Comment by SangaraSorama** [comment]
I fixed the videos. The "before" was incorrect I believe, and both are now without bgm

**Comment by SangaraSorama** [comment]
Added the change in syntax from Temp, making it a proper `if`

**Review by flx-sta — DISMISSED** [review]

**Review by torranx — DISMISSED** [review]

File: src/phases/attempt-capture-phase.ts [hunk 2]
```diff
@@ -81,7 +81,11 @@ export class AttemptCapturePhase extends PokemonPhase {
     this.pokeball.setOrigin(0.5, 0.625);
     field.add(this.pokeball);
 
-    globalScene.audioManager.playSound("se/pb_throw", isCritical ? { rate: 0.2 } : undefined); // Crit catch throws are higher pitched
+    if (isCritical) {
+      globalScene.audioManager.playSound("se/pb_throw");
+    } else {
+      globalScene.audioManager.playSound("se/crit_throw");
+    }
```
Comment (Tempo-anon) [inline src/phases/attempt-capture-phase.ts]: Sorry about this, but I accidentally got these mixed up in my first post. If `isCritical` is true it would be playing the normal `pb_throw` sound effect. 
```suggestion
    if (isCritical) {
      globalScene.audioManager.playSound("se/crit_throw");
    } else {
      globalScene.audioManager.playSound("se/pb_throw");
    }
```

**Review by torranx — APPROVED** [review]
:shoots temp's foot:
<sub>didnt notice that too</sub>

**Review by Tempo-anon — APPROVED** [review]
