### PR TITLE
[Refactor][Bug] Add `canSetWeather` utility + Fix Chilly Reception

### LINKED ISSUE #710: [Bug] Chilly Reception Replaces Legendary Weather (Primordial Sea, Desolate Land, Delta Stream)
### Describe the bug

On Usage, Chilly Reception replaces the weather (Harsh Sun, Heavy Rain, Heavy Winds) set by the Primal Weather Abilities.

### Reproduction

Use Chilly Reception while a Legendary weather is active.

### Expected behavior

Sandstorm and other weather-setting fails while Legendary Weather is active.

https://github.com/user-attachments/assets/da130bd1-6ab5-4bb3-be3c-67422135379d

> heavy rain causes the weather-modifying moves Sunny Day, Rain Dance, Sandstorm, and Hail to fail if used, and causes the Abilities Drought, Drizzle, Sand Stream, and Snow Warning to fail to activate.
-Bulba

Chilly Reception should still switch the Pokemon despite the weather not being able to be changed, unlike Parting Shot.

https://replay.pokemonshowdown.com/gen9customgame-2303972860

### Screenshots / Videos

Chilly and Delta Stream

https://github.com/user-attachments/assets/1f9b72da-4e64-424f-a94e-335593875389

Chilly and Desolate Land

https://github.com/user-attachments/assets/f7764b84-8837-4e24-adce-481512e7f659

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?

Fixes #710 

## Why am I making these changes?

The game would benefit from a `canSetWeather` function

## What are the changes from a developer perspective?

Created a `canSetWeather` function that will check if a new weather can. be set on the field before overwriting the current weather in `trySetWeather`
Changed `isImmutable()` to `isPrimal()` because primal weather can be overwritten by other primal weather, so it is not 'immutable' and `isPrimal()` clarifies the weather hierarchy better. 
Created a 'PRIMAL_WEATHER' constant that is used for reference in `canSetWeather()` and `isPrimal()` 
Cleaned up `isDamaging()` to match `isPrimal()` 

## How to test the changes?

Chilly Reception should no longer overwrite the 'immutable' weathers like Strong Winds/Harsh Sun/Heavy Rain

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)

### CODE REVIEW

File: src/data/move-attrs/weather-change-attr.ts [hunk 1]
```diff
@@ -23,8 +23,6 @@ export class WeatherChangeAttr extends MoveEffectAttr {
   }
 
   override getCondition(): MoveConditionFunc {
-    return (_user, _target, _move) =>
-      !globalScene.arena.weather
-      || (globalScene.arena.weather.weatherType !== this.weatherType && !globalScene.arena.weather.isImmutable());
+    return (_user, _target, _move) => globalScene.arena.canSetWeather(this.weatherType);
```
Comment (Tempo-anon) [inline src/data/move-attrs/weather-change-attr.ts:26]: This would make the entire move fail if the weather can't be changed right? The Pokemon using chilly reception should still attempt to switch out even if the weather changing fails. i.e. If the current weather is snow using chilly reception still switches the user out

File: src/field/arena.ts [hunk 2]
```diff
@@ -406,7 +434,7 @@ export class Arena {
       return this.trySetWeatherOverride(Overrides.WEATHER_OVERRIDE);
     }
 
-    if (this.weather?.weatherType === (weather || undefined)) {
+    if (!this.canSetWeather(weather)) {
```
Comment (Tempo-anon) [inline src/field/arena.ts]: nit: something about `if (!...)` just bothers me but I don't know how other people feel about it or if `if (this.canSetWeather(weather) === false)` is too much

**Review by Tempo-anon — DISMISSED** [review]
Looks like some tests are failing.

File: src/data/move-attrs/weather-change-attr.ts (hunk 1 above)
Comment (frutescens) [reply src/data/move-attrs/weather-change-attr.ts:26]: This isn't Chilly Reception's attr. It's Sunny Day/Rain Dance/etc's move attribute.
Chilly Reception's is `ChillyReceptionAttr`

Comment (Tempo-anon) [reply src/data/move-attrs/weather-change-attr.ts:26]: Oh whoops, my bad

File: src/field/arena.ts (hunk 2 above)
Comment (frutescens) [reply src/field/arena.ts]: Think that should be a larger question since it is used commonly across the codebase + would require a change across the codebase

File: src/field/arena.ts [hunk 3]
```diff
@@ -395,6 +395,38 @@ export class Arena {
...
   }
 
+  /**
+   * Helper function that checks if it is possible to set a new weather given current weather conditions
+   * @param newWeather the weather that the game is attempting to set
+   * @returns `true` if the weather can be set given current conditions | `false` if not
+   */
+  canSetWeather(newWeather: WeatherType): boolean {
+    if (this.weather) {
+      // Checks if the new weather is identical to the current weather
```
Comment (torranx) [inline src/field/arena.ts]: I don't think the comments on top of the `if` blocks add any value since the conditions are already straightforward

File: src/field/arena.ts [hunk 4]
```diff
@@ -395,6 +395,38 @@ export class Arena {
...
+          newWeather === WeatherType.HARSH_SUN
+          || newWeather === WeatherType.HEAVY_RAIN
+          || newWeather === WeatherType.STRONG_WINDS
+          || newWeather === WeatherType.NONE
+        ) {
+          return true;
+        } else {
+          return false;
+        }
+      }
```
Comment (torranx) [inline src/field/arena.ts]: the 2 `if` statements can be merged, and using array.includes might be cleaner here

File: src/field/arena.ts [hunk 5]
```diff
@@ -395,6 +395,38 @@ export class Arena {
...
+      // Checks if there is no current weather and the game is attempting to set the weather to none
+    } else if (isNullOrUndefined(this.weather) && newWeather === WeatherType.NONE) {
```
Comment (torranx) [inline src/field/arena.ts]: nit: you can remove the `if-else if` conditions by returning `false` early given the conditions here. much more readable that way imo

File: src/field/arena.ts (hunk 2 above)
Comment (torranx) [reply src/field/arena.ts]: I'd still go with `if (!...)` considering the function returns boolean

Comment (DayKev) [reply src/field/arena.ts]: > I'd still go with `if (!...)` considering the function returns boolean

Agreed. +1 from Moka as well.
image

File: src/field/arena.ts [hunk 6]
```diff
@@ -395,6 +395,38 @@ export class Arena {
...
+      return false;
+    }
+    return true;
+  }
```
Comment (DayKev) [inline src/field/arena.ts]:
```suggestion
   * @param weather - The weather that the game is attempting to set
   * @returns `true` if the weather can be set given current conditions | `false` if not
   */
  public canSetWeather(weather: WeatherType): boolean {
    if (this.weather) {
      if (weather === this.weather.weatherType) {
        return false;
      }
      if (this.weather.isImmutable()) {
        if ([WeatherType.NONE, ...primalWeathers].includes(weather)) {
          return true;
        }
        return false;
      }
    } else if (weather === WeatherType.NONE) {
      return false;
    }
    return true;
  }
```

Comment (DayKev) [reply src/field/arena.ts]: As part of this suggestion you should also add this to `constants.ts` (and import it into `arena.ts`):
```ts
export const primalWeathers = Object.freeze([WeatherType.HARSH_SUN, WeatherType.HEAVY_RAIN, WeatherType.STRONG_WINDS]);
```

Comment (DayKev) [reply src/field/arena.ts]: This also lets you change `Weather.isImmutable()` to `return primalWeathers.includes(this.weatherType);`

File: src/field/arena.ts [hunk 7]
```diff
@@ -395,6 +395,25 @@ export class Arena {
     return true;
   }
 
+  /**
+   * Helper function that checks if it is possible to set a new weather given current weather conditions
+   * @param weather - The weather that the game is attempting to set
+   * @returns `true` if the weather can be set given current conditions | `false` if not
+   */
+  public canSetWeather(weather: WeatherType): boolean {
```
Comment (torranx) [inline src/field/arena.ts]: did you mean to remove the `isNullOrUndefined` check?

Comment (frutescens) [reply src/field/arena.ts]: See Kev's comment here https://github.com/Despair-Games/poketernity/pull/714#discussion_r1962840474

Comment (DayKev) [reply src/field/arena.ts]: That check is implied by the first if failing.

File: src/data/weather.ts [hunk 8]
```diff
@@ -22,15 +27,15 @@ export class Weather {
 
   constructor(weatherType: WeatherType, turnsLeft?: number) {
```
Comment (DayKev) [inline src/data/weather.ts]:
```suggestion
  constructor(weatherType: WeatherType, turnsLeft: number = 0) {
```
Huh. Well, since your changes revealed this might as well fix it lol.

File: src/data/weather.ts [hunk 9]
```diff
@@ -22,15 +27,15 @@ export class Weather {
...
     this.weatherType = weatherType;
-    this.turnsLeft = !this.isImmutable() ? turnsLeft || 0 : 0;
+    this.turnsLeft = !this.isPrimal() ? turnsLeft || 0 : 0;
```
Comment (DayKev) [inline src/data/weather.ts]:
```suggestion
    this.turnsLeft = !this.isPrimal() ? turnsLeft : 0;
```

File: src/field/arena.ts (hunk 7 above)
Comment (torranx) [reply src/field/arena.ts]:
```
else if (isNullOrUndefined(this.weather) && newWeather === WeatherType.NONE) {
      return false;
    }
```
before it returns `false`, now if `this.weather` is falsy, it defaults to return `true`

File: src/field/arena.ts [hunk 10]
```diff
@@ -395,6 +395,25 @@ export class Arena {
...
+    if (this.weather) {
+      if (weather === this.weather.weatherType) {
+        return false;
+      }
+      if (this.weather.isPrimal() && [WeatherType.NONE, ...PRIMAL_WEATHER].includes(weather)) {
+        return true;
+      }
```
Comment (DayKev) [inline src/field/arena.ts]: You can't do it this way because that lets any weather override primal weather.

File: src/field/arena.ts (hunk 7 above)
Comment (frutescens) [reply src/field/arena.ts]: I don't think so because then if `this.weather` is falsy, it then checks if the `newWeather` is `WeatherType.NONE` first before defaulting to `true`

Comment (torranx) [reply src/field/arena.ts]: yes but it doesnt check if the `weather` is undefined or null, and will return `true` by default
or am I missing something here

Comment (frutescens) [reply src/field/arena.ts]: if `this.weather` is undefined or null, it's checked in `if (this.weather)` + it should return `true` by default

Comment (DayKev) [reply src/field/arena.ts]:
```ts
  public canSetWeather(newWeather: WeatherType): boolean {
    if (this.weather) {
      // ...
    }
    // this.weather must be falsy now, because the above if
    // did not evaluate this.weather as truthy, and we've reached
    // the else-if block
    else if (newWeather === WeatherType.NONE) {
      return false;
    }
    return true;
  }
```

Comment (DayKev) [reply src/field/arena.ts]: The `else if` should never run if `this.weather` is truthy, either, afaik.

**Comment by DayKev** [comment]
Looks good, gonna add a test for the primal weathers and then approve. 👍

**Review by DayKev — APPROVED** [review]

**Review by torranx — APPROVED** [review]
