### PR TITLE
[Ability][Checkup][Bug] Fixing up Fluffy's interactions with Long Reach + adding tests/utilities for Fluffy

### LINKED ISSUE #128: [Ability][Checkup] Fluffy
## Ability Requirements
- [ ] Documentation
- [ ] Tests
- [x] A Pokémon with Fluffy takes half damage from moves that make contact. 
- [x] It also takes double damage from Fire-type moves. 
- [x] Fire-type moves that make contact will deal regular damage. 
- [ ] Moves affected by Long Reach which make contact will deal regular damage. 

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/139

## Flyout Behaviour

<details><summary>
Fluffy's Flyout appears whenever a Fire move is used on a Pokemon, or when a move that makes contact would hit successfully.
</summary>
Contact

https://github.com/user-attachments/assets/42db30a8-4023-4b00-9144-28ec2bf745b1

Fire

https://github.com/user-attachments/assets/a6bc4c33-e3b5-443e-b399-2e09bb41f17d

</details>

## References
- [Bulbapedia - Fluffy](https://bulbapedia.bulbagarden.net/wiki/Fluffy_(Ability))

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?

Fluffy should interact correctly with Long Reach now. 

## Why am I making these changes?

Ability Checkup + needed some better testing utilities for tracking base damage, post-multiplier/calculated damage, and final damage. 

## What are the changes from a developer perspective?

DamageCalculationResult now has the optional fields of baseDamage and postMultiplierDamage.
Fluffy now uses checkFlag() instead of hasFlag()

## How to test the changes?

`npm run test fluffy`
image

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

### CODE REVIEW

**Review by MokaStitcher — CHANGES_REQUESTED** [review]
There are a number of tests that reference the now gone `DamageCalculationResult.damage`, and MoveEffectPhase itself has an error too

image

File: src/data/abilities.ts [hunk 1]
```diff
@@ -1199,7 +1199,11 @@ export function initAbilities() {
     new Ability(Abilities.DANCER, 7).attr(PostDancingMoveAbAttr),
     new Ability(Abilities.BATTERY, 7).attr(AllyMoveCategoryPowerBoostAbAttr, [MoveCategory.SPECIAL], 1.3),
     new Ability(Abilities.FLUFFY, 7)
-      .attr(ReceivedMoveDamageMultiplierAbAttr, (_target, _user, move) => move.hasFlag(MoveFlags.MAKES_CONTACT), 0.5)
+      .attr(
+        ReceivedMoveDamageMultiplierAbAttr,
+        (target, user, move) => move.checkFlag(MoveFlags.MAKES_CONTACT, user, target),
+        0.5,
+      )
       .attr(ReceivedMoveDamageMultiplierAbAttr, (_target, user, move) => user.getMoveType(move) === Type.FIRE, 2)
```
Comment (PigeonBar) [inline src/data/abilities.ts]:
```suggestion
      .attr(ReceivedTypeDamageMultiplierAbAttr, Type.FIRE, 2)
```
Just a minor simplification

**Review by PigeonBar — APPROVED** [review]

**Review by MokaStitcher — APPROVED** [review]
