### PR TITLE
[Bug] Fix evolutions not being cancellable

### LINKED ISSUE #399: [Bug] Evolution cancelling does not work anymore
### Describe the bug

During a Pokemon's evolution it is normally possible to press X/Cancel to stop the evolution and then be offered the option to pause the evolution entirely.
This functionality was broken in #186 

### Reproduction

```
  STARTING_LEVEL_OVERRIDE: 50,
  ITEM_REWARD_OVERRIDE: [{name: "RARE_CANDY"}],
```
evolve any Pokemon and try to press the cancel button during the evolution

### Expected behavior

Pressing X/Cancel stops the evolution and offers the choice to pause it

### Screenshots / Videos

_No response_

### Session export file

_No response_

### User data export file

_No response_

### Additional context

The evolution phase looks at the result of doCycle() to know if the evolution has been cancelled and act accordingly

https://github.com/Despair-Games/poketernity/blob/9b9a8cd651b6e55a50ab9cd011103c188869d701/src/phases/evolution-phase.ts#L120-L126

Before PR #186 doCycle returned false if the FormChangeSceneHandler detected that input
https://github.com/Despair-Games/poketernity/blob/78ef604a90a25b542c78d7f33e663171989d6c66/src/phases/abstract-form-change-base-phase.ts#L253-L255

But when moving doCycle to its own file this check was lost so doCycle never returns false and evolutions don't get cancelled anymore

### PR DESCRIPTION
**Pull request by PigeonBar**
## What are the changes the user will see?

The player can cancel evolutions via input.

## Why am I making these changes?

Fixes #399.

## What are the changes from a developer perspective?

1. Moved `FormChangeSceneHandler.cancelled` to EvolutionPhase, so that it can keep track of whether each individual evolution has been cancelled. This variable is a BooleanHolder so that it can be passed into `doCycle()` to communicate when the animation should be cancelled.
2. Added some tests.
3. Removed some code from `reload.test.ts` for using the Map, since it turns out to no longer be needed.

## Screenshots/Videos

<details><summary>Evolutions can be cancelled</summary>
<p>

https://github.com/user-attachments/assets/d4e54869-6ebb-4cfc-8bd3-3946884fafa5

</p>
</details> 

<details><summary>Trying to cancel a form change does nothing</summary>
<p>

https://github.com/user-attachments/assets/1497257c-4232-488e-bc5a-a10bf42326a7

</p>
</details> 

<details><summary>Trying to cancel the Weird Dream animation does nothing</summary>
<p>

https://github.com/user-attachments/assets/11204719-b561-4dd9-a5e3-a39f75a4f2b2

</p>
</details> 

## How to test the changes?

Try to cancel evolutions and other things that use similar animations.

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

**Review by xsn34kzx — DISMISSED** [review]

**Review by MokaStitcher — DISMISSED** [review]
Had a go at adding tests for paused evolutions too, feel free to add them if you think they're useful
For some reason I didn't manage to get through a second wave after cancelling the evo in the first one, it kept getting stuck in the CommandPhase in the second wave and I didn't feel like debugging that so I split it into 2 separate tests

<details><summary>Details</summary>

```ts

  it("should allow to pause evolutions after cancelling them", async () => {
    await game.classicMode.startBattle([Species.BULBASAUR]);

    const pokemon = game.field.getPlayerPokemon();
    expect(pokemon.species.getName()).toBe("Bulbasaur");
    expect(pokemon.calculateBaseStats()).toStrictEqual([45, 49, 49, 65, 65, 45]);
    expect(pokemon.pauseEvolutions).toBeFalsy();

    // Act as if the evolution was cancelled by the player and prevent overriding the value
    game.scene.animations.setEvolutionCancelled(true);
    vi.spyOn(game.scene.animations, "setEvolutionCancelled").mockImplementation(async (..._args) => {});
    vi.spyOn(pokemon, "getLevelMoves").mockReturnValue([]); // Do not attempt to learn level-up moves

    game.move.use(Moves.SPLASH);
    await game.doKillOpponents();

    // Say yes to pausing the evolution
    game.onNextPrompt("EvolutionPhase", UiMode.CONFIRM, () => game.scene.ui.processInput(Button.ACTION));

    await game.toNextWave();

    const lastLevel = pokemon.level;
    expect(pokemon.pauseEvolutions).toBeTruthy();
    expect(lastLevel).toBeGreaterThan(32);
    expect(pokemon.species.getName()).toBe("Bulbasaur");
    expect(pokemon.calculateBaseStats()).toStrictEqual([45, 49, 49, 65, 65, 45]);
  });

  it("should not happen for Pokemon with paused evolutions", async () => {
    await game.classicMode.startBattle([Species.BULBASAUR]);

    const pokemon = game.field.getPlayerPokemon();
    expect(pokemon.species.getName()).toBe("Bulbasaur");
    expect(pokemon.calculateBaseStats()).toStrictEqual([45, 49, 49, 65, 65, 45]);

    pokemon.pauseEvolutions = true;
    vi.spyOn(pokemon, "getLevelMoves").mockReturnValue([]); // Do not attempt to learn level-up moves

    game.move.use(Moves.SPLASH);
    await game.doKillOpponents();
    await game.toNextWave();

    expect(game.phaseInterceptor.log).not.toContain("EvolutionPhase");
    expect(pokemon.level).toBeGreaterThan(32);
    expect(pokemon.species.getName()).toBe("Bulbasaur");
    expect(pokemon.calculateBaseStats()).toStrictEqual([45, 49, 49, 65, 65, 45]);
  });
``` 

Also requires doing `this.pauseEvolutions = !!dataSource.pauseEvolutions;` in pokemon.ts instead of 
https://github.com/Despair-Games/poketernity/blob/893754e2a31f4b82c44d526d81d23797ae932283/src/field/pokemon.ts#L365
and adding `this.pauseEvolutions = false;` after https://github.com/Despair-Games/poketernity/blob/893754e2a31f4b82c44d526d81d23797ae932283/src/field/pokemon.ts#L416


</details> 

<sub> also, conflicts :(

File: src/animations.ts [hunk 1]
```diff
@@ -592,4 +597,11 @@ export class Animation {
 
     updateParticle();
   }
+
+  /**
+   * @param cancelled If `true`, stop evolution-related anims because the player cancelled evolution.
+   */
+  public setEvolutionCancelled(cancelled: boolean) {
+    this.evolutionCancelled = cancelled;
+  }
```
Comment (flx-sta) [inline src/animations.ts]: NIT: Use a a `get/set` instead:

```suggestion
export class Animation {
  private scene: BattleScene;
  private _evolutionCancelled: boolean = false;

  //...

  public set evolutionCancelled(cancelled: boolean) {
    this._evolutionCancelled = cancelled;
  }
  
  public get evolutionCancelled() { 
    return this._evolutionCancelled;
  }
  //...
}
```

**Review by flx-sta — COMMENTED** [review]
I'm a little unsure about the scope. It feels a bit odd that a `evolutionCanceled` property lives inside the `Animation` class. It's a highly specified variable in a fairly generic class

**Review by flx-sta — DISMISSED** [review]
