### PR TITLE
[Design] Change Tera to work similarly to mainline

### LINKED ISSUE #570: [Bug] Tera Blast and Tera Starstorm are Unaffected by Aerilate
Copied over from PKR 4978

### Describe the bug

When used by a Pokémon with the ability Aerilate, Tera Blast and Tera Starstorm will not change their Typings from Normal.

-Every move that is unaffected by -ate seems to extend VariableMoveTypeAttr 
https://github.com/pagefaultgames/pokerogue/blob/f2ef3620b56576c35b5cf478cafef572c943b05c/src/data/move.ts#L4890C40-L4890C59

Link to Discord's Bug Report (Base Tera Blast doesn't work with Pixilate)
https://discord.com/channels/1125469663833370665/1280404498157797448

### Reproduction

Have Tera Blast or Tera Starstorm on a Pokémon with an ability that modifies move Typing.
-ie. Aerilate, Galvanize, Refrigerate, Pixilate

### Expected behavior

BlastStartstormAerilate

> If the user is not Terastallized, Tera Blast will be affected by Abilities such as Galvanize, but if the user Terastallized into a Normal type, Tera Blast will remain Normal.
-Bulba

When not Tera'd Tera Blast and Tera Starstorm should be affected by -Ate Abilities.
(Tera Blast and Tera Starstorm seem to be exceptions to the rule)

### Screenshots / Videos

Aerilate does not make Tera Blast or Tera Starstorm Flying-Type

https://github.com/user-attachments/assets/bec36ce0-80fa-4ba0-a801-6d8be27c7ffd

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Revelation Dance and Terrain Pulse is unaffected by Aerilate, which is correct

> Revelation Dance is unaffected by Normalize, Pixilate, Refrigerate, Aerilate, and Galvanize.

>Terrain Pulse is unaffected by Normalize, Pixilate, Refrigerate, and Galvanize.
-Bulba

https://github.com/user-attachments/assets/11e19023-3af0-4069-acf2-d32483e13e4d

Terrain Pulse and Rev Dance unaffected Aerilate

### LINKED ISSUE #577: [Bug] Embody Aspect Crashes Whenever Ogerpon is Recalled While not Present on the Field and Unfainted
Copied over from PKR 5004

### Describe the bug

When Ogerpon is in a Mask Form, and gains Embody Aspect, the game crashes if Ogerpon isn't active on the field and not fainted.

Also occurs with Mystery Encounter recalls.

Link to Discord's Bug Report (Ogerpon's Embody Aspect when Tera'd is causing the game to stop loading.)
https://discord.com/channels/1125469663833370665/1290282888885047400

### Reproduction

```
import { Type } from "#enums/type";
//Under WeatherType in the imports section

ITEM_REWARD_OVERRIDE: [{name: "TERA_SHARD", type: Type.GRASS}]
```
Begin a run with a Pokemon and Ogerpon Teal-Mask, Tera Ogerpon with a Grass Shard, then beat wave 4 with Ogerpon not active on the field or Fainted.

### Expected behavior

Embody Aspect should not crash the game when Pokemon are recalled and Ogerpon is Mask-Tera'd and not active.

### Screenshots / Videos

Trainer Battle Transition, Ogerpon Teal Mask

https://github.com/user-attachments/assets/3fd3fe0b-a79f-4242-857a-735863d99f21

Biome Transition, Ogerpon Teal Mask

https://github.com/user-attachments/assets/5466a268-6902-4bcf-a54e-5eb5cd49c801

Console Errors
-Embody Aspect Ability Flyout shows up before Crashing

Embody Aspect Crash Console, participated

Trainer Battle Transition, Ogerpon Hearthflame Mask

https://github.com/user-attachments/assets/9edc8527-2c64-4b50-b711-2f2f48d206ad

### Session export file

_No response_

### User data export file

_No response_

### Additional context

> Embody Aspect uses PostBattleInitAbAttr, so the ability only activates at the end of waves right before the battle is about to be re-initialized (e.g. before trainer battles or ME's) 
> (For reference, abilities like Zero to Hero also use PostBattleInitAbAttr to ensure that Palafin is in non-Hero form upon starting the battle) 
-PigeonBar

### LINKED ISSUE #578: [Bug] Stellar Terapagos and Mask-Tera'd Ogerpon Remain in Tera-Exclusive Forms when Other Tera Shard is Used
Copied over from PKR 5005

### Describe the bug

Terapagos and Ogerpon remain in their Tera-exclusive forms when a different Tera Shard is used on them.

Examples:
-Stellar-Tera Terapagos remains in its Stellar Form when a Fire Tera Shard is used on it, resulting in a Fire-Tera Stellar Form Terapagos.

-Ogerpon Teal Mask remains in its Teal-Mask-Tera form when a Fire Tera Shard is used on it, resulting in a Fire-type Teal-Mask-Tera Ogerpon. 

### Reproduction

Begin runs with Terapagos and Ogerpon, choose the appropriate Shards, then choose the other shard after their forms have changed.

```
import { Type } from "#enums/type";
//Under WeatherType in the imports section

ITEM_REWARD_OVERRIDE: [{name: "TERA_SHARD", type: Type.STELLAR}, {name: "TERA_SHARD", type: Type.GRASS}]
```

### Expected behavior

> Ogerpon cannot have its Tera Type be changed under normal circumstances in Pokémon Scarlet and Violet. Even if the game is modified to force Ogerpon to have a different Tera Type, the game will softlock upon trying to Terastallize, forcing the player to restart the console. It shares this distinction with Terapagos.

Ogerpon normally cannot have its Tera Type changed.

 I'd expect that because Teal-Mask-Tera is always Grass-Type, it should revert to base Ogerpon if its Tera-type is changed.

### Screenshots / Videos

Terapagos remains in its Stellar form when Terastallized into a different Tera-Type from Stellar.

https://github.com/user-attachments/assets/eeea4df7-e032-4b19-bce2-1892a16b3a09

Ogerpon remains in its Teal-Mask-Tera form when Terastallized into a different Tera-Type from Grass.

https://github.com/user-attachments/assets/dc5b73d4-fd52-4b30-97df-29b37f45657c

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Both Ogerpon and Terapagos can currently Tera into Tera-Types they would not be able to in the mainline games.

-Terapagos and Ogerpon both have access to every Tera-Type when they would usually be restricted; Ogerpon with the Tera-Type that matches its current Mask, and Terapagos with Stellar.

Terapagos can Grass

https://github.com/user-attachments/assets/9678c841-36c5-469e-82f0-373cc1bf5a4e

> Some Pokémon species have unique Terastallized states, which change their appearance significantly upon Terastallizing, beyond the standard crystallized appearance of Terastallization. Additionally, the Pokémon's Ability changes after the Terastallization. There is no official name for this class of Terastallized state. **Unlike other Pokémon, the few ones with a unique Terastallized state are the only ones which cannot have their Tera Types changed in Treasure Eatery.**

> Terapagos cannot have any other Tera Type than Stellar.

> The Teal Mask draws upon the power of grass; while wearing it, Ogerpon's Tera Type is always Grass.

> The Hearthflame Mask draws upon the power of fire; while wearing it, Ogerpon's Tera Type is always Fire

> The Wellspring Mask draws upon the power of water; while wearing it, Ogerpon's Tera Type is always Water. 

>The Cornerstone Mask draws upon the power of stone; while wearing it, Ogerpon's Tera Type is always Rock.

-Bulba

> in a perfect world, no shard would work on terapagos
> it would be stellar by default with tera rework

-Blitzy

### LINKED ISSUE #643: [Bug] Bug Type Superfan Checks Tera Inconsistently
Copied over from PKR 5289

### Describe the bug

Bug Type Superfan does not consider Tera for Eligibility for the "Show them your Bug Types" option, but does immediately afterwards when tallying your Bug types.

Link to Discord's Bug Report (Bug type superfan not counting terastallised pokemon as bug types)
https://discord.com/channels/1125469663833370665/1329854840880496821

### Reproduction

Start with a Bug Type Pokemon.

Start with no Bug Type Pokemon, and change the TeraType to Bug.
```
import { Type } from "#enums/type";
```
```
	STARTING_WAVE_OVERRIDE: 11,

       // ABILITY_OVERRIDE: Abilities.BEAST_BOOST

	MYSTERY_ENCOUNTER_RATE_OVERRIDE: 255,

	MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.BUG_TYPE_SUPERFAN

	ITEM_REWARD_OVERRIDE: [{name: "TERA_SHARD", type: Type.ELECTRIC}],
	STARTING_HELD_ITEMS_OVERRIDE: [{name: "TERA_SHARD", type: Type.ELECTRIC}],
```

### Expected behavior

Bug Type Superfan should be consistent in how it checks for Bug-Type Pokemon. As they seem to be an expert, they should probably be able to tell a Bug-Type Pokemon is a Bug regardless of its current Tera.

### Screenshots / Videos

Initial check sees past Tera, Tally does not

https://github.com/user-attachments/assets/a9cdab66-0f07-4285-b7b6-29375bb69039

Tally will not count Bug Type Pokemon that have Terastallized to become not-Bug Type.

https://github.com/user-attachments/assets/a94ae8c9-74c7-45c3-af10-95cc1f587b36

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Dark Deal does not look at Tera when deciding the Transmogrification product.

### LINKED ISSUE #1046: [Ability] Implement Embody Aspect
> [!CAUTION]
> Dependent on Form Change refactor

 https://bulbapedia.bulbagarden.net/wiki/Embody_Aspect_(Ability)

### PR DESCRIPTION
**Pull request by DayKev**
> [!IMPORTANT]
> **This PR updates locales!**

> [!TIP]
> ### Follow Up Issues
>  <details><summary>Show</summary>
> <p>
> 
> - #889 
> - #986
> - #987 
> - #988
>   - requires #885
> - #989 
> - #997 
> 
> </p>
> </details> 
> 

## What are the changes the user will see?
- The player will be able to Terastallize their Pokémon in [the same way they can in Scarlet and Violet](https://bulbapedia.bulbagarden.net/wiki/Terastal_phenomenon#Effects) once they get a Tera Orb, with the effects also now matching mainline.
- Players can choose the Tera type of their starters based on that starter's existing types.
- ~Tera shards will be able to change the tera type of a Pokémon.~ To be added in a future PR after items have been refactored.

## Why am I making these changes?
Align Tera behavior with mainline.

### Features
- Tera type of starters can be cycled on the starter select screen for dual-type Pokémon.
- Terastallization is enabled in battle when the player has a Tera Orb.
- Terastallization can be initiated from the fight UI by using the button to the left of the "Fight" and "Pokemon" commands.
- Terastallization lasts until the arena is reset or the Terastallized Pokémon faints.
- Only one Pokémon can be Terastallized at a time, and cannot be used on Mega or GMax Pokémon.
- Once Terastallization is used, the player cannot use it again until the Tera Orb is recharged, which happens in the `PartyHealPhase` that happens after every 10th wave. Alternatively, if the player has a Terapagos in their party it will automatically be recharged every wave. It will also automatically recharge on the E4 waves (181-190).

### Bugs Fixed
- Tera Stellar no longer modifies a Pokémon's defensive typing.
- Tera Stellar now properly boosts damage based on mainline behavior.
- Fixes #570 
- Fixes #577 
- Fixes #578 

### Misc Changes
- New test helper function added to Terastallize a Pokémon to any type.
- Terapagos locked to Stellar Tera type.
- Ogerpon locked to the Tera type of its matching form.
- Shedinja locked to Bug Tera type (custom).
- Embody Aspect is no longer partial.

## Screenshots/Videos
<details><summary>Tera button on fight UI</summary>
<p>

image

</p>
</details> 
<details><summary>Terastallized Pokémon</summary>
<p>

image

</p>
</details> 
<details><summary>Cursor replaced when about to Terastallize</summary>
<p>

image

</p>
</details> 
<details><summary>Light theme version of Tera cursor</summary>
<p>

image

</p>
</details> 
<details><summary>Tera type shown on starter select screen</summary>
<p>

image

</p>
</details> 
<details><summary>Tera type shown on Pokémon summary screen</summary>
<p>

image

</p>
</details> 

## How to test the changes?
Start a new Classic run to check that the player cannot Tera their Pokémon without a Tera Orb. Then use the following override and start a new run to test Tera behavior:
```ts
const overrides = {
  STARTING_MODIFIER_OVERRIDE: [{name: "TERA_ORB"}]
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [x] Have I made sure that any UI change works for both UI themes (dark and light)?

#### Are there any localization additions or changes? If so:

- [x] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [x] If so, please leave a link to it here: https://github.com/Despair-Games/poketernity-locales/pull/43
- [x] Have I added the `Localization` tag to this PR?

### CODE REVIEW

**Comment by DayKev** [comment]
Tera phase timing will be incorrect until after #885 is merged.

File: src/data/init/init-abilities.ts [hunk 1]
```diff
@@ -202,6 +203,12 @@ import { TerrainType } from "#enums/terrain-type";
 import { WeatherType } from "#enums/weather-type";
 import i18next from "i18next";
 
+/** Used for Aerialate, Refrigerate, Pixilate, Galvanize */
+const basicMoveTypeChangeAbilityCondition: PokemonAttackCondition = (user, _target, move) =>
```
Comment (DayKev) [inline src/data/init/init-abilities.ts]: A better name for this is welcome.

Comment (flx-sta) [reply src/data/init/init-abilities.ts]: So they all alter normal-type moves to something else.
- https://bulbapedia.bulbagarden.net/wiki/Galvanize_(Ability)
- https://bulbapedia.bulbagarden.net/wiki/Aerilate_(Ability)
- https://bulbapedia.bulbagarden.net/wiki/Pixilate_(Ability)
- https://bulbapedia.bulbagarden.net/wiki/Refrigerate_(Ability)

maybe:
```suggestion
const alterNormalTypeMoveCondition: PokemonAttackCondition = (user, _target, move) =>
```

or
```suggestion
const normalTypeConversionCondition: PokemonAttackCondition = (user, _target, move) =>
```

But I might be missing some context

**Comment by flx-sta** [comment]
> ## TODO
> 
> - Replace placeholder assets copied from Xavion's PR (can be done later)
> - Fix Terastallization timing (waiting for #885, will probably be done in a follow-up)
> - Trainers (will be done in a follow-up)
> - Tera shards to change a Pokémon's tera type (pending items refactor)
> - Terraform Zero ability (will be done in a follow-up)

@DayKev are there already follow-up issues/tasks in place so it doesn't get lost?

File: src/battle-scene.ts [hunk 2]
```diff
@@ -580,8 +581,8 @@ export default class BattleScene extends SceneBase {
 
     this.damageNumberHandler = new DamageNumberHandler();
 
-    this.spriteSparkleHandler = new PokemonSpriteSparkleHandler();
-    this.spriteSparkleHandler.setup();
+    this.spriteTeraSparkleHandler = new PokemonSpriteTeraSparkleHandler();
+    this.spriteTeraSparkleHandler.setup();
```
Comment (flx-sta) [inline src/battle-scene.ts:588]: NIT/Q: Why not call `setup()` in the contructor?

File: src/battle-scene.ts [hunk 3]
```diff
@@ -1373,7 +1374,16 @@ export default class BattleScene extends SceneBase {
 
         for (const pokemon of this.getPlayerParty()) {
           pokemon.resetWaveData();
+          pokemon.resetTera(); // TODO: put this in resetBattleData?
```
Comment (flx-sta) [inline src/battle-scene.ts]: Q: Is this `TODO` still relevant/open?

File: src/battle-scene.ts [hunk 4]
```diff
@@ -1373,7 +1374,16 @@ export default class BattleScene extends SceneBase {
...
+
           applyAbAttrs<PostBattleInitAbAttr>(AbAttrFlag.POST_BATTLE_INIT, pokemon, false);
+
+          if (
+            pokemon.species.speciesId === SpeciesId.TERAPAGOS
+            || (this.gameMode.isClassic && isBetween(this.currentBattle.waveIndex, 181, 190))
+          ) {
+            this.arena.playerTerasUsed = 0;
+          }
```
Comment (flx-sta) [inline src/battle-scene.ts]: I assume this is this:
> Upon capturing Terapagos at the end of [The Indigo Disk](https://bulbapedia.bulbagarden.net/wiki/The_Indigo_Disk), the Tera Orb will be infused with Terapagos' energy and will no longer require charging.

We should document that in a TLDR way

```suggestion

          // Upon capturing TERAPAGOS [...],  the Tera Orb will be infused with Terapagos' energy and will no longer require charging
          if (
            pokemon.species.speciesId === SpeciesId.TERAPAGOS
            || (this.gameMode.isClassic && isBetween(this.currentBattle.waveIndex, 181, 190))
          ) {
            this.arena.playerTerasUsed = 0;
          }
```

Although it seems that here the player hasn't caught it so not sure

File: src/data/init/init-abilities.ts [hunk 5]
```diff
@@ -202,6 +203,12 @@ import { TerrainType } from "#enums/terrain-type";
...
+  move?.type === ElementalType.NORMAL
+  && (!move.hasAttr(VariableMoveTypeAttr)
+    || ([MoveId.TERA_BLAST, MoveId.TERA_STARSTORM].includes(move.id) && !user?.isTerastallized));
```
Comment (flx-sta) [inline src/data/init/init-abilities.ts]: NIT: Please create a (frozen) array for those. e.g. in `move-utils`

```ts
const teraMoveIds = Object.freeze([MoveId.TERA_BLAST, MoveId.TERA_SANDSTORM]);
```

and then
```suggestion
    || (teraMoveIds.includes(move.id) && !user?.isTerastallized));
```

----

ALT: Create a helper method `move.isTeraMove()` (it could still check that array)

File: src/data/init/init-abilities.ts [hunk 6]
```diff
@@ -202,6 +203,12 @@ import { TerrainType } from "#enums/terrain-type";
...
+
 // prettier-ignore
```
Comment (flx-sta) [inline src/data/init/init-abilities.ts]: Q: is the prettier-ignore here still relevant?

File: src/data/init/init-moves.ts [hunk 7]
```diff
@@ -3259,7 +3259,7 @@ export function initMoves() {
       .attr(TeraBlastTypeAttr)
       .attr(TeraBlastPowerAttr)
       .attr(StatStageChangeAttr, [Stat.ATK, Stat.SPATK], -1, true, {
-        condition: (user, _target, _move) => user.isTerastallized() && user.isOfType(ElementalType.STELLAR),
+        condition: (user, _target, _move) => user.isTerastallized && user.isOfType(ElementalType.STELLAR),
```
Comment (flx-sta) [inline src/data/init/init-moves.ts:3262]: NIT: If you dont' need params after the optionals you can omit them:
```suggestion
        condition: (user) => user.isTerastallized && user.isOfType(ElementalType.STELLAR),
```

File: src/data/init/init-moves.ts [hunk 8]
```diff
@@ -3476,7 +3476,7 @@ export function initMoves() {
       .attr(TeraMoveCategoryAttr)
       .attr(TeraStarstormTypeAttr)
       .attr(VariableTargetAttr, (user, _target, _move) =>
-        user.species.speciesId === SpeciesId.TERAPAGOS && user.isTerastallized()
+        user.species.speciesId === SpeciesId.TERAPAGOS && user.isTerastallized
```
Comment (flx-sta) [inline src/data/init/init-moves.ts:3479]: NIT: If you dont' need params after the optionals you can omit them:
```suggestion
     .attr(VariableTargetAttr, (user) =>
        user.species.speciesId === SpeciesId.TERAPAGOS && user.isTerastallized
```

File: src/data/moves/move-attrs/add-type-attr.ts [hunk 9]
```diff
@@ -39,6 +39,6 @@ export class AddTypeAttr extends MoveEffectAttr {
   }
 
   override getCondition(): MoveConditionFunc {
-    return (_user, target, _move) => !target.isTerastallized() && !target.getTypes().includes(this.type);
+    return (_user, target, _move) => !target.isTerastallized && !target.getTypes().includes(this.type);
```
Comment (flx-sta) [inline src/data/moves/move-attrs/add-type-attr.ts:42]: NIT: If you dont' need params after the optionals you can omit them:

```suggestion
    return (_user, target) => !target.isTerastallized && !target.getTypes().includes(this.type);
```

File: src/data/mystery-encounters/utils/encounter-phase-utils.ts [hunk 10]
```diff
@@ -117,6 +118,7 @@ export interface EnemyPokemonConfig {
   modifierConfigs?: HeldModifierConfig[];
   tags?: BattlerTagType[];
   dataSource?: PokemonData;
+  tera?: ElementalType;
```
Comment (flx-sta) [inline src/data/mystery-encounters/utils/encounter-phase-utils.ts]: Q: Why `tera` here and `teraType` on Pokemon?

File: src/data/pokemon-forms.ts [hunk 11]
```diff
@@ -194,9 +176,7 @@ export class SpeciesFormChangeTeraTrigger extends SpeciesFormChangeTrigger {
  * @extends SpeciesFormChangeTrigger
  */
 export class SpeciesFormChangeLapseTeraTrigger extends SpeciesFormChangeTrigger {
```
Comment (flx-sta) [inline src/data/pokemon-forms.ts]: Q: So what's the purpose of this class now?

File: src/data/pokemon-forms.ts [hunk 12]
```diff
@@ -168,24 +167,7 @@ export class SpeciesDefaultFormMatchTrigger extends SpeciesFormChangeTrigger {
  * @extends SpeciesFormChangeTrigger
  */
 export class SpeciesFormChangeTeraTrigger extends SpeciesFormChangeTrigger {
```
Comment (flx-sta) [inline src/data/pokemon-forms.ts]: Q: So what's the purpose of this class now?

File: src/data/trainer-config.ts [hunk 13]
```diff
@@ -250,11 +250,41 @@ export const trainerPartyTemplates = {
...
   [key: number]: PartyMemberFunc;
 }
 
+class TrainerAI {
+  public teraMode: TeraAIMode;
+  public instantTeras: number[] = [];
+
+  /**
+   * @param canTerastallize Whether this trainer is allowed to tera
+   */
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: NIT: this doesn't match with the constructor params

File: src/data/trainer-config.ts [hunk 14]
```diff
@@ -640,6 +672,36 @@ export class TrainerConfig {
     return this;
   }
 
+  /**
+   * Sets random pokemon from the trainers team to instant tera. Uses their specialty types is they have one.
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: Typo
```suggestion
   * Sets random pokemon from the trainers team to instant tera. Uses their specialty types if they have one.
```

File: src/data/trainer-config.ts [hunk 15]
```diff
@@ -640,6 +672,36 @@ export class TrainerConfig {
...
+   * @param count The amount of pokemon to have instant tera
+   * @returns this
+   */
+  setRandomTeraModifiers(count: () => number): TrainerConfig {
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: Q: Why is the param called `count` but it's a fn returning a number? That's so odd and the name might be misleading then

File: src/data/trainer-config.ts [hunk 16]
```diff
@@ -640,6 +672,36 @@ export class TrainerConfig {
...
+      const partyMemberIndexes = new Array(party.length).fill(null).map((_, i) => i);
+      for (let t = 0; t < Math.min(count(), party.length); t++) {
+        const randomIndex = randSeedItem(partyMemberIndexes);
+        partyMemberIndexes.splice(partyMemberIndexes.indexOf(randomIndex), 1);
+        if (this.specialtyTypes?.length) {
+          party[randomIndex].teraType = randSeedItem(this.specialtyTypes);
+        }
+        this.trainerAI.setInstantTera(randomIndex);
+      }
+    });
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: NIT:
```suggestion
    this.genAIFuncs.push((party: EnemyPokemon[]) => {
      const { length } = party;
      const partyMemberIndexes = Array.from({ length }).map((_, i) => i);
      for (let t = 0; t < Math.min(count(), length); t++) {
        const randomIndex = randSeedItem(partyMemberIndexes);
        partyMemberIndexes.splice(partyMemberIndexes.indexOf(randomIndex), 1);
        if (this.specialtyTypes?.length) {
          party[randomIndex].teraType = randSeedItem(this.specialtyTypes);
        }
        this.trainerAI.setInstantTera(randomIndex);
      }
    });
```

File: src/data/trainer-config.ts [hunk 17]
```diff
@@ -640,6 +672,36 @@ export class TrainerConfig {
     return this;
   }
 
+  /**
+   * Sets random pokemon from the trainers team to instant tera. Uses their specialty types is they have one.
+   * @param count The amount of pokemon to have instant tera
+   * @returns this
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: NIT: Match existing docs:
```suggestion
   * @returns this {@linkcode TrainerConfig}
```

File: src/data/trainer-config.ts [hunk 18]
```diff
@@ -640,6 +672,36 @@ export class TrainerConfig {
...
+        this.trainerAI.setInstantTera(randomIndex);
+      }
+    });
+    return this;
+  }
+
+  /**
+   * Sets a specific pokemon to instant tera
+   * @param index The index within the team to have instant tera
+   * @returns this
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: NIT: Match existing docs:
```suggestion
   * @returns this {@linkcode TrainerConfig}
```

File: src/data/trainer-config.ts [hunk 19]
```diff
@@ -1648,21 +1712,21 @@ export function getSpeciesFilterRandomPartyMemberFunc(
...
+//   const ret: PersistentModifier[] = [];
+//   ret.push(
+//     modifierTypes
+//       .TERA_SHARD()
+//       .generateType([], [teraType])!
+//       .withIdFromFunc(modifierTypes.TERA_SHARD)
+//       .newModifier(party[partySlot]) as PersistentModifier,
+//   );
+//   return ret;
+// }
```
Comment (flx-sta) [inline src/data/trainer-config.ts:1725]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-config.ts [hunk 20]
```diff
@@ -1308,9 +1371,10 @@ export class TrainerConfig {
     this.setStaticParty();
     this.setHasVoucher(true);
     this.setVictoryBgm("victory_gym");
-    this.setGenModifiersFunc((party) =>
-      getRandomTeraModifiers(party, 1, specialtyTypes.length ? specialtyTypes : undefined),
-    );
+    // this.setGenModifiersFunc((party) =>
+    //   getRandomTeraModifiers(party, 1, specialtyTypes.length ? specialtyTypes : undefined),
+    // );
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: Q: Forgot to remove it? If not add a note/todo why it's not

File: src/data/trainer-config.ts [hunk 21]
```diff
@@ -1308,9 +1371,10 @@ export class TrainerConfig {
...
+    this.setRandomTeraModifiers(() => 1); // TODO: is this what we want?
```
Comment (flx-sta) [inline src/data/trainer-config.ts]: Q: This Todo still relevant/open?

File: src/data/trainer-config.ts [hunk 22]
```diff
@@ -1671,19 +1735,19 @@ function getSpecificTeraModifier(
...
+//     ret.push(
+//       modifierTypes
+//         .TERA_SHARD()
+//         .generateType([], [randSeedItem(types ? types : party[randomIndex].getTypes())])!
+//         .withIdFromFunc(modifierTypes.TERA_SHARD)
+//         .newModifier(party[randomIndex]) as PersistentModifier,
+//     ); // TODO: is the bang correct?
+//   }
+//   return ret;
+// }
```
Comment (flx-sta) [inline src/data/trainer-config.ts:1750]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/champion-trainer-configs.ts [hunk 23]
```diff
@@ -232,17 +229,17 @@ export const championTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const teraPokemon = party[4];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [ElementalType.FIRE])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/champion-trainer-configs.ts:243]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/champion-trainer-configs.ts [hunk 24]
```diff
@@ -321,28 +318,28 @@ export const championTrainerConfigs: TrainerConfigs = {
...
+  //       teraType = ElementalType.WATER;
+  //   }
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [teraType])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/champion-trainer-configs.ts:344]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/champion-trainer-configs.ts [hunk 25]
```diff
@@ -386,17 +383,17 @@ export const championTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const teraPokemon = party[4];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [ElementalType.FLYING])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/champion-trainer-configs.ts:399]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/champion-trainer-configs.ts [hunk 26]
```diff
@@ -429,28 +426,28 @@ export const championTrainerConfigs: TrainerConfigs = {
...
+  //       teraType = ElementalType.WATER;
+  //   }
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [teraType])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/champion-trainer-configs.ts:454]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/evil-boss-trainer-configs.ts [hunk 27]
```diff
@@ -657,17 +655,17 @@ export const evilBossTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const teraPokemon = party[4];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [teraPokemon.species.type1])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/evil-boss-trainer-configs.ts:669]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/evil-boss-trainer-configs.ts [hunk 28]
```diff
@@ -725,15 +723,15 @@ export const evilBossTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const teraPokemon = party[0];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [teraPokemon.species.type1])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(teraPokemon) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/evil-boss-trainer-configs.ts:738]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/rival-trainer-configs.ts [hunk 29]
```diff
@@ -315,17 +314,17 @@ export const rivalTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const starter = party[0];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [starter.species.type1])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(starter) as PersistentModifier,
+  //   ]; // TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/rival-trainer-configs.ts:328]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/rival-trainer-configs.ts [hunk 30]
```diff
@@ -413,17 +412,17 @@ export const rivalTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const starter = party[0];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [starter.species.type1])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(starter) as PersistentModifier,
+  //   ]; //TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/rival-trainer-configs.ts:427]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/data/trainer-configs/rival-trainer-configs.ts [hunk 31]
```diff
@@ -519,15 +518,15 @@ export const rivalTrainerConfigs: TrainerConfigs = {
...
+  // .setGenModifiersFunc((party) => {
+  //   const starter = party[0];
+  //   return [
+  //     modifierTypes
+  //       .TERA_SHARD()
+  //       .generateType([], [starter.species.type1])!
+  //       .withIdFromFunc(modifierTypes.TERA_SHARD)
+  //       .newModifier(starter) as PersistentModifier,
+  //   ]; // TODO: is the bang correct?
+  // }),
```
Comment (flx-sta) [inline src/data/trainer-configs/rival-trainer-configs.ts:534]: Q: forgot to remove it? if not add a note/todo why it's not

File: src/enums/common-anim.ts [hunk 32]
```diff
@@ -48,4 +48,5 @@ export enum CommonAnim {
   GRASSY_TERRAIN,
   PSYCHIC_TERRAIN,
   LOCK_ON = 2120,
+  TERASTALLIZE,
```
Comment (flx-sta) [inline src/enums/common-anim.ts:51]: Q: Should this follow after the artificially high `LOCK_ON = 2120`?

File: src/enums/phase-id.ts
Comment (flx-sta) [inline src/enums/phase-id.ts:1]: Dang... that's a lot of detail work

File: src/field/pokemon.ts [hunk 33]
```diff
@@ -100,7 +100,7 @@ import { VariableMoveTypeMultiplierAttr } from "#app/data/moves/move-attrs/varia
 import { getNatureStatMultiplier } from "#app/data/nature";
 import { starterPassiveAbilities } from "#app/data/passives";
 import type { SpeciesEvolutionCondition, SpeciesFormEvolution } from "#app/data/pokemon-evolutions";
-import type { SpeciesFormChange } from "#app/data/pokemon-forms";
+import { SpeciesFormChangeLapseTeraTrigger, type SpeciesFormChange } from "#app/data/pokemon-forms";
```
Comment (flx-sta) [inline src/field/pokemon.ts:103]:
```suggestion
import { SpeciesFormChangeLapseTeraTrigger, type SpeciesFormChange } from "#app/data/pokemon-forms";
import type { SpeciesFormChange } from "#app/data/pokemon-forms";
```

Or did I miss the mark this time :D

File: src/field/pokemon.ts [hunk 34]
```diff
@@ -269,6 +268,9 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
   public pokerus: boolean;
   public switchOutStatus: boolean;
   public evoCounter: number;
+  protected _teraType: ElementalType;
+  public isTerastallized: boolean = false; // TODO: put this in battle data?
+  public stellarTypesBoosted: ElementalType[] = []; // TODO: put this in battle data?
```
Comment (flx-sta) [inline src/field/pokemon.ts]: Q: Are those TODOs still open?

File: src/field/pokemon.ts [hunk 35]
```diff
@@ -410,6 +417,48 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
     }
   }
 
+  public get teraType(): ElementalType {
```
Comment (flx-sta) [inline src/field/pokemon.ts:426]: NIT: tsdoc

File: src/field/pokemon.ts [hunk 36]
```diff
@@ -410,6 +417,48 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
+        }
+
+      case SpeciesId.SHEDINJA:
+        return ElementalType.BUG;
+    }
+
+    return this._teraType;
+  }
+
+  public set teraType(value: ElementalType) {
```
Comment (flx-sta) [inline src/field/pokemon.ts:455]: NIT: tsdoc

File: src/field/pokemon.ts [hunk 37]
```diff
@@ -410,6 +417,48 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
+    this._teraType = value;
+  }
+
+  public resetTera(): void {
```
Comment (flx-sta) [inline src/field/pokemon.ts:463]: NIT: tsdoc

File: src/field/pokemon.ts [hunk 38]
```diff
@@ -1376,9 +1429,9 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
   public getTypes(includeTeraType = false, forDefend: boolean = false, baseOnly: boolean = false): ElementalType[] {
     const types: ElementalType[] = [];
 
-    if (includeTeraType) {
-      const teraType = this.getTeraType();
-      if (teraType !== ElementalType.UNKNOWN) {
+    if (includeTeraType && this.isTerastallized) {
+      const teraType = this.teraType;
+      if (!(forDefend && teraType === ElementalType.STELLAR)) {
```
Comment (flx-sta) [inline src/field/pokemon.ts:1446]: Q: Does `ElementalType.UNKNOWN` not need any special handling anymore?

File: src/field/pokemon.ts [hunk 39]
```diff
@@ -3061,16 +3094,28 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
+
+      if (
+        source.teraType === ElementalType.STELLAR
+        && (!source.stellarTypesBoosted.includes(moveType) || source.species.speciesId === SpeciesId.TERAPAGOS)
+      ) {
+        stabMultiplier.value += matchesSourceType ? 0.5 : 0.2;
+      }
     }
 
     applyAbFunc<StabBoostAbAttr>(AbAttrFlag.STAB_BOOST, source, simulated, stabMultiplier);
```
Comment (flx-sta) [inline src/field/pokemon.ts]: NIT: Might wanna move the whole `stab` logic into an enclosed helper method (out of scope possibly)

File: src/field/pokemon.ts [hunk 40]
```diff
@@ -3393,6 +3438,16 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
     return maxForms.includes(this.getFormKey());
   }
 
+  isMega(): boolean {
```
Comment (flx-sta) [inline src/field/pokemon.ts]: NIT: tsdoc

File: src/field/pokemon.ts [hunk 41]
```diff
@@ -3393,6 +3438,16 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
+    const megaForms = [
+      SpeciesFormKey.MEGA,
+      SpeciesFormKey.MEGA_X,
+      SpeciesFormKey.MEGA_Y,
+      SpeciesFormKey.PRIMAL,
+    ] as string[];
+    return megaForms.includes(this.getFormKey());
```
Comment (flx-sta) [inline src/field/pokemon.ts]: Q: Can't you define the array as `string[]` to begin with?
```suggestion
    const megaForms: string[] = [
      SpeciesFormKey.MEGA,
      SpeciesFormKey.MEGA_X,
      SpeciesFormKey.MEGA_Y,
      SpeciesFormKey.PRIMAL,
    ];
    return megaForms.includes(this.getFormKey());
```

File: src/field/trainer.ts [hunk 42]
```diff
@@ -618,6 +620,12 @@ export default class Trainer extends Phaser.GameObjects.Container {
     return [];
   }
 
+  public genAI(party: EnemyPokemon[]): void {
```
Comment (flx-sta) [inline src/field/trainer.ts:624]: NIT: tsdoc

File: src/field/trainer.ts [hunk 43]
```diff
@@ -739,4 +747,13 @@ export default class Trainer extends Phaser.GameObjects.Container {
       }
     });
   }
+
+  public shouldTera(pokemon: EnemyPokemon): boolean {
```
Comment (flx-sta) [inline src/field/trainer.ts:756]: NIT: tsdoc

File: src/ui/handlers/fight-ui-handler.ts [hunk 44]
```diff
@@ -18,8 +20,8 @@ import { MoveCategory } from "#enums/move-category";
 import { TextStyle } from "#enums/text-style";
 import { UiMode } from "#enums/ui-mode";
 import i18next from "i18next";
-import { UiHandler } from "./abstract-ui-handler";
-import type { CommandUiHandler } from "./command-ui-handler";
+
+type FightCommand = BattleCommand.FIGHT | BattleCommand.TERA;
```
Comment (flx-sta) [inline src/ui/handlers/fight-ui-handler.ts]: NIT: Probably should define that somewhere more global. I've seen that definition in a previous file before without this "helper" type being used

File: src/ui/handlers/run-info-ui-handler.ts [hunk 45]
```diff
@@ -487,17 +487,11 @@ export class RunInfoUiHandler extends UiHandler {
   private parseTrainerDefeat(enemyContainer: Phaser.GameObjects.Container) {
     // Loads and adds trainer sprites to the UI
     this.showTrainerSprites(enemyContainer);
-    // Determining which Terastallize Modifier belongs to which Pokemon
+    // Old behavior: Determining which Terastallize Modifier belongs to which Pokemon
     // Creates a dictionary {PokemonId: TeraShardType}
+
+    // TODO: get tera'd pokemon
```
Comment (flx-sta) [inline src/ui/handlers/run-info-ui-handler.ts:493]: Q: TODO still relevant/open?

File: src/ui/handlers/run-info-ui-handler.ts [hunk 46]
```diff
@@ -511,13 +505,16 @@ export class RunInfoUiHandler extends UiHandler {
       enemyData["player"] = true;
       const enemy = enemyData.toPokemon();
       const enemyIcon = globalScene.addPokemonIcon(enemy, 0, 0, 0, 0);
+
       // Applying Terastallizing Type tint to Pokemon icon
+      // TODO: update this
```
Comment (flx-sta) [inline src/ui/handlers/run-info-ui-handler.ts:510]: Q: TODO still relevant/open?

**Review by flx-sta — COMMENTED** [review]
### Pure Code-Review
image

File: src/data/init/init-abilities.ts (hunk 1 above)
Comment (Tempo-anon) [reply src/data/init/init-abilities.ts]: I've heard these abilities referred to as -ate abilities online but I don't know if that would be a good name. Also for reference, the only abilities that change move types are Aerilate/Galvanize/Pixilate/Refrigerate which change normal->flying/electric/fairy/ice and give a 20% boost, normalize (change everything to normal and give a 20% boost), and liquid voice (changes sound moves to water with no atk boost)

File: src/data/trainer-config.ts [hunk 47]
```diff
@@ -250,11 +250,41 @@ export const trainerPartyTemplates = {
...
 type GenModifiersFunc = (party: EnemyPokemon[]) => PersistentModifier[];
+type GenAIFunc = (party: EnemyPokemon[]) => void;
 
 export interface PartyMemberFuncs {
   [key: number]: PartyMemberFunc;
 }
 
+class TrainerAI {
+  public teraMode: TeraAIMode;
+  public instantTeras: number[] = [];
```
Comment (Tempo-anon) [inline src/data/trainer-config.ts:262]: I remember there was some talk of limiting 1 tera per team. Will that also be true for enemy trainers?

File: src/data/trainer-config.ts (hunk 21 above)
Comment (Tempo-anon) [reply src/data/trainer-config.ts]: Bleh I should have documented this better when I changed it. This gives all E4 a tera of their type to a random Pokemon on the team

File: src/field/pokemon.ts [hunk 48]
```diff
@@ -410,6 +417,48 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
+          case 2:
+          case 6:
+            return ElementalType.FIRE;
+          case 3:
+          case 7:
+            return ElementalType.ROCK;
+        }
+
+      case SpeciesId.SHEDINJA:
+        return ElementalType.BUG;
```
Comment (Tempo-anon) [inline src/field/pokemon.ts:449]: Is this custom?

File: src/battle-scene.ts (hunk 4 above)
Comment (Tempo-anon) [reply src/battle-scene.ts]: Would also add on to that comment about how it's automatically recharged from 181-190

File: src/data/trainer-config.ts (hunk 47 above)
Comment (flx-sta) [reply src/data/trainer-config.ts:262]: > 1 of each per Team

Which includes Tera

[image](https://discord.com/channels/1312659961502761000/1343699671524048957/1347116929218908201)

File: src/battle-scene.ts (hunk 3 above)
Comment (DayKev) [reply src/battle-scene.ts]: Yes, though it depends on whether we go through with having the arena reset every wave or not.

File: src/battle-scene.ts (hunk 2 above)
Comment (DayKev) [reply src/battle-scene.ts:588]: Dunno, I didn't write the class, I only renamed it.

File: src/data/init/init-abilities.ts (hunk 6 above)
Comment (DayKev) [reply src/data/init/init-abilities.ts]: It was added to prevent prettier from mangling the move/ability arrays.

File: src/data/mystery-encounters/utils/encounter-phase-utils.ts (hunk 10 above)
Comment (DayKev) [reply src/data/mystery-encounters/utils/encounter-phase-utils.ts]: Missed renaming, will change.

File: src/enums/common-anim.ts (hunk 32 above)
Comment (DayKev) [reply src/enums/common-anim.ts:51]: I don't think it matters? Not sure. Inner might know, he's been doing work on the animations system; or possibly cam.

File: src/field/pokemon.ts (hunk 33 above)
Comment (DayKev) [reply src/field/pokemon.ts:103]: Mixed imports (`import { X, type Y } from Z`) are okay, it's only when all imports from the file are type imports (`import { type X, type Y } from Z`) that it should be brought outside the brackets. The new ESLint rule will catch this for us so we don't need to worry about it.

File: src/field/pokemon.ts (hunk 38 above)
Comment (DayKev) [reply src/field/pokemon.ts:1446]: Checking for `UNKNOWN` was the old way of checking if a pokemon was Terastallized or not, because non-Terastallized pokemon would have a Tera type of `UNKNOWN` and only Terastallized pokemon would have a Tera type. Now, all pokemon have a Tera type by default.

File: src/field/pokemon.ts (hunk 41 above)
Comment (DayKev) [reply src/field/pokemon.ts]: Probably, this was copy-pasted. Will check.

File: src/ui/handlers/fight-ui-handler.ts (hunk 44 above)
Comment (DayKev) [reply src/ui/handlers/fight-ui-handler.ts]: True, will do.

File: src/data/trainer-config.ts (hunk 47 above)
Comment (DayKev) [reply src/data/trainer-config.ts:262]: Yes, though MEs might want to break the rule. I'll double check whether MEs also use this field or not.

File: src/field/pokemon.ts (hunk 48 above)
Comment (DayKev) [reply src/field/pokemon.ts:449]: I think so. I'll add a note.

**Comment by DayKev** [comment]
> > ## TODO
> > 
> > * Replace placeholder assets copied from Xavion's PR (can be done later)
> > * Fix Terastallization timing (waiting for [[Feature] Add uniform dynamic turn command scheduling #885](https://github.com/Despair-Games/poketernity/pull/885), will probably be done in a follow-up)
> > * Trainers (will be done in a follow-up)
> > * Tera shards to change a Pokémon's tera type (pending items refactor)
> > * Terraform Zero ability (will be done in a follow-up)
> 
> @DayKev are there already follow-up issues/tasks in place so it doesn't get lost?

Created issues for the ones that didn't already have them.

File: src/data/trainer-config.ts (hunk 47 above)
Comment (Tempo-anon) [reply src/data/trainer-config.ts:262]: I don't think any MEs do. The only MEs that might have to do with tera are the expert breeder which has a steel clefable and mysterious challengers which calls a gym leader. There's also the clown event that changes types but that's unrelated to tera at all (maybe it should?)

File: src/data/init/init-abilities.ts (hunk 1 above)
Comment (flx-sta) [reply src/data/init/init-abilities.ts]: https://pokemondb.net/pokebase/244961/what-are-all-of-the-ate-abilitites

File: src/battle-scene.ts (hunk 3 above)
Comment (flx-sta) [reply src/battle-scene.ts]: Won't be able to resolve it in this PR I'd say

**Comment by flx-sta** [comment]
> Created issues for the ones that didn't already have them.

I'mma link them here:
- #989 
- #988 
- #987 
- #986

File: src/enums/common-anim.ts (hunk 32 above)
Comment (DayKev) [reply src/enums/common-anim.ts:51]: Asked Inner, it doesn't matter.

File: src/ui/handlers/run-info-ui-handler.ts (hunk 45 above)
Comment (DayKev) [reply src/ui/handlers/run-info-ui-handler.ts:493]: Oh yeah, I'll make an issue for this too.

File: src/data/trainer-config.ts (hunk 15 above)
Comment (DayKev) [reply src/data/trainer-config.ts]: I have changes planned for this in a follow-up so I'll address it then too.

File: src/data/trainer-config.ts (hunk 47 above)
Comment (DayKev) [reply src/data/trainer-config.ts:262]: This field is set by MEs (currently only expert breeder as mentioned) to determine which Pokemon to Terastallize. Since we might decide that a new ME in the future is allowed to break the rules and have more than one pokemon Terastallize, it'll need to stay an array for now.

File: src/data/pokemon-forms.ts (hunk 12 above)
Comment (DayKev) [reply src/data/pokemon-forms.ts]: It's a manual form change trigger. It's separate so that it can be triggered separately.

File: src/data/init/init-moves.ts [hunk 49]
```diff
@@ -3259,7 +3259,7 @@ export function initMoves() {
       .attr(TeraBlastTypeAttr)
       .attr(TeraBlastPowerAttr)
       .attr(StatStageChangeAttr, [Stat.ATK, Stat.SPATK], -1, true, {
-        condition: (user, _target, _move) => user.isTerastallized() && user.isOfType(ElementalType.STELLAR),
+        condition: (user) => user.isTerastallized && user.isOfType(ElementalType.STELLAR),
```
Comment (DayKev) [inline src/data/init/init-moves.ts]: I'm not sure it's best to remove the unused params in cases like these since in the future if it's necessary to use them it's not obvious to developers that they're available to be used.

**Comment by DayKev** [comment]
Updates based on reviews starting at `537801e`

File: src/battle-scene.ts [hunk 50]
```diff
@@ -1373,7 +1373,18 @@ export default class BattleScene extends SceneBase {
...
           pokemon.resetWaveData();
+          pokemon.resetTera(); // TODO: put this in resetWaveData once Arena reset behavior is changed?
+
           applyAbAttrs<PostBattleInitAbAttr>(AbAttrFlag.POST_BATTLE_INIT, pokemon, false);
+
+          if (
+            // In Scarlet/Violet, the player's Tera Orb automatically recharges after every battle once they've caught Terapagos
+            pokemon.species.speciesId === SpeciesId.TERAPAGOS
+            // The player's Tera Orb also automatically recharges when fighting the Elite 4 or in Area Zero (the endgame area)
+            || (this.gameMode.isClassic && this.currentBattle.waveIndex > 180)
```
Comment (flx-sta) [inline src/battle-scene.ts]: NIT: Since this is the wave where apparently Elite-4 start, can we give this wave-index a name as a constant so it's not a "magic-number"?

File: src/constants/move-constants.ts [hunk 51]
```diff
@@ -0,0 +1,3 @@
+import { MoveId } from "#enums/move-id";
+
+export const TERA_MOVES = Object.freeze([MoveId.TERA_BLAST, MoveId.TERA_STARSTORM]);
```
Comment (flx-sta) [inline src/constants/move-constants.ts:3]: NIT: @Tempo-anon recently asked about the const pattern, as it's inconsistent. It seems we have chosen `PascalCase` instead of `UPPER_SNAKE_CASE`.

File: src/data/init/init-moves.ts (hunk 49 above)
Comment (flx-sta) [reply src/data/init/init-moves.ts]: Feel free to restore them then if you don't feel confident about that change:

```suggestion
        condition: (user, _target, _move) => user.isTerastallized && user.isOfType(ElementalType.STELLAR),
```

File: src/data/moves/move-attrs/add-type-attr.ts [hunk 52]
```diff
@@ -39,6 +39,6 @@ export class AddTypeAttr extends MoveEffectAttr {
   }
 
   override getCondition(): MoveConditionFunc {
-    return (_user, target, _move) => !target.isTerastallized() && !target.getTypes().includes(this.type);
+    return (_user, target) => !target.isTerastallized && !target.getTypes().includes(this.type);
```
Comment (flx-sta) [inline src/data/moves/move-attrs/add-type-attr.ts]: Feel free to return them then if you don't feel confident about that change
```suggestion
    return (_user, target, _move) => !target.isTerastallized && !target.getTypes().includes(this.type);
```

File: src/enums/tera-ai-mode.ts [hunk 53]
```diff
@@ -0,0 +1,9 @@
+/** Determines whether an NPC trainer is allowed to Terastallize any of their pokemon */
+export enum TeraAIMode {
+  /** The trainer cannot use Terastallization */
+  NONE,
+  /** The trainer will Tersastallize the configured pokemon on the first turn it's sent out */
+  INSTANT,
+  /** (Currently unused) The trainer will choose when to Terastallize their pokemon based on the current battle state */
+  SMART,
```
Comment (flx-sta) [inline src/enums/tera-ai-mode.ts:8]: And here I thought there was some kind of hidden complex smart logic involved :D

File: src/field/pokemon.ts (hunk 36 above)
Comment (flx-sta) [reply src/field/pokemon.ts:455]: @DayKev I assume you marked this as resolved as it's simply a plain getter for the private value?

**Review by flx-sta — DISMISSED** [review]
Looks good

File: src/field/pokemon.ts (hunk 36 above)
Comment (DayKev) [reply src/field/pokemon.ts:455]: The TSDocs are on the getter, which applies it to all uses.
image

If I were to add separate TSDocs to the setter, they would be combined in the display rather than shown separately.

Comment (flx-sta) [reply src/field/pokemon.ts:455]: Forgot about that. Thanks

File: src/constants/move-constants.ts (hunk 51 above)
Comment (DayKev) [reply src/constants/move-constants.ts:3]: For now I'm going to keep matching the current convention which is `ALL_CAPS`. If we decide to switch to `PascalCase` then all the constants can be converted then.

Comment (flx-sta) [reply src/constants/move-constants.ts:3]: I've started a [poll on Discord](https://discord.com/channels/1312659961502761000/1343699671524048957/1362470863433236782) to resolve this in the long run. For now let's just ignore it

File: src/data/special-waves.ts [hunk 54]
```diff
@@ -30,6 +30,7 @@ export const EVIL_ADMIN_2_WAVE = 114;
 export const EVIL_BOSS_1_WAVE = 115;
 export const EVIL_BOSS_2_WAVE = 165;
 
+export const ELITE_FOUR_START_WAVE = 181;
```
Comment (flx-sta) [inline src/data/special-waves.ts]: Could have just used `>= ELITE_FOUR_1_WAVE` then, lol.
Didn't know these are there

**Review by flx-sta — DISMISSED** [review]

File: src/data/special-waves.ts (hunk 54 above)
Comment (DayKev) [reply src/data/special-waves.ts]: Oh you're right, for some reason I was thinking it wouldn't apply if you used Tera on wave 181 and then transitioned to 182 if I did it that way. I'll remove the unnecessary extra constant and use that one.

**Review by flx-sta — DISMISSED** [review]

File: src/data/init/init-abilities.ts [hunk 55]
```diff
@@ -202,6 +204,11 @@ import { TerrainType } from "#enums/terrain-type";
 import { WeatherType } from "#enums/weather-type";
 import i18next from "i18next";
 
+/** Used for Aerialate, Refrigerate, Pixilate, Galvanize */
+const normalTypeMoveConversionCondition: PokemonAttackCondition = (user, _target, move) =>
+  move?.type === ElementalType.NORMAL
+  && (!move.hasAttr(VariableMoveTypeAttr) || (TERA_MOVES.includes(move.id) && !user?.isTerastallized));
```
Comment (innerthunder) [inline src/data/init/init-abilities.ts]: This should be moved to `ability-utils.ts`

File: src/data/init/init-abilities.ts [hunk 56]
```diff
@@ -1622,29 +1629,25 @@ export function initAbilities() {
       .attr(PostAttackApplyStatusEffectAbAttr, false, 30, StatusEffect.TOXIC)
       .edgeCase(), // Does not inflict poison if user gets inflicted with target's Mummy
     new Ability(AbilityId.EMBODY_ASPECT_TEAL, 9)
-      .attr(PostBattleInitStatStageChangeAbAttr, [Stat.SPD], 1, true)
+      .attr(PostTeraFormChangeStatChangeAbAttr, [Stat.SPD], 1)
```
Comment (innerthunder) [inline src/data/init/init-abilities.ts:1624]: According to [smogon](https://www.smogon.com/dex/sv/abilities/embody-aspect-hearthflame/), this also needs to be a post-summon effect.

File: src/phases/terastallization-phase.ts [hunk 57]
```diff
@@ -0,0 +1,49 @@
...
+    globalScene.phaseManager.queueMessagePhase(
+      i18next.t("battle:pokemonTerastallized", {
+        pokemonNameWithAffix: getPokemonNameWithAffix(this.pokemon),
+        type: i18next.t(`pokemonInfo:Type.${ElementalType[this.pokemon.teraType]}`),
+      }),
+    );
+
+    new CommonBattleAnim(CommonAnim.TERASTALLIZE, this.pokemon).play(false, () => {
+      this.end();
+    });
```
Comment (innerthunder) [inline src/phases/terastallization-phase.ts]: nit: Since the message runs after the animation, it may be less confusing if the phase is queued within the animation callback

**Review by innerthunder — COMMENTED** [review]
code review only

**Review by flx-sta — DISMISSED** [review]

File: index.html [hunk 58]
```diff
@@ -127,7 +127,7 @@
           <div id="apadCycleNature" class="apad-button apad-square apad-small" data-key="CYCLE_NATURE">
             <span class="apad-label">N</span>
           </div>
-          <div id="apadCycleVariant" class="apad-button apad-square apad-small" data-key="V">
+          <div id="apadCycleTera" class="apad-button apad-square apad-small" data-key="CYCLE_TERA">
             <span class="apad-label">V</span>
           </div>
           <!-- buttons to display battle-specific information -->
```
Comment (PigeonBar) [inline index.html:133]: The button below also needs to be updated from `"V"` to `"CYCLE_TERA"`.

File: src/ui/handlers/command-ui-handler.ts [hunk 59]
```diff
@@ -126,23 +152,28 @@ export class CommandUiHandler extends UiHandler {
...
+          if ([BattleCommand.FIGHT, BattleCommand.BALL].includes(cursor)) {
             success = this.setCursor(cursor + 2);
           }
           break;
         case Button.LEFT:
-          if (cursor % 2 === 1) {
+          if ([BattleCommand.BALL, BattleCommand.RUN].includes(cursor)) {
             success = this.setCursor(cursor - 1);
+          } else if ([BattleCommand.FIGHT, BattleCommand.POKEMON].includes(cursor) && this.canTera()) {
+            success = this.setCursor(BattleCommand.TERA);
```
Comment (PigeonBar) [inline src/ui/handlers/command-ui-handler.ts:168]:
```suggestion
            success = this.setCursor(BattleCommand.TERA);
            this.toggleTeraButton();
```
(Should the UI also display a cursor next to the Tera button, to show more clearly that the player is selecting the Tera button?)

Comment (DayKev) [reply src/ui/handlers/command-ui-handler.ts:168]: The Tera button is supposed to have the Terastallization shader applied to it while the cursor is on it (which this should fix, thanks).

File: test/moves/tera-blast.test.ts [hunk 60]
```diff
@@ -86,34 +89,30 @@ describe("Moves - Tera Blast", () => {
...
     game.move.select(MoveId.TERA_BLAST);
     game.setTurnOrder([BattlerIndex.PLAYER, BattlerIndex.ENEMY]);
     await game.phaseInterceptor.to("MoveEndPhase");
 
-    expect(playerPokemon.getStatStage(Stat.SPATK)).toBe(-1);
-    expect(playerPokemon.getStatStage(Stat.ATK)).toBe(-1);
-  }, 20000);
+    expect(player.getStatStage(Stat.SPATK)).toBe(-1);
+    expect(player.getStatStage(Stat.ATK)).toBe(-1);
+  });
```
Comment (PigeonBar) [inline test/moves/tera-blast.test.ts:117]:
```suggestion
  });

  it("should be affected by type-changing abilities (e.g., Aerilate) if user is not Terastallized", async () => {
    game.override.enemySpecies(SpeciesId.FURRET).ability(AbilityId.AERILATE);
    await game.classicMode.startBattle();

    const player = game.field.getPlayerPokemon();
    vi.spyOn(player, "getMoveType");

    game.move.use(MoveId.TERA_BLAST);
    game.setTurnOrder([BattlerIndex.PLAYER, BattlerIndex.ENEMY]);
    await game.phaseInterceptor.to("MoveEffectPhase");

    expect(player.getMoveType).toHaveLastReturnedWith(ElementalType.FLYING);
  });

  it("should NOT be affected by type-changing abilities (e.g., Aerilate) if user is Terastallized", async () => {
    game.override.enemySpecies(SpeciesId.CHIKORITA).ability(AbilityId.AERILATE);
    await game.classicMode.startBattle();
    
    const player = game.field.getPlayerPokemon();
    game.field.forceTera(player, ElementalType.NORMAL);
    vi.spyOn(player, "getMoveType");

    game.move.use(MoveId.TERA_BLAST);
    game.setTurnOrder([BattlerIndex.PLAYER, BattlerIndex.ENEMY]);
    await game.phaseInterceptor.to("MoveEffectPhase");

    expect(player.getMoveType).toHaveLastReturnedWith(ElementalType.NORMAL);
  });
```
(Some tests for #570)

File: test/moves/tera-starstorm.test.ts [hunk 61]
```diff
@@ -29,28 +29,30 @@ describe("Moves - Tera Starstorm", () => {
...
     vi.spyOn(terapagos, "getMoveType");
+    game.field.forceTera(terapagos);
 
     game.move.select(MoveId.TERA_STARSTORM);
     await game.toEndOfTurn();
 
-    expect(terapagos.isTerastallized()).toBe(true);
+    expect(terapagos.isTerastallized).toBe(true);
     expect(terapagos.getMoveType).toHaveReturnedWith(ElementalType.STELLAR);
   });
```
Comment (PigeonBar) [inline test/moves/tera-starstorm.test.ts:48]:
```suggestion
  });

  it("should be affected by type-changing abilities (e.g., Aerilate) if user is not Terastallized", async () => {
    game.override.ability(AbilityId.AERILATE);
    game.override.battleType("single");
    await game.classicMode.startBattle([SpeciesId.TERAPAGOS]);

    const player = game.field.getPlayerPokemon();
    vi.spyOn(player, "getMoveType");

    game.move.use(MoveId.TERA_STARSTORM);
    game.setTurnOrder([BattlerIndex.PLAYER, BattlerIndex.ENEMY]);
    await game.phaseInterceptor.to("MoveEffectPhase");

    expect(player.getMoveType).toHaveLastReturnedWith(ElementalType.FLYING);
  });
```
(A test for #570.)

File: src/data/init/init-abilities.ts [hunk 62]
```diff
@@ -1622,29 +1621,29 @@ export function initAbilities() {
...
+      .attr(PostSummonStatStageChangeAbAttr, [Stat.SPD], 1)
```
Comment (PigeonBar) [inline src/data/init/init-abilities.ts]:
```suggestion
      .attr(PostSummonStatStageChangeAbAttr, [Stat.SPD], 1, true)
```
(Sets `selfTarget` to `true`)

File: src/data/init/init-abilities.ts [hunk 63]
```diff
@@ -1622,29 +1621,29 @@ export function initAbilities() {
...
       .attr(UncopiableAbilityAbAttr)
       .attr(UnswappableAbilityAbAttr)
-      .attr(NoTransformAbilityAbAttr)
-      .partial(), // Ogerpon tera interactions
+      .attr(NoTransformAbilityAbAttr),
     new Ability(AbilityId.EMBODY_ASPECT_WELLSPRING, 9)
-      .attr(PostBattleInitStatStageChangeAbAttr, [Stat.SPDEF], 1, true)
+      .attr(PostTeraFormChangeStatChangeAbAttr, [Stat.SPDEF], 1)
+      .attr(PostSummonStatStageChangeAbAttr, [Stat.SPDEF], 1)
```
Comment (PigeonBar) [inline src/data/init/init-abilities.ts]:
```suggestion
      .attr(PostSummonStatStageChangeAbAttr, [Stat.SPDEF], 1, true)
```

File: src/data/init/init-abilities.ts [hunk 64]
```diff
@@ -1622,29 +1621,29 @@ export function initAbilities() {
...
       .attr(UncopiableAbilityAbAttr)
       .attr(UnswappableAbilityAbAttr)
-      .attr(NoTransformAbilityAbAttr)
-      .partial(), // Ogerpon tera interactions
+      .attr(NoTransformAbilityAbAttr),
     new Ability(AbilityId.EMBODY_ASPECT_HEARTHFLAME, 9)
-      .attr(PostBattleInitStatStageChangeAbAttr, [Stat.ATK], 1, true)
+      .attr(PostTeraFormChangeStatChangeAbAttr, [Stat.ATK], 1)
+      .attr(PostSummonStatStageChangeAbAttr, [Stat.ATK], 1)
```
Comment (PigeonBar) [inline src/data/init/init-abilities.ts]:
```suggestion
      .attr(PostSummonStatStageChangeAbAttr, [Stat.ATK], 1, true)
```

File: src/data/init/init-abilities.ts [hunk 65]
```diff
@@ -1622,29 +1621,29 @@ export function initAbilities() {
...
       .attr(UncopiableAbilityAbAttr)
       .attr(UnswappableAbilityAbAttr)
-      .attr(NoTransformAbilityAbAttr)
-      .partial(), // Ogerpon tera interactions
+      .attr(NoTransformAbilityAbAttr),
     new Ability(AbilityId.EMBODY_ASPECT_CORNERSTONE, 9)
-      .attr(PostBattleInitStatStageChangeAbAttr, [Stat.DEF], 1, true)
+      .attr(PostTeraFormChangeStatChangeAbAttr, [Stat.DEF], 1)
+      .attr(PostSummonStatStageChangeAbAttr, [Stat.DEF], 1)
```
Comment (PigeonBar) [inline src/data/init/init-abilities.ts]:
```suggestion
      .attr(PostSummonStatStageChangeAbAttr, [Stat.DEF], 1, true)
```

File: src/data/challenge.ts [hunk 66]
```diff
@@ -675,6 +675,7 @@ export class FreshStartChallenge extends Challenge {
     pokemon.variant = 0; // Not shiny
     pokemon.formIndex = 0; // Froakie should be base form
     pokemon.ivs = [15, 15, 15, 15, 15, 15]; // Default IVs of 15 for all stats (Updated to 15 from 10 in 1.2.0)
+    pokemon.teraType = pokemon.species.type1; // Always primary tera type
```
Comment (PigeonBar) [inline src/data/challenge.ts]: Should the player also be allowed to choose the starter's secondary type as the tera type during Fresh Start, since that is also possible from a fresh save file?

File: src/field/arena.ts [hunk 67]
```diff
@@ -39,10 +39,11 @@ export class Arena {
   public biomeId: BiomeId;
   public weather: Weather | null;
   public terrain: Terrain | null;
-  public tags: ArenaTag[];
+  public tags: ArenaTag[] = [];
   public bgm: string;
   public ignoreAbilities: boolean;
   public ignoringEffectSource: BattlerIndex | null;
+  public playerTerasUsed: number = 0;
```
Comment (PigeonBar) [inline src/field/arena.ts]: Attaching this data to the Arena means that the Tera Orb gets reset upon every biome change (e.g., Teleporting Hijinks, and Endless Wave X6). Is this intended? (Other game data, such as the player's amount of money, is attached to `globalScene` instead.)

File: src/ui/handlers/command-ui-handler.ts [hunk 68]
```diff
@@ -155,6 +187,42 @@ export class CommandUiHandler extends UiHandler {
...
+   * @returns `true` if the player is allowed to Terastallize
+   */
+  public canTera(): boolean {
+    const hasTeraOrb = globalScene.getModifiers(TerastallizeAccessModifier).length > 0;
+
+    const activePokemon = globalScene.getField()[this.fieldIndex];
+
+    const isUltraNecrozma =
+      activePokemon.species.speciesId === SpeciesId.NECROZMA && activePokemon.getFormKey() === "ultra";
+    const isBlockedForm = activePokemon.isMega() || activePokemon.isMax() || isUltraNecrozma;
```
Comment (PigeonBar) [inline src/ui/handlers/command-ui-handler.ts:206]: (TODO: Should Mega and G-Max form changes also reset the Pokemon's Tera manually?)

File: src/ui/handlers/command-ui-handler.ts [hunk 69]
```diff
@@ -155,6 +187,42 @@ export class CommandUiHandler extends UiHandler {
...
+
+    const { playerTerasUsed } = globalScene.arena;
+
+    const commandPhase = this.getCommandPhase();
+    const teraCommand = globalScene.currentBattle.turnManager.findCommandFromPokemon(commandPhase.getPokemon());
```
Comment (PigeonBar) [inline src/ui/handlers/command-ui-handler.ts]:
```suggestion
    const ally = activePokemon.getAlly();
    const teraCommand = ally ? globalScene.currentBattle.turnManager.findCommandFromPokemon(ally) : undefined;
```

File: src/ui/components/battle-info.ts [hunk 70]
```diff
@@ -588,11 +588,11 @@ export class BattleInfo extends Phaser.GameObjects.Container {
         this.genderText.setPositionRelative(this.nameText, this.nameText.displayWidth, 0);
       }
 
-      const teraType = pokemon.getTeraType();
+      const teraType = pokemon.teraType;
```
Comment (PigeonBar) [inline src/ui/components/battle-info.ts]:
```suggestion
      const teraType = pokemon.isTerastallized ? pokemon.teraType : ElementalType.UNKNOWN;
```
(Fixing a bug where Terastallizing fails to update the Tera icon, since Terastallizing no longer changes the Pokemon's `getTeraType()`.)

File: src/ui/components/battle-info.ts [hunk 71]
```diff
@@ -336,12 +336,12 @@ export class BattleInfo extends Phaser.GameObjects.Container {
     this.genderText.setPositionRelative(this.nameText, nameTextWidth, 0);
     setTextColor(this.genderText, getGenderTextStyle(pokemon.gender));
 
-    this.lastTeraType = pokemon.getTeraType();
+    this.lastTeraType = pokemon.teraType;
```
Comment (PigeonBar) [inline src/ui/components/battle-info.ts]:
```suggestion
    this.lastTeraType = pokemon.isTerastallized ? pokemon.teraType : ElementalType.UNKNOWN;
```

File: src/ui/components/battle-info.ts [hunk 72]
```diff
@@ -336,12 +336,12 @@ export class BattleInfo extends Phaser.GameObjects.Container {
...
 
     this.teraIcon.setPositionRelative(this.nameText, nameTextWidth + this.genderText.displayWidth + 1, 2);
-    this.teraIcon.setVisible(this.lastTeraType !== ElementalType.UNKNOWN);
+    this.teraIcon.setVisible(pokemon.isTerastallized);
```
Comment (PigeonBar) [inline src/ui/components/battle-info.ts:342]:
```suggestion
    this.teraIcon.setVisible(pokemon.isTerastallized);
    this.teraIcon.setTintFill(Phaser.Display.Color.GetColor(...getTypeRgb(this.lastTeraType)));
```

**Review by PigeonBar — COMMENTED** [review]
image

File: src/data/challenge.ts (hunk 66 above)
Comment (DayKev) [reply src/data/challenge.ts]: Whoops, forgot that was added because of the additional restrictions in PKR. Will remove it.

File: src/ui/handlers/command-ui-handler.ts (hunk 68 above)
Comment (DayKev) [reply src/ui/handlers/command-ui-handler.ts:206]: Yeah. Not sure where to change that though.

File: src/field/arena.ts (hunk 67 above)
Comment (DayKev) [reply src/field/arena.ts]: Hm... for (the current state of) endless yes. Given we want to remove it though that can be ignored, so it might be better to move it to `BattleScene` for now.

File: src/phases/terastallization-phase.ts [hunk 73]
```diff
@@ -0,0 +1,49 @@
...
+  public pokemon: Pokemon;
+  override readonly id = PhaseId.TERASTALLIZATION;
+
+  constructor(pokemon: Pokemon) {
+    super();
+
+    this.pokemon = pokemon;
+  }
+
+  public override start(): void {
```
Comment (PigeonBar) [inline src/phases/terastallization-phase.ts:22]:
```suggestion
  public override start(): void {
    // A failsafe; this should no longer be possible once phase ordering for Terastallization is fixed.
    if (this.pokemon.isFainted()) {
      return super.end();
    }

```

File: src/battle-scene.ts [hunk 74]
```diff
@@ -227,6 +228,7 @@ export default class BattleScene extends SceneBase {
   public currentBattle: Battle;
   public pokeballCounts: PokeballCounts;
   public money: number;
+  public playerTerasUsed: number = 0;
```
Comment (PigeonBar) [inline src/battle-scene.ts:231]: This also needs to be reset to 0 in `BattleScene.reset()` now.

File: src/battle-scene.ts [hunk 75]
```diff
@@ -1372,7 +1374,18 @@ export default class BattleScene extends SceneBase {
 
         for (const pokemon of this.getPlayerParty()) {
           pokemon.resetWaveData();
+          pokemon.resetTera(); // TODO: put this in resetWaveData once Arena reset behavior is changed?
+
           applyAbAttrs<PostBattleInitAbAttr>(AbAttrFlag.POST_BATTLE_INIT, pokemon, false);
+
+          if (
+            // In Scarlet/Violet, the player's Tera Orb automatically recharges after every battle once they've caught Terapagos
+            pokemon.species.speciesId === SpeciesId.TERAPAGOS
```
Comment (PigeonBar) [inline src/battle-scene.ts]:
```suggestion
            (pokemon.species.speciesId === SpeciesId.TERAPAGOS && pokemon.isAllowedInChallenge())
```

File: src/field/pokemon.ts [hunk 76]
```diff
@@ -3061,16 +3105,28 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
...
-    if (sourceTeraType !== ElementalType.UNKNOWN && sourceTeraType === moveType) {
-      stabMultiplier.value += 0.5;
+
+    if (source.isTerastallized) {
+      if (sourceTeraType === moveType && moveType !== ElementalType.STELLAR) {
+        stabMultiplier.value += 0.5;
+      }
+
+      if (
+        source.teraType === ElementalType.STELLAR
```
Comment (PigeonBar) [inline src/field/pokemon.ts]:
```suggestion
        sourceTeraType === ElementalType.STELLAR
```

File: src/phases/move-effect-phase.ts [hunk 77]
```diff
@@ -259,6 +259,10 @@ export class MoveEffectPhase extends HitCheckPhase {
         this.triggerMoveEffects(MoveEffectTrigger.POST_TARGET, user, null);
       }
       this.updateSubstitutes();
+      const moveType = user.getMoveType(move, true);
+      if (move.isAttackMove(user, targets[0]) && !user.stellarTypesBoosted.includes(moveType)) {
```
Comment (PigeonBar) [inline src/phases/move-effect-phase.ts]:
```suggestion
      if (this.lastHit && user.isTerastallized && move.isAttackMove(user, targets[0]) && !user.stellarTypesBoosted.includes(moveType)) {
```

File: src/ui/handlers/starter-select-ui-handler.ts [hunk 78]
```diff
@@ -3199,6 +3270,7 @@ export class StarterSelectUiHandler extends MessageUiHandler {
     this.dexAttrCursor = 0n;
```
Comment (PigeonBar) [inline src/ui/handlers/starter-select-ui-handler.ts:3274]:
```suggestion
    const oldTeraType = this.teraCursor !== ElementalType.UNKNOWN ? this.teraCursor : species?.type1 ?? ElementalType.UNKNOWN;
    this.dexAttrCursor = 0n;
```
(Fixing a bug where cycling nature, ability, etc. resets the selected Tera type.)

File: src/ui/handlers/starter-select-ui-handler.ts [hunk 79]
```diff
@@ -3238,11 +3310,12 @@ export class StarterSelectUiHandler extends MessageUiHandler {
...
           : DexAttr.VARIANT_3;
       this.dexAttrCursor |= globalScene.gameData.getFormAttr(
-        formIndex !== undefined ? formIndex : (formIndex = oldProps!.formIndex),
-      ); // TODO: is this bang correct?
+        formIndex !== undefined ? formIndex : (formIndex = oldProps!.formIndex), // TODO: is this bang correct?
+      );
       this.abilityCursor = abilityIndex !== undefined ? abilityIndex : (abilityIndex = oldAbilityIndex);
       this.natureCursor = natureIndex !== undefined ? natureIndex : (natureIndex = oldNatureIndex);
-      const [isInParty, partyIndex]: [boolean, number] = this.isInParty(species); // we use this to firstly check if the pokemon is in the party, and if so, to get the party index in order to update the icon image
+      this.teraCursor = !isNullOrUndefined(teraType) ? teraType : (teraType = species.type1);
```
Comment (PigeonBar) [inline src/ui/handlers/starter-select-ui-handler.ts]:
```suggestion
      this.teraCursor = !isNullOrUndefined(teraType) ? teraType : (teraType = oldTeraType);
```

File: src/ui/handlers/starter-select-ui-handler.ts [hunk 80]
```diff
@@ -3189,7 +3260,7 @@ export class StarterSelectUiHandler extends MessageUiHandler {
   }
 
   setSpeciesDetails(species: PokemonSpecies, options: SpeciesDetails = {}): void {
```
Comment (PigeonBar) [inline src/ui/handlers/starter-select-ui-handler.ts:3264]: (TODO: This function gets called with `species = null` when the cursor is on the filter bar at the top of the screen. So, the type of `species` should be `PokemonSpecies | null`.)

File: src/ui/handlers/command-ui-handler.ts [hunk 81]
```diff
@@ -54,19 +71,24 @@ export class CommandUiHandler extends UiHandler {
...
-      commandPhase = currentPhase;
+    const commandPhase = this.getCommandPhase();
+
+    if (this.canTera()) {
+      this.teraButton.setVisible(true);
+      this.teraButton.setFrame(ElementalType[globalScene.getField()[this.fieldIndex].teraType].toLowerCase());
     } else {
-      commandPhase = globalScene.phaseManager.getStandbyPhase() as CommandPhase;
+      this.teraButton.setVisible(false);
+      if (this.cursor === BattleCommand.TERA) {
```
Comment (PigeonBar) [inline src/ui/handlers/command-ui-handler.ts]:
```suggestion
      if (this.getCursor() === BattleCommand.TERA) {
```

**Review by PigeonBar — COMMENTED** [review]
image

**Comment by DayKev** [comment]
Commits from Pigeon's review: 4ed3acf - 3291a81
New commits: 6726a8f +

**Comment by flx-sta** [comment]
@DayKev Please resolve the conflicts

**Review by flx-sta — DISMISSED** [review]

File: src/phases/terastallization-phase.ts [hunk 82]
```diff
@@ -0,0 +1,55 @@
...
+          type: i18next.t(`pokemonInfo:Type.${ElementalType[this.pokemon.teraType]}`),
+        }),
+      );
+
+      this.end();
+    });
+  }
+
+  public override end(): void {
+    this.pokemon.isTerastallized = true;
```
Comment (PigeonBar) [inline src/phases/terastallization-phase.ts:44]:
```suggestion
    this.pokemon.isTerastallized = true;

    if (this.pokemon.summonData) {
      this.pokemon.summonData.addedType = null;
      this.pokemon.summonData.types = [];
    }

```

Comment (PigeonBar) [reply src/phases/terastallization-phase.ts:44]: Also, I found the following things that modify `summonData.types` but are currently missing a check for `isTerastallized`:

- PostDefendTypeChangeAbAttr (Color Change)
- RoostedTag
- CopyBiomeTypeAttr (Camouflage)
- CopyTypeAttr (Reflect Type)
- FirstMoveTypeAttr (Conversion)
- ResistLastMoveTypeAttr (Conversion 2)
- PokemonTransformPhase

Comment (DayKev) [reply src/phases/terastallization-phase.ts:44]: `summonData.types` shouldn't be cleared when Terastallizing because STAB is supposed to take into account the Pokémon's types at the time of Terastallization, even if they're changed.
It shouldn't be modified after a Pokémon is Terastallized though.

**Review by flx-sta — APPROVED** [review]

File: src/phases/terastallization-phase.ts (hunk 82 above)
Comment (DayKev) [reply src/phases/terastallization-phase.ts:44]: Replaced most of the `summonData.types = ...` with a new helper function that has a check for Terastallization in it.

**Review by innerthunder — APPROVED** [review]

File: src/ui/handlers/command-ui-handler.ts (hunk 68 above)
Comment (flx-sta) [reply src/ui/handlers/command-ui-handler.ts:206]: Created a follow-up 
#1072
