### PR TITLE
[P2] Ignore non starter selectable forms in dex data + other fixes to game data updates when catching a Pokemon

### LINKED ISSUE #518: [Bug] Evolving a Pokemon into an Unlockable Starter (usually baby pokemon) displays the "___ has been added as a starter" Textbox at an Awkward Time
Copied over from PKR 3971

### Describe the bug

Evolved Pichu while not having unlocked Pikachu. 

When it evolved, the "has been added as a starter" textbox appears before the pokemon sprite has actually transitioned from a white silhouette to a defined sprite, and before the "Congratulations, your __ has evolved into ___" textbox.

Link to Discord where this was reported, Video is there as it is larger than 10MB
https://discord.com/channels/1125469663833370665/1125894949020381285/1280042413905150057

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

The "___ has been added as a starter" textbox should appear after the pokemon has fully finished evolving.

### Screenshots / Videos

_No response_

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

_No response_

### LINKED ISSUE #674: [Bug] Mega, GMax, Origin, and more forms are not stored in caught data
### Describe the bug

These forms are part of an ignore list during the game-data setPokemonSpeciesCaught method. This seems to be legacy code? Because the method to ignore forms from being selected on the starter screen (like Arceus, Ogerpon, Genesect) is by setting the isStarterSelectable when initializing the PokemonForm in pokemon-species.

Importance for this is that you can actually collect these forms and that trainers using these pokemon forms wont have a grey ball icon anymore.

I believe simply removing that if statement and the list would fix the bug and cause no side effects.
```
if (noStarterFormKeys.includes(pokemon.getFormKey())) {
  pokemon.formIndex = 0;
}
```
```
export const noStarterFormKeys: string[] = [
  SpeciesFormKey.MEGA,
  SpeciesFormKey.MEGA_X,
  SpeciesFormKey.MEGA_Y,
  SpeciesFormKey.PRIMAL,
  SpeciesFormKey.ORIGIN,
  SpeciesFormKey.THERIAN,
  SpeciesFormKey.GIGANTAMAX,
  SpeciesFormKey.GIGANTAMAX_RAPID,
  SpeciesFormKey.GIGANTAMAX_SINGLE,
  SpeciesFormKey.ETERNAMAX
].map(k => k.toString());
```
All the other forms not mentioned in this list work perfectly fine and are stored in the catch data.

### Reproduction

Get a Palkia. Start a run with it. Get Lustrous Globe (and activate it). You will see in the setPokemonSpeciesCaught function that it specifically sets the formIndex back to 0 instead of storing the formIndex 1 to the caught data.

### Expected behavior

I expect my now unlocked form to be stored as unlocked in the caught data. Like how Arceus, Ogerpon, Silvally and many others work too.

### Screenshots / Videos

Image

Image

### Session export file

[Palkia_Caught_Data.txt](https://github.com/user-attachments/files/18793326/Palkia_Caught_Data.txt)

### User data export file

[data_just_after_changing_palkia_form.txt](https://github.com/user-attachments/files/18793325/data_just_after_changing_palkia_form.txt)

### Additional context

https://github.com/Despair-Games/poketernity/blob/1bdf2c457cc69b9681f3742c76396100f6dc8043/src/data/no-starter-form-keys.ts#L3

Copied from Pokerogue  #5034

### PR DESCRIPTION
**Pull request by MokaStitcher**
## What are the changes the user will see?

1. Unlocking a Pokemon of form index X will no longer unlock that form index for its pre-evolution if it doesn't have one
2. Game Statistics for caught Pokemon will no longer get updated multiple times when catching an evolved Pokemon
3. Fix root species not always getting unlocked by Weird Dream and Global Trading System MEs
4. Display correct starter unlocked messages for Weird Dream and Global Trading System MEs
5. "starter unlocked" messages during evolution get shown after the evolution animation finished
6. **NEW** Non starter selectable forms are now considered seen/caught as long as the mon's base form is seen/caught
7. **NEW** fix unlocks for some specific Pokemon forms:
   - Catching a transformed Battle-bond Greninja now properly unlocks Battle-bond Froakie
   - Catching a female or male Basculegion now properly unlocks White-striped Basculin
   - Catching a Complete form Zygarde now properly unlocks the appropriate Power Construct Form
   - Catching a Dusk Form Lycanroc now properly unlocks Own Tempo Rockruff
   - Catching any Minior in core form now properly unlocks its meteor form. The core forms are no longer selectable in starter select

## Why am I making these changes?

1. Unlocking a cosplay form for Pikachu currently also unlocks that form index for Pichu, even if Pichu has no such form, causing potential issues in starter selection when it's the only form marked as unlocked
2. This issue creates very inaccurate statistics
3. Currently if you unlock Pikachu as a starter through one of these MEs, the code stops its recursion through pre-evolutions and does not unlock Pichu or update its data, which is inconsistent with how the rest of the game works.
4. GTS currently does not show any starter unlocked message. Weird Dream only shows the root species as unlocked (e.g., Pichu. Event if the unlocked starter was Pikachu)
5. Fixes #518 
6. Fixes #674. Instead of marking those forms as caught the team decided that the forms should just be ignored. This also solves many issues of inconsistencies with how some battle specific forms currently get marked as caught and shown as new even if that doesn't make sense, like Cramorant's gulping and gorging forms.

## What are the changes from a developer perspective?

Most of the fixes are in the `setPokemonCaught` and `setPokemonSpeciesCaught` function for GameData.
- When marking a Pokemon as caught and going up through the evolution chain, check if the current species has a form at the same index of the Pokemon that was caught. If not and the species already has a form unlocked, use that form, otherwise unlock the default form.
- setPokemonSpeciesCaught calls itself recursively for all pre evolutions of the caught Pokemon. Made sure the block updating game stats is only being called once.
- setPokemonSpeciesCaught  and setPokemonCaught now returns an array of the new starter Species(Id)s, if any, instead of a boolean. Other methods where updated to do the same as a result:
  - `pokemon.evolve`
  - ME utils' `addPokemonDataToDexAndValidateAchievements`
- With this, the following were updated:
  - Weird Dream ME now uses the existing `addPokemonDataToDexAndValidateAchievements` and uses the result to show a starter unlocked message for all unlocked starters
  - GTS ME: merge duplicate OptionPhases, and display message for unlocked starters
  - evolution phase: show unlocked starter message(s) after the "Pokemon has evolved" message

- **NEW** Remove the code stopping Mega/Gmax/etc forms from being marked as caught and the `noStarterFormKeys` array it was using. Remove unused array of starter selectable species in PokemonForm.ts
- Add an attribute `baseFormKey` in the PokemonForm class, that is used to figure out which starter selectable form should be unlocked when catching a non starter selectable form.
- Created `Pokemon.getSelectableFormIndex()` to return the index of the form that should be unlocked in the dex for a Pokemon. Call it in `Pokemon.getDexData()` and `gameData.setSpeciesCaught` to ensure that non starter selectable forms are not marked as seen/caught and not shown as new through the tinted pokeball and new catch panels.

- Updated `init-species` to add this `baseFormKey` attribute for Pokemon with specific form unlock patterns, like Battle Bond Greninja, Basculegion, Minior, and Zygarde. 
To make Basculegion's unlock work, Basculin's white striped form has been moved to first place in Basculin's form list and Basculegion's female form has been marked as non starter selectable, so it will default to the male form when unlocking it. This is so when catching female Basculegion (form index 1), the index unlocked in the dex data will actually be 0, resulting in properly unlocking Basculin's white stripped form rather than blue stripped as before.

Created tests for dex data and the `setPokemonCaught` function

## Screenshots/Videos

<details><summary>Invalid form unlock</summary>

Before, after catching a single cosplay Pikachu, Spiky eared pichu is shown + errors in the console:
image

After, after catching a single cosplay Pikachu: normal Pichu is unlocked + no errors:
image
</details> 

<details><summary>Game Statistics</summary>

Before, on a fresh file after having caught a single shiny Pikachu:
image
image image

After, on a fresh file after having caught a single Pikachu:
image
image image
</details> 

<details><summary>MEs</summary>

Before, fresh file getting a Raichu from Weird Dream: message for Pichu unlocked (no pikachu message). But only pikachu got unlocked
_weird_dream_before_get_raichu
_weird_dream_gts_before_get_raichu_no_pichu_unlock

After, both pichu and pikachu are unlocked:
_weird_dream_gts_after_get_raichu_pichu_unlock

</details> 

<details><summary>Non starter selectable forms</summary>

Before, after having caught a yellow minior in core form, the yellow minior in meteor forms shows as not owned / with a new form
image
Before, core form is selectable in starter select:
image

After: First catching a blue minior in core form on a fresh file. When encountering a blue minior again it does not have a tinted ball or show the form as new
image

</details> 

<details><summary>Rockruff/Lycanroc</summary>

Before, fresh file after having caught only Midnight Lycanroc, mistakenly unlocked own tempo Rockruff:
image

Before, fresh file after having caught only Dusk Lycanroc. no own tempo & same error as pichu:
image

After, fresh file after having caught only Midnight Lycanroc:
image

After, fresh file after having caught only Dusk Lycanroc:
image

<sub> seems like starter select does not show the correct abilities for alternate forms, but that's not for this PR to fix 💀 

</details> 

## How to test the changes?

`npm run test:silent dex_data set_pokemon_caught`

<details><summary>Invalid form unlock + stats</summary>

```
  ENEMY_SPECIES_OVERRIDE: Species.PIKACHU,
  ENEMY_FORM_OVERRIDES: {
    [Species.PIKACHU]: 5 // some cosplay form
  },
```
- Open the game in a private window to have a fresh file
- Start a run and catch a pikachu
- Go to the next wave then back to the title screen
- Check Pichu and the console in starter select
- Check the Stats menu

</details> 

<details><summary>Evolution message</summary>

Fresh file, catch iggly and give it rare candies until it evolves
```
  STARTING_LEVEL_OVERRIDE: 50,
  STARTING_WAVE_OVERRIDE: 21,
  ENEMY_SPECIES_OVERRIDE: Species.IGGLYBUFF,
  ITEM_REWARD_OVERRIDE: [ {name: "RARE_CANDY"}, {name: "EVOLUTION_ITEM"}],
```
</details> 

<details><summary>ME</summary>

To test the specific case of Pokemon with baby forms you'd need to update the code of those MEs to give Species.PIKACHU instead of a random species then use overrides, always on a fresh file.
```
  MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.GLOBAL_TRADE_SYSTEM,
  //MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.WEIRD_DREAM,
  MYSTERY_ENCOUNTER_RATE_OVERRIDE: 255,
  STARTING_LEVEL_OVERRIDE: 50,
  STARTING_WAVE_OVERRIDE: 21,
  STARTING_BIOME_OVERRIDE: Biome.PLAINS,
```

</details> 

<details><summary>Non starter selectable forms</summary>

- from a fresh file
- start a run and catch a Pokemon in a form that is not selectable through starter select (ie, ash greninja, core form minior, complete form zygarde, ...)
- Exit to starter select and confirm that the correct form was unlocked
- reload the run and in the next waves, catch the mon again and make sure the tinted pokeball and catch panel are highlighting things correctly

```
  ENEMY_SPECIES_OVERRIDE: Species.MINIOR, // Species.BASCULEGION // Species.GRENINJA // Species.ZYGARDE // Species.CRAMORANT
  BATTLE_TYPE_OVERRIDE: "single",
  MOVESET_OVERRIDE: MoveId.FALSE_SWIPE,
  STARTING_LEVEL_OVERRIDE: 100,
  POKEBALL_OVERRIDE: {
    active: true,
    pokeballs: {
      [PokeballType.POKEBALL]: 5,
      [PokeballType.GREAT_BALL]: 0,
      [PokeballType.ULTRA_BALL]: 0,
      [PokeballType.MASTER_BALL]: 99,
    },
  },
```
</details> 

## Checklist

- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes manually?

- [X] Are all unit tests still passing? (`npm run test:silent`)
  - [X] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [X] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

File: src/data/no-starter-form-keys.ts [hunk 1]
```diff
@@ -1,14 +0,0 @@
-import { SpeciesFormKey } from "#enums/species-form-key";
-
-export const noStarterFormKeys: string[] = [
```
Comment (Tempo-anon) [inline src/data/no-starter-form-keys.ts:3]: I assume this was a sam relic or something to prevent players from choosing these specific forms in the starter-select, but that also doesn't mean much when there are a ton of SpeciesFormKeys that aren't able to be chosen as starters

File: src/system/game-data.ts [hunk 2]
```diff
@@ -1516,12 +1515,17 @@ export class GameData {
...
+   * The function exits early if the Pokemon is a "rental" Pokemon (ie was given through an event for the current run only)
+   * unless that Pokemon had already been captured before, in which case any new form, gender, etc. gets unlocked.
    *
-   * @param pokemon
-   * @param incrementCount
-   * @param fromEgg
-   * @param showMessage
-   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
+   * @param pokemon the {@linkcode Pokemon} that was caught
+   * @param incrementCount whether to increment game stats and starter candy or not. Default: `true`. Use `false` for "rental" Pokemon.
```
Comment (Tempo-anon) [inline src/system/game-data.ts]: nit: would `incrementCount` make more sense as something like `updateData`?

File: src/system/game-data.ts [hunk 3]
```diff
@@ -1584,39 +1597,28 @@ export class GameData {
...
+        // Once at the root species, give starter candy
         if (!hasPrevolution && (!globalScene.gameMode.isDaily || hasNewAttr || fromEgg)) {
-          this.addStarterCandy(
-            species,
-            1 * (pokemon.isShiny() ? 5 * (1 << (pokemon.variant ?? 0)) : 1) * (fromEgg || pokemon.isBoss() ? 2 : 1),
-          );
+          let candyMultiplier = 1;
+          if (pokemon.isShiny()) {
+            // Common shiny gives x5 candies, rare shiny: x10, epic shiny: x20.
+            candyMultiplier *= 5 * (1 << (pokemon.variant ?? 0));
```
Comment (Tempo-anon) [inline src/system/game-data.ts]: Should we throw a todo here? There's magic numbers and uses less readable math equation, not to mention whether or not these rates will ever want to be adjusted

File: src/system/game-data.ts [hunk 4]
```diff
@@ -1637,23 +1639,51 @@ export class GameData {
...
     });
   }
 
+  private incrementCaughtPokemonStats(pokemon: Pokemon) {
+    this.gameStats.pokemonCaught++;
+    if (pokemon.species.isSubLegendary()) {
+      this.gameStats.subLegendaryPokemonCaught++;
+    } else if (pokemon.species.isLegendary()) {
+      this.gameStats.legendaryPokemonCaught++;
+    } else if (pokemon.species.isMythical()) {
```
Comment (Tempo-anon) [inline src/system/game-data.ts:1700]: nit: I don't think these need to be `else`'s since a Pokemon should only ever be one category

File: src/data/no-starter-form-keys.ts (hunk 1 above)
Comment (MokaStitcher) [reply src/data/no-starter-form-keys.ts:3]: yeah it's definitely both completely outdated and not necessary

File: src/system/game-data.ts (hunk 4 above)
Comment (MokaStitcher) [reply src/system/game-data.ts:1700]: true, but with the else I guess it doesn't run through the other cases if one is true, so it's technically sliiigghhtly more efficient

Comment (Tempo-anon) [reply src/system/game-data.ts:1700]: Oh you're right, performance improvement 📈

File: src/system/game-data.ts (hunk 2 above)
Comment (MokaStitcher) [reply src/system/game-data.ts]: Ended up changing things up more than that because `incrementCount`covered too much ground. Hopefully it makes more sense now (ME relic this one I think...)

File: src/data/balance/starters.ts [hunk 5]
```diff
@@ -1,12 +1,32 @@
...
+ * Common shinies gives a x5 multiplier and every tier above that doubles that (common: x5, rare: x10, epic: x20).
+ * @param variant the {@linkcode VariantTier} to consider.
+ * @returns the amount to multiply candy gain by.
+ */
+export function getCandyGainMultiplierForShinies(variant: VariantTier) {
+  // Make sure the given variant is valid, otherwise default to base variant
+  if (!VariantTier[variant]) {
+    variant = 0;
+  }
+  return STARTER_CANDY_BASE_MULIPLIER_FOR_SHINY * (1 << variant);
```
Comment (Tempo-anon) [inline src/data/balance/starters.ts]: I appreciate the comment explaining this in detail but I still am not sure if we should be making a habit of using bitshifts as part of equations. I know it's a lot more lines of code but something like this seems like it'd be easier to read at a glance
```ts
switch(variant) {
  case 0:
   return 5; // or muiltiplier = 1; break;
  case 1: 
    return 10;
  case 2:
    return 20;
}
```

File: src/data/balance/starters.ts [hunk 6]
```diff
@@ -1,12 +1,32 @@
...
+export const STARTER_CANDY_MULIPLIER_FOR_EGG = 2;
+export const STARTER_CANDY_BASE_MULIPLIER_FOR_SHINY = 5;
+
+/**
+ * Get the starter candy multiplier for catching (or hatching) a shiny Pokemon based on its variant.
+ * Common shinies gives a x5 multiplier and every tier above that doubles that (common: x5, rare: x10, epic: x20).
+ * @param variant the {@linkcode VariantTier} to consider.
+ * @returns the amount to multiply candy gain by.
+ */
+export function getCandyGainMultiplierForShinies(variant: VariantTier) {
```
Comment (Tempo-anon) [inline src/data/balance/starters.ts]: nit: the name should have a return type hinting for `number`

File: test/system/dex_data.test.ts [hunk 7]
```diff
@@ -0,0 +1,275 @@
...
+    expect(gameData.gameStats.shinyPokemonCaught).toBe(1);
+    expect(bulbaDexData.caughtCount).toBe(0);
+    expect(ivyDexData.caughtCount).toBe(0);
+    expect(venuDexData.caughtCount).toBe(1);
+
+    expect(starterData.candyCount).toBe(10); // catching a rare tier shiny gives 10 candy
+    expect(starterData.abilityAttr & AbilityAttr.ABILITY_HIDDEN).toBeTruthy();
+    expect(bulbaDexData.caughtAttr & DexAttr.NON_SHINY).toBeTruthy();
+    expect(bulbaDexData.caughtAttr & DexAttr.SHINY).toBeTruthy();
+    expect(bulbaDexData.caughtAttr & DexAttr.DEFAULT_VARIANT).toBeTruthy();
```
Comment (Tempo-anon) [inline test/system/dex_data.test.ts]: So catching any tiered shiny will still unlock the default shiny right?

**Review by Tempo-anon — DISMISSED** [review]
Code looks fine to me

File: test/system/dex_data.test.ts (hunk 7 above)
Comment (MokaStitcher) [reply test/system/dex_data.test.ts]: right now yes, but it's not going to stay that way. I'll be making a separate PR to rework how unlocked variants are handled in dex data, and will fix that issue then. But for now I have to follow how dex data is built

File: src/data/balance/starters.ts (hunk 6 above)
Comment (MokaStitcher) [reply src/data/balance/starters.ts]: my bad!

File: src/data/balance/starters.ts (hunk 5 above)
Comment (MokaStitcher) [reply src/data/balance/starters.ts]: honestly, fair. will do.
Going the multiplier + break route allows me to get rid of the variant validity check, so perfect
(people who messed with their egg data often put variant as 3 because they didn't know it should be 0-indexed, so they would end up with 80 candies 💀  (40 x 2 for egg))

**Comment by MokaStitcher** [comment]
Putting to draft for a short time because I think I want to take the opportunity to also fix the "starter unlocked" messages issues for MEs as well as #518

edit: done. I'll update the PR description tomorrow
tldr of the new changes: setPokemonCaught now returns an array of the new starter Species(Id)s, instead of a boolean. This allows other places in the code to properly display unlocked starter messages if applicable. This fixes:
- Weird Dream ME not always showing the correct species as unlocked (ie if you get a Pikachu, it would always say Pichu got unlocked, even if Pichu was already unlocked before and the new starter was actually Pikachu)
- GTS ME not showing unlocked starter text at all
- Starter Unlock text showing at an awkward time during evolution (#518)

File: src/data/balance/starters.ts [hunk 8]
```diff
@@ -1,12 +1,39 @@
...
+export const STARTER_CANDY_MULIPLIER_FOR_BOSS = 2;
+export const STARTER_CANDY_MULIPLIER_FOR_EGG = 2;
+
+/**
+ * Get the starter candy multiplier for catching (or hatching) a shiny Pokemon based on its variant.
+ * Common shinies gives a x5 multiplier and every tier above that doubles that (common: x5, rare: x10, epic: x20).
+ * @param variant the {@linkcode VariantTier} to consider.
+ * @returns the amount to multiply candy gain by.
+ */
+export function getCandyGainMultiplierForShinies(variant: VariantTier): number {
```
Comment (Tempo-anon) [inline src/data/balance/starters.ts]: nit: I'd rename `variant` to `variantTier` just so the type of it can be seen immediately based on its name

File: src/data/mystery-encounters/encounters/weird-dream-encounter.ts [hunk 9]
```diff
@@ -477,37 +468,19 @@ async function postProcessTransformedPokemon(
...
-    globalScene.gameData.updateSpeciesDexIvs(newPokemon.species.getRootSpeciesId(true), newPokemon.ivs);
-    const newStarterUnlocked = await globalScene.gameData.setPokemonCaught(newPokemon, true, false, false);
-    if (newStarterUnlocked) {
-      isNewStarter = true;
-      await showEncounterText(
-        i18next.t("battle:addedAsAStarter", { pokemonName: getPokemonSpecies(speciesRootForm).getName() }),
-      );
+  if (!forBattle) {
+    // For pokemon at/below 570 BST or any shiny pokemon, unlock it permanently as if you had caught it
+    // For other mons, update their dex data as long as they had been unlocked previously
```
Comment (Tempo-anon) [inline src/data/mystery-encounters/encounters/weird-dream-encounter.ts:473]: nit and unrelated to the PR but this bit always annoyed me because it's not really documented anywhere in game and always led to people asking questions and confusion about how unlocking worked. Even now I'm learning something as I didn't realize there was also a check for shininess

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts [hunk 10]
```diff
@@ -951,32 +951,44 @@ export function getEncounterPokemonLevelForWave(levelAdditiveModifier: number =
...
  */
-export async function addPokemonDataToDexAndValidateAchievements(pokemon: PlayerPokemon) {
-  const speciesForm = !pokemon.fusionSpecies ? pokemon.getSpeciesForm() : pokemon.getFusionSpeciesForm();
+export async function addPokemonDataToDexAndValidateAchievements(
+  pokemon: PlayerPokemon,
+  includeNewCatch: boolean = true,
+): Promise<Species[]> {
+  const isNewCatch = !globalScene.gameData.dexData[pokemon.species.getRootSpeciesId()].caughtAttr;
+  if (!isNewCatch || includeNewCatch) {
+    const speciesForm = !pokemon.fusionSpecies ? pokemon.getSpeciesForm() : pokemon.getFusionSpeciesForm();
```
Comment (Tempo-anon) [inline src/data/mystery-encounters/utils/encounter-pokemon-utils.ts]: if fusions are planned to be removed, could also just remove all instances of it here for simplicity?

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts [hunk 11]
```diff
@@ -951,32 +951,44 @@ export function getEncounterPokemonLevelForWave(levelAdditiveModifier: number =
...
+    if (pokemon.species.isSubLegendary()) {
+      globalScene.validateAchv(achvs.CATCH_SUB_LEGENDARY);
+    }
 
-  if (pokemon.species.isSubLegendary()) {
-    globalScene.validateAchv(achvs.CATCH_SUB_LEGENDARY);
-  }
+    if (pokemon.species.isLegendary()) {
+      globalScene.validateAchv(achvs.CATCH_LEGENDARY);
+    }
```
Comment (Tempo-anon) [inline src/data/mystery-encounters/utils/encounter-pokemon-utils.ts:977]: nit: is the chunk of code for validating if a Pokemon is a sublegend/legend/mythic and giving an achv called multiple times throughout the codebase? maybe might be worth putting in a utils function

File: src/system/game-data.ts [hunk 12]
```diff
@@ -1516,54 +1521,81 @@ export class GameData {
...
+   * The function exits early if the Pokemon is a "rental" Pokemon (ie was given through an event for the current run only)
+   * unless that species had already been captured before, in which case any new form, gender, etc. gets unlocked.
    *
-   * @param pokemon
-   * @param incrementCount
-   * @param fromEgg
-   * @param showMessage
-   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
+   * @param pokemon the {@linkcode Pokemon} that was caught.
+   * @param isNonRentalCatch `true` if we are in a catching or hatching situation, and if the Pokemon is not being "rented"
```
Comment (Tempo-anon) [inline src/system/game-data.ts]: nit: not sure about the name. Is there a list of all cases of rental pokemon? Only ones off the top of my head are the weird dream transformation stuff

**Review by Tempo-anon — COMMENTED** [review]
Code looks all right to me. Just some minor nitpicks

File: src/data/mystery-encounters/encounters/weird-dream-encounter.ts (hunk 9 above)
Comment (MokaStitcher) [reply src/data/mystery-encounters/encounters/weird-dream-encounter.ts:473]: Yeah. I understand why the restriction is here but it's hard to convey in game.
I wonder if having an icon to show that a Pokemon is "rental" with a tooltip explaining it could help

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts (hunk 10 above)
Comment (MokaStitcher) [reply src/data/mystery-encounters/utils/encounter-pokemon-utils.ts]: I'd rather not have PRs bleed into each other. I'm fine with fixing conflicts when fusion removal gets merged

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts (hunk 11 above)
Comment (MokaStitcher) [reply src/data/mystery-encounters/utils/encounter-pokemon-utils.ts:977]: we are in a helper function (even if ME-only helper function). Definitely many more things would gain to be refactored around but this PR is already way beyond its original scope

File: src/system/game-data.ts (hunk 12 above)
Comment (MokaStitcher) [reply src/system/game-data.ts]: it's the best name I could find that actually fits what it does

The comment tries to explain but this variable would be `true` if:
- we are in a catch or hatch situation AND the mon is not "rental"

Which means it should be `false` if:
- we are in a catch or hatch situation and the mon is "rental"
- OR we are not in a catch situation e.g. evolution, form change, and other stuff i'm probably forgetting

So it's not purely about rental. Rental is only a very small portion of the cases where this would be false

If someone can find a name that expresses all that i'll be happy to change it

File: src/data/mystery-encounters/encounters/global-trade-system-encounter.ts [hunk 13]
```diff
@@ -552,6 +453,66 @@ function generateTradeOption(alreadyUsedSpecies: PokemonSpecies[], originalBst?:
   return newSpecies!;
 }
 
+async function doTradeOptionPhaseCallback(): Promise<void> {
```
Comment (torranx) [inline src/data/mystery-encounters/encounters/global-trade-system-encounter.ts:462]: this could do a documentation

File: src/system/game-data.ts [hunk 14]
```diff
@@ -1582,77 +1614,95 @@ export class GameData {
...
+        if (fromEgg) {
+          candyMultiplier *= STARTER_CANDY_MULIPLIER_FOR_EGG;
+        } else if (pokemon.isBoss()) {
+          candyMultiplier *= STARTER_CANDY_MULIPLIER_FOR_BOSS;
+        }
+        this.addStarterCandy(species, STARTER_CANDY_GAIN_FROM_CATCH * candyMultiplier);
       }
 
-      const checkPrevolution = (newStarter: boolean) => {
+      const checkPrevolution = (unlockedStarters: Species[]) => {
```
Comment (torranx) [inline src/system/game-data.ts]: I know it was like this before but is it really prevolution and not preevolution?

Comment (MokaStitcher) [reply src/system/game-data.ts]: renamed things defined in game-data.ts but for now I left the global `pokemonPrevolutions` array as is because I don't want to be touching even more files in this PRs

File: src/data/mystery-encounters/encounters/global-trade-system-encounter.ts [hunk 15]
```diff
@@ -552,6 +453,70 @@ function generateTradeOption(alreadyUsedSpecies: PokemonSpecies[], originalBst?:
...
+  const traderName = generateRandomTraderName();
+  encounter.setDialogueToken("tradeTrainerName", traderName.trim());
+
+  // Remove the original party member from party
+  globalScene.removePokemonFromPlayerParty(tradedPokemon, false);
+
+  // Set data properly, then generate the new Pokemon's assets
+  receivedPokemonData.passive = tradedPokemon.passive;
+  // Pokeball to Ultra ball, randomly
+  receivedPokemonData.pokeball = randInt(4) as PokeballType;
```
Comment (PigeonBar) [inline src/data/mystery-encounters/encounters/global-trade-system-encounter.ts]:
```suggestion
  receivedPokemonData.pokeball = randInt(3) as PokeballType;
```

File: src/phases/evolution-phase.ts [hunk 16]
```diff
@@ -220,7 +222,22 @@ export class EvolutionPhase extends FormChangeBasePhase {
...
+        }
+        ui.showText(
+          i18next.t("battle:addedAsAStarter", { pokemonName: getPokemonSpecies(unlockedStarters.shift()).getName() }),
+          null,
+          () => showStarterUnlockText(unlockedStarters).then(() => resolve()),
+          null,
+          true,
+        );
+      });
+    };
```
Comment (PigeonBar) [inline src/phases/evolution-phase.ts]:
```suggestion
    async function showStarterUnlockText(unlockedStarters: Species[]): Promise<void> {
      for (const speciesId of unlockedStarters) {
        globalScene.playSound("level_up_fanfare");
        await new Promise<void>(resolve => {
          ui.showText(
            i18next.t("battle:addedAsAStarter", { pokemonName: getPokemonSpecies(speciesId).getName() }),
            null,
            () => resolve(),
            null,
            true,
          );
        });
      }
    };
```
Less recursion needed

File: src/system/game-data.ts [hunk 17]
```diff
@@ -1515,54 +1520,81 @@ export class GameData {
   }
 
   /**
+   * Set the given Pokemon (and its pre-evolutions, if any) as caught and update the dex data based on its characteristics
+   * (nature, ability, shinyness, variant, ...) updates games stats and gives starter candy.
+   * Note: it does not update the Pokemon IVs (TODO: why??). See {@linkcode updateSpeciesDexIvs} for that.
+   * By default, shows a message for each starter unlocked in the process.
+   * The function exits early if the Pokemon is a "rental" Pokemon (ie was given through an event for the current run only)
+   * unless that species had already been captured before, in which case any new form, gender, etc. gets unlocked.
```
Comment (PigeonBar) [inline src/system/game-data.ts]:
```suggestion
   * Set the given Pokemon (and its pre-evolutions, if any) as caught, update the dex data based on its characteristics
   * (nature, ability, shinyness, variant, ...), update game stats, and give starter candy.
   * 
   * Note: it does not update the Pokemon IVs (TODO: why??). See {@linkcode updateSpeciesDexIvs} for that.
   * 
   * By default, shows a message for each starter unlocked in the process.
   * 
   * The function exits early if the Pokemon is a "rental" Pokemon (i.e. was given through an event for the current run only)
   * unless that species had already been captured before, in which case any new form, gender, etc. gets unlocked.
```

File: test/system/dex_data.test.ts
Comment (PigeonBar) [inline test/system/dex_data.test.ts:1]: This test should probably be sorted in `vitest.config.ts` to run earlier, in case the other tests do stuff that modifies dex data.

File: test/system/dex_data.test.ts [hunk 18]
```diff
@@ -0,0 +1,341 @@
...
+
+    for (const speciesId of defaultStarterSpecies) {
+      const dexData = gameData.dexData[speciesId];
+      const starterData = gameData.starterData[speciesId];
+      expect(dexData).toBeDefined();
+      expect(starterData).toBeDefined();
+
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_1).toBeTruthy();
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_2).toBeFalsy();
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_HIDDEN).toBeFalsy();
```
Comment (PigeonBar) [inline test/system/dex_data.test.ts:46]:
```suggestion
      expect(starterData.eggMoves).toBe(0);
      expect(starterData.candyCount).toBe(0);
      expect(starterData.friendship).toBe(0);
      expect(starterData.abilityAttr & AbilityAttr.ABILITY_1).toBeTruthy();
      expect(starterData.abilityAttr & AbilityAttr.ABILITY_2).toBeFalsy();
      expect(starterData.abilityAttr & AbilityAttr.ABILITY_HIDDEN).toBeFalsy();
      expect(starterData.passiveAttr).toBe(0);
      expect(starterData.valueReduction).toBe(0);
      expect(starterData.classicWinCount).toBe(0);
```

File: src/system/game-data.ts [hunk 19]
```diff
@@ -1515,54 +1520,81 @@ export class GameData {
...
       const dexEntry = this.dexData[species.speciesId];
       const caughtAttr = dexEntry.caughtAttr;
+
+      /*
+       * Ensure that the form index is valid for this species. An invalid index can happen when an evolved Species
+       * and its pre evolution Species doen't have the same number of forms. For example when catching any Pikachu
+       * other than normal and partner it should not unlock the caught form for Pichu since it doesn't have them.
+       */
       const formIndex = pokemon.formIndex;
-      if (noStarterFormKeys.includes(pokemon.getFormKey())) {
```
Comment (PigeonBar) [inline src/system/game-data.ts:1565]: It turns out that the starter select UI checks are not enough, since they cannot make the player choose a starter-selectable form if the player has not caught a starter-selectable form yet.

<details><summary>Screenshot</summary>
<p>

image



</p>
</details>

Comment (MokaStitcher) [reply src/system/game-data.ts:1565]: Right, I worked under the assumption that it wasn't possible to catch one of these forms without having the base form, but forgot about Eternatus...
But Etern is not supposed to stay special in this way so, not sure how we want to handle that right now 🤔

File: test/system/dex_data.test.ts
Comment (MokaStitcher) [reply test/system/dex_data.test.ts:1]: I think it's safe with how things are done currently, because the GameManager's constructor calls [globalScene.reset(false,true)](https://github.com/Despair-Games/poketernity/blob/5849f8873c6287c48dc94c2e784e6a06e7456f4f/test/testUtils/gameManager.ts#L110-L111) which resets the GameData object

https://github.com/Despair-Games/poketernity/blob/5849f8873c6287c48dc94c2e784e6a06e7456f4f/src/battle-scene.ts#L1132-L1135

(These tests are doing things that would break each other if there was bleeding I think, and a few other tests are already doing things like importing the everything save file and things seems to be fine too)

File: src/phases/evolution-phase.ts (hunk 16 above)
Comment (MokaStitcher) [reply src/phases/evolution-phase.ts]: this is much better, thank you

File: src/system/game-data.ts (hunk 19 above)
Comment (MokaStitcher) [reply src/system/game-data.ts:1565]: So, I see a few options:
- Assume we will never allow to catch any of these forms without owning the base form first. This is currently the case already, except for Eternatus, but we're not keeping it that way, so we may just leave things like this.
- Leave things open, and thus either:
   - Change `gamedata.getSpeciesDefaultDexAttr` to make it exclude non starter selectable forms. If no starter selectable form is found it would default to the base form, so Etern would show as its normal form in starter select even if the caught attr only has the max form. With this, we solve the starter select issue but catching the evolved form does not unlock the base form properly, which may cause problems if later down the line we want to allow catching those forms for other Pokemon
   - Move the starterSelectable check to `setSpeciesCaught` instead. If the new form is not starter selectable, check that there is already another starter selectable unlocked form. If yes, no issue, unlock the new form. If not, either:
       - Unlock the base form instead, so in Etern's case the first time you catch it it would unlock the base form, and you'd need to catch it another time to mark the emax form as caught
       - Or, unlock both the default form and new form. I am not entirely sure how much of a can of worms that would be, and if it's something we want to be doing, but I think it solves the drawbacks of the various other options above

Comment (PigeonBar) [reply src/system/game-data.ts:1565]: I think unlocking both the default form and the unselectable form together would be the best option, since this PR makes it intended for mega, gmax, etc. forms to be stored in caught data anyway.

Comment (MokaStitcher) [reply src/system/game-data.ts:1565]: Following the vote I have made it so all non starter selectable forms get ignored, and instead fall back to unlocking a starter selectable form instead. PR description has been updated (except screenshots and how to test instructions, for now)

File: src/field/pokemon.ts [hunk 20]
```diff
@@ -4208,9 +4235,13 @@ export class PlayerPokemon extends Pokemon {
     });
   }
 
-  public evolve(evolution: SpeciesFormEvolution | null): Promise<void> {
+  /**
+   * @param evolution the {@linkcode SpeciesFormEvolution} to use
```
Comment (DayKev) [inline src/field/pokemon.ts]:
```suggestion
   * @param evolution - The {@linkcode SpeciesFormEvolution} to use
```

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts [hunk 21]
```diff
@@ -948,29 +948,40 @@ export function getEncounterPokemonLevelForWave(levelAdditiveModifier: number =
 
 /**
  * Helper async function to update a player's dex and award achievements
+ * The function exits early if the Pokemon is a "rental" Pokemon (ie was given through an event for the current run only)
+ * unless that species had already been captured before, in which case any new form, gender, etc. gets unlocked.
+ *
  * @param pokemon - The newly obtained Pokemon
+ * @param includeNewCatch whether to update the data if the catch would unlock a new starter. Default: `true`.
```
Comment (DayKev) [inline src/data/mystery-encounters/utils/encounter-pokemon-utils.ts]:
```suggestion
 * @param includeNewCatch - Whether to update the data if the catch would unlock a new starter. Default: `true`.
```

File: src/data/mystery-encounters/utils/encounter-pokemon-utils.ts [hunk 22]
```diff
@@ -948,29 +948,40 @@ export function getEncounterPokemonLevelForWave(levelAdditiveModifier: number =
 
 /**
  * Helper async function to update a player's dex and award achievements
```
Comment (DayKev) [inline src/data/mystery-encounters/utils/encounter-pokemon-utils.ts]:
```suggestion
 * Helper async function to update a player's dex and award achievements.
 *
```

File: src/data/balance/starters.ts [hunk 23]
```diff
@@ -1,12 +1,39 @@
...
+export const CLASSIC_CANDY_FRIENDSHIP_MULTIPLIER = 3;
+
+export const STARTER_CANDY_GAIN_FROM_CATCH = 1;
+export const STARTER_CANDY_MULIPLIER_FOR_BOSS = 2;
+export const STARTER_CANDY_MULIPLIER_FOR_EGG = 2;
+
+/**
+ * Get the starter candy multiplier for catching (or hatching) a shiny Pokemon based on its variant.
+ * Common shinies gives a x5 multiplier and every tier above that doubles that (common: x5, rare: x10, epic: x20).
+ * @param variant the {@linkcode VariantTier} to consider.
```
Comment (DayKev) [inline src/data/balance/starters.ts]:
```suggestion
 * @param variant - The {@linkcode VariantTier} to consider.
```

File: src/system/game-data.ts [hunk 24]
```diff
@@ -1519,54 +1524,89 @@ export class GameData {
...
-   * @param pokemon
-   * @param incrementCount
-   * @param fromEgg
-   * @param showMessage
-   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
+   * The function exits early if the Pokemon is a "rental" Pokemon (i.e. was given through an event for the current run only)
+   * unless that species had already been captured before, in which case any new form, gender, etc. gets unlocked.
+   *
+   * @param pokemon the {@linkcode Pokemon} that was caught.
+   * @param isNonRentalCatch `true` if we are in a catching or hatching situation, and if the Pokemon is not being "rented"
```
Comment (DayKev) [inline src/system/game-data.ts]:
```suggestion
   * @param pokemon - The {@linkcode Pokemon} that was caught.
   * @param isNonRentalCatch - `true` if we are in a catching or hatching situation, and if the Pokemon is not being "rented"
```

File: src/system/game-data.ts [hunk 25]
```diff
@@ -1519,54 +1524,89 @@ export class GameData {
...
+   *   as part of an event. If `false` and the Pokemon wasn't already caught (e.g. rental mon), no data will get updated,
+   *   otherwise (e.g. evolution situation) the nature, ability and other unlocks will get updated, but no the game stats.
+   * @param fromEgg whether the Pokemon was obtained through an egg. Default: `false`
+   * @param showMessage whether to display a message if (a) new Starter(s) was unlocked. Default: `true`
```
Comment (DayKev) [inline src/system/game-data.ts]:
```suggestion
   * @param fromEgg - Whether the Pokemon was obtained through an egg. Default: `false`
   * @param showMessage - Whether to display a message if (a) new Starter(s) was unlocked. Default: `true`
```

File: src/system/game-data.ts [hunk 26]
```diff
@@ -1519,54 +1524,89 @@ export class GameData {
...
-   * @param incrementCount
-   * @param fromEgg
-   * @param showMessage
-   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
+   * @param pokemon the {@linkcode Pokemon} that was caught
+   * @param species the {@linkcode PokemonSpecies} to mark as caught based on the pokemon's characteristics
+   * @param updateStats whether to increment game stats and the species's caught/hatched count. Default: `true`
+   * @param giveCandy whether to give starter candy for the root species. Default: `true`
+   * @param fromEgg whether the Pokemon was obtained through an egg. Default: `false`
+   * @param showMessage whether to display a message if (a) new Starter(s) was unlocked. Default: `true`
```
Comment (DayKev) [inline src/system/game-data.ts]:
```suggestion
   * @param pokemon - The {@linkcode Pokemon} that was caught
   * @param species - The {@linkcode PokemonSpecies} to mark as caught based on the pokemon's characteristics
   * @param updateStats - Whether to increment game stats and the species's caught/hatched count. Default: `true`
   * @param giveCandy - Whether to give starter candy for the root species. Default: `true`
   * @param fromEgg - Whether the Pokemon was obtained through an egg. Default: `false`
   * @param showMessage - Whether to display a message if (a) new Starter(s) was unlocked. Default: `true`
```

File: test/system/dex_data.test.ts [hunk 27]
```diff
@@ -0,0 +1,74 @@
...
+      expect(starterData.friendship).toBe(0);
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_1).toBeTruthy();
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_2).toBeFalsy();
+      expect(starterData.abilityAttr & AbilityAttr.ABILITY_HIDDEN).toBeFalsy();
+      expect(starterData.passiveAttr).toBe(0);
+      expect(starterData.valueReduction).toBe(0);
+      expect(starterData.classicWinCount).toBe(0);
+
+      const unlockedNatures = gameData.getNaturesForAttr(dexData.natureAttr);
+      expect(unlockedNatures.length).toBe(1);
```
Comment (DayKev) [inline test/system/dex_data.test.ts:52]: It defaults to unlocking a single random neutral nature for starters on a brand new save?

Comment (MokaStitcher) [reply test/system/dex_data.test.ts:52]: ~~I think so yeah. I could test for that, I thought I did something with that but can't remember where exactly~~
oh I did already. Yes, it's done here
https://github.com/Despair-Games/poketernity/blob/4f046b89828d65f4e8ad792cdda6820f1dd96509/src/system/game-data.ts#L1451-L1454

Comment (DayKev) [reply test/system/dex_data.test.ts:52]: Huh. Interesting.

**Review by DayKev — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]
📈
