### PR TITLE
[P1] Make getAlly() check for player legal Pokemon

### LINKED ISSUE #840: [Bug] Fusion Flare and Fusion Bolt Crash in Challenges when used with Second Slot Ineligible Pokemon in Double Battles
### Describe the bug

Fusion Flare and Fusion Bolt will crash the game if used while the Player is in a Challenge Run with any ineligible Pokemon in the second slot during a Double Battle.

-Does not occur if the Pokemon in the second slot does not exist or is Fainted

### Reproduction

Begin a Mono-Fighting Challenge run with Mankey and Type: Null
Use Fusion Flare or Fusion Bolt while the Type: Null is in the Second Slot of a Double Battle.

```
	BATTLE_TYPE_OVERRIDE: "double",
	MOVESET_OVERRIDE: [MoveId.FUSION_FLARE, MoveId.FUSION_BOLT],
```

### Expected behavior

The game should not Crash when a Pokemon uses Fusion Flare or Fusion Bolt in Challenges while the Second Slot during a Double Battle is occupied by an Ineligible Pokemon.

### Screenshots / Videos

Image

Fusion Bolt Crash Second Slot Ineligible - Crash

https://github.com/user-attachments/assets/3e58893c-5246-4fe4-ba61-290c2bb82ebd

No Pokemon in Second Slot - No Crash

https://github.com/user-attachments/assets/801a36c6-b72b-4859-ae41-7f03ea30411e

Fainted in Second Slot - No Crash

https://github.com/user-attachments/assets/b1804881-56fe-45b1-a46f-d7505d118ee5

Water Pledge in Doubles Challenges Ineligible Pokemon in Second Slot - No Crash

https://github.com/user-attachments/assets/8c5a773a-e68b-4d5c-b4ee-a7ee2b8ecb3c

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes the user will see?

Fusion flare/bolt will no longer crash the game if the user's ally is not allowed in battle

## Why am I making these changes?

Fixes #840

## What are the changes from a developer perspective?

Created a new `PlayerPokemon.getAlly()` function that overrides `Pokemon.getAlly()` and updated usages of it across the code base

## Screenshots/Videos

image

## How to test the changes?

Mono fighting challenge with mankey + type:null
```ts
BATTLE_TYPE_OVERRIDE: "double",
MOVESET_OVERRIDE: [MoveId.FUSION_FLARE, MoveId.FUSION_BOLT],
```

## Checklist

- [ ] ⚠️ If this is a PR for `main` (such as a hotfix), has the game version been updated (`npm run update-version:patch` / `npm run update version:minor`?
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

#### Are there any localization additions or changes? If so:

- [ ] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [ ] If so, please leave a link to it here:
- [ ] Have I added the `Localization` tag to this PR?

#### If there are no locale changes:
- [ ] Have I made sure **not** to commit any changes to the locale repo on this branch?

### CODE REVIEW

File: src/data/moves/move-attrs/last-move-double-power-attr.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export class LastMoveDoublePowerAttr extends VariablePowerAttr {
       const userAlly = user.getAlly();
       const enemyAlly = enemy?.getAlly();
 
-      if (userAlly && userAlly.turnData.acted) {
+      if (userAlly.isAllowedInBattle() && userAlly.turnData.acted) {
```
Comment (MokaStitcher) [inline src/data/moves/move-attrs/last-move-double-power-attr.ts]: hmm, wonder why `getAlly` doesn't make that check
I'd rather change that to avoid similar issues happening elsewhere in the code. We may need to double check that no call to getAlly expects to get invalid Pokemon, but that would be weird

Comment (Tempo-anon) [reply src/data/moves/move-attrs/last-move-double-power-attr.ts]: Adding the `isAllowedInBattle()` check to `getAlly` would mean that it would also apply for enemies 🫠 players are the only side that's affected by challenge legality

**Review by flx-sta — DISMISSED** [review]
Using `Mono-Type: Fight` Challenge with only Mankey in my team stil seems to break it

--------

<details><summary>Details</summary>
<p>


## Fusion Bolt

https://github.com/user-attachments/assets/a869ad41-8f39-4242-aba0-26e732716c5e

## Fusion Flare

https://github.com/user-attachments/assets/be2ff25a-cdb0-4377-9d19-53cc691382ab

## Console Error

fusion-flare-bolt-error

</p>
</details>

File: src/data/moves/move-attrs/last-move-double-power-attr.ts (hunk 1 above)
Comment (MokaStitcher) [reply src/data/moves/move-attrs/last-move-double-power-attr.ts]: Then it should always return true for enemies if not fainted, not sure why that would be an issue?
Or the PlayerPokemon subclass should override getAlly to add the check

Comment (MokaStitcher) [reply src/data/moves/move-attrs/last-move-double-power-attr.ts]: Also there may be a logic issue here. user and enemy should be named user and target probably, because there is nothing telling us that the user is a PlayerPokemon and the enemy an EnemyPokemon, it could very well be the other way around and in both cases it should make sure whatever mon getAlly returns is valid

File: src/field/pokemon.ts [hunk 2]
```diff
@@ -4147,6 +4150,14 @@ export class PlayerPokemon extends Pokemon {
     return this.getFieldIndex();
   }
 
+  override getAlly(): Pokemon | undefined {
+    const ally = globalScene.getPlayerField()[this.getFieldIndex() ? 0 : 1];
```
Comment (MokaStitcher) [inline src/field/pokemon.ts]:
```suggestion
    const ally = super.getAlly();
```
Technically it's the same but in case the logic behind Pokemon.getAlly ever gets changed this ensures it would get reflected here

**Review by DayKev — COMMENTED** [review]
https://github.com/Despair-Games/poketernity/pull/861

File: src/field/pokemon.ts [hunk 3]
```diff
@@ -3022,7 +3027,7 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
     if (globalScene.currentBattle.double && this.getAlly()?.isActive(true)) {
       applyAbFunc(
         AbAttrFlag.ALLIED_FIELD_DAMAGE_REDUCTION,
-        this.getAlly(),
+        this.getAlly()!,
```
Comment (torranx) [inline src/field/pokemon.ts]: I think the bang can be removed by replacing the condition `this.getAlly()?.isActive(true)` with `this.getAlly() && this.getAlly().isActive(true)`

Comment (DayKev) [reply src/field/pokemon.ts]: It would need an indirection variable added (like I did for the other ones in my review, guess I missed this one).

File: src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts [hunk 4]
```diff
@@ -133,8 +133,9 @@ class ForceSwitchOutHelper {
    * @param pokemon The {@linkcode Pokemon} attempting to switch out.
    * @returns `true` if the switch is successful
    */
-  public switchOutLogic(pokemon: Pokemon): boolean {
-    const switchOutTarget = pokemon;
+  public switchOutLogic(switchOutTarget: Pokemon): boolean {
+    const { currentBattle } = globalScene;
+    const { battleType, trainer, waveIndex } = currentBattle;
```
Comment (MokaStitcher) [inline src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts]:
```suggestion
    const { battleType, double, trainer, waveIndex } = globalScene.currentBattle;
```

File: src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts [hunk 5]
```diff
@@ -190,13 +191,12 @@ class ForceSwitchOutHelper {
           500,
         );
 
-        if (globalScene.currentBattle.double) {
-          const allyPokemon = switchOutTarget.getAlly();
+        if (currentBattle.double && allyPokemon) {
```
Comment (MokaStitcher) [inline src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts]:
```suggestion
        if (double && allyPokemon) {
```

File: src/data/moves/move-attrs/force-switch-out-attr.ts [hunk 6]
```diff
@@ -36,6 +36,8 @@ export class ForceSwitchOutAttr extends MoveEffectAttr {
   }
 
   override applyEffect(user: Pokemon, target: Pokemon, move: Move): boolean {
+    const { currentBattle } = globalScene;
+    const { battleType, double, trainer, waveIndex } = currentBattle;
```
Comment (MokaStitcher) [inline src/data/moves/move-attrs/force-switch-out-attr.ts]:
```suggestion
    const { battleType, double, trainer, waveIndex } = globalScene.currentBattle;
```

**Review by MokaStitcher — COMMENTED** [review]
few nits, not playtested yet

**Review by DayKev — DISMISSED** [review]

File: src/data/moves/move-attrs/await-combined-pledge-attr.ts [hunk 7]
```diff
@@ -36,7 +36,7 @@ export class AwaitCombinedPledgeAttr extends OverrideMoveEffectAttr {
     });
 
     if (ret) {
-      const ally = user.getAlly();
+      const ally = user.getAlly()!;
```
Comment (torranx) [inline src/data/moves/move-attrs/await-combined-pledge-attr.ts]: shouldnt this be checked instead of adding a bang?

File: src/data/moves/move.ts [hunk 8]
```diff
@@ -772,7 +772,7 @@ export abstract class Move implements Localizable {
     applyAbAttrs(AbAttrFlag.VARIABLE_MOVE_POWER, source, simulated, this, target, power);
 
     if (source.getAlly()) {
-      applyAbAttrs(AbAttrFlag.ALLY_MOVE_CATEGORY_POWER_BOOST, source.getAlly(), simulated, this, target, power);
+      applyAbAttrs(AbAttrFlag.ALLY_MOVE_CATEGORY_POWER_BOOST, source.getAlly()!, simulated, this, target, power);
```
Comment (torranx) [inline src/data/moves/move.ts]: is the bang needed here? the condition already checks for `source.getAlly()`

**Review by torranx — COMMENTED** [review]
few questions, otherwise lgtm

File: src/data/moves/move.ts (hunk 8 above)
Comment (DayKev) [reply src/data/moves/move.ts]: Because it's a function TS can't know that the `if` check will return the same value as here. That's why I used a `const` in most of the other spots in my review/suggestion.

File: src/data/moves/move-attrs/ability-copy-attr.ts [hunk 9]
```diff
@@ -34,13 +34,14 @@ export class AbilityCopyAttr extends MoveEffectAttr {
       }),
     );
 
-    if (this.copyToPartner && globalScene.currentBattle?.double && user.getAlly().hp) {
-      user.getAlly().summonData.ability = target.getAbility().id;
+    const allyPokemon = user.getAlly();
+    if (this.copyToPartner && globalScene.currentBattle?.double && allyPokemon?.hp) {
```
Comment (innerthunder) [inline src/data/moves/move-attrs/ability-copy-attr.ts]:
```suggestion
    if (this.copyToPartner && globalScene.currentBattle?.double && allyPokemon?.isActive(true)) {
```

File: src/field/pokemon.ts [hunk 10]
```diff
@@ -3019,10 +3024,11 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
     applyAbFunc(AbAttrFlag.RECEIVED_MOVE_DAMAGE_MULTIPLIER, this, simulated, source, move, receivedDamageMultiplier);
 
     /** Additionally apply friend guard damage reduction if ally has it. */
-    if (globalScene.currentBattle.double && this.getAlly()?.isActive(true)) {
+    const allyPokemon = this.getAlly();
+    if (globalScene.currentBattle.double && allyPokemon && allyPokemon.isActive(true)) {
```
Comment (innerthunder) [inline src/field/pokemon.ts]:
```suggestion
    if (globalScene.currentBattle.double && allyPokemon?.isActive(true)) {
```
I think this can be condensed?

File: src/data/moves/move.ts (hunk 8 above)
Comment (torranx) [reply src/data/moves/move.ts]: why are we not doing that here? I'd prefer the compiler checking instead of telling it it is not undefined

Comment (DayKev) [reply src/data/moves/move.ts]: I missed a couple when doing my review. 🤷

**Review by torranx — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
