### PR TITLE
[Move][P3] Splash, Celebrate, Hold Hands now display messages

### LINKED ISSUE #614: [Bug] Splash does not Display a Message when Used
Copied over from PKR 5113

### Describe the bug

Splash does not display a message when used.

**Pokerogue PR #5340**

### Reproduction

Use Splash, view the no message in the textbox.

### Expected behavior

https://github.com/user-attachments/assets/afcd42d5-f288-4dca-8be1-b7d88fd2813c

It should display "But nothing happened!" immediately after Splash is used.

https://abcboy101.github.io/poke-corpus/#q=dp.324.795&s=QPNnFvRRZc3T9w

### Screenshots / Videos

https://github.com/user-attachments/assets/f6ebe2c3-8c2b-4a83-8bb9-a6d66a04b530

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes the user will see?

Splash, Celebrate, and Hold Hands now display messages

## Why am I making these changes?

Closes #614 

## What are the changes from a developer perspective?

* Created a new `DisplayMessageAttr`

## Screenshots/Videos

Splash: 
image

Celebrate:
image

Hold Hands:
image

## How to test the changes?

```ts
const overrides = {
  MOVESET_OVERRIDE: [MoveId.SPLASH, MoveId.CELEBRATE, MoveId.HOLD_HANDS],
  BATTLE_TYPE_OVERRIDE: "double"
}
```

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

Are there any localization additions or changes? If so:

- [x] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [x] If so, please leave a link to it here: https://github.com/Despair-Games/poketernity-locales/pull/29
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Review by CodeTappert — DISMISSED** [review]

File: src/data/move-attrs/display-message-attr.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import type { Pokemon } from "#app/field/pokemon";
+import type { Move } from "#app/data/move";
+import { globalScene } from "#app/global-scene";
+import { MoveEffectAttr } from "./move-effect-attr";
+import { getPokemonNameWithAffix } from "#app/messages";
+
+/**
+ * Attribute to display a message
+ * @extends MoveAttr
```
Comment (torranx) [inline src/data/move-attrs/display-message-attr.ts]:
```suggestion
 * @extends MoveEffectAttr 
```

File: src/data/move-attrs/display-message-attr.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+ */
+export class DisplayMessageAttr extends MoveEffectAttr {
+  private displayMessage: string;
```
Comment (torranx) [inline src/data/move-attrs/display-message-attr.ts:12]: nit: name `message` would be enough here

**Review by innerthunder — DISMISSED** [review]
