### PR TITLE
[Move][P2] Fix Pollen Puff interactions when targeting an ally

### LINKED ISSUE #838: [Bug] Pollen Puff Parental Bond, Multi-Lens, Grip Claw Ally Healing Interactions Incorrect
### Describe the bug

- The Item Multi Lens and the Ability Parental Bond allows an ally-targeted Pollen Puff to heal an Ally multiple times, for the full amount.
 
- Using Pollen Puff against an Ally may trigger a Grip Claw, where the stolen item is transferred to the User.

Link to Discord's Bug Report (Pollen Puff item interactions)
https://discord.com/channels/1125469663833370665/1305920392849788990

### Reproduction

Start with Bulbasaur and Omanyte

Advance the First Wave, Transfer all Berries to the Omanyte.
Use Energy Ball and Endure on the Omanyte, then Use Pollen Puff on the Omanyte.
```
    BATTLE_TYPE_OVERRIDE: "double",
    
    MOVESET_OVERRIDE: [MoveId.POLLEN_PUFF, MoveId.ENDURE, MoveId.ENERGY_BALL],
    ABILITY_OVERRIDE: Abilities.PARENTAL_BOND,
    
   PASSIVE_ABILITY_OVERRIDE: Abilities.STURDY,
    ENEMY_MOVESET_OVERRIDE: [Moves.SPLASH],
```
    STARTING_HELD_ITEMS_OVERRIDE: [{name: "GRIP_CLAW", count: 4}, {name: "BERRY", count: 10},

### Expected behavior

https://replay.pokemonshowdown.com/gen9doublescustomgame-2319817021

### Screenshots / Videos

Pollen Puff Parental Bond

https://github.com/user-attachments/assets/95630b81-4d4c-446b-9d2d-63338fd9f1a6

Pollen Puff Grip Claw

https://github.com/user-attachments/assets/a8378bf4-7466-4b80-985b-49154beb5ce1

### Session export file

[Pollen Puff Grip Claw PE.txt](https://github.com/user-attachments/files/19255854/Pollen.Puff.Grip.Claw.PE.txt)

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

- Pollen Puff should no longer heal targeted allies multiple times when the user has Parental Bond or Multi-Lens.
- Pollen Puff should no longer steal items from targeted allies when the user has Grip Claw

## Why am I making these changes?

fixes #838 

## What are the changes from a developer perspective?

- `HealOnAllyAttr` now stops in-progress multi-hit moves when it successfully applies.
- Added a `stopMultiHit` method to `Pokemon` that resets the Pokemon's turn data to stop the execution of multi-hit moves. This is now used in other edge cases where turn data needs to be reset.
- The type guards `isAttackMove`, `isStatusMove`, and `isSelfStatusMove` now optionally take the user and target into account. With this option, Grip Claw now takes variable move category into account when determining if a move can steal items.

## Screenshots/Videos

<details><summary>Pollen Puff/Parental Bond</summary>
<p>

https://github.com/user-attachments/assets/80a590ec-2e58-4c81-8cb7-adb9c81029a0

Overrides:
```ts
const overrides = {
  BATTLE_TYPE_OVERRIDE: "double",
  ABILITY_OVERRIDE: Abilities.PARENTAL_BOND,
  MOVESET_OVERRIDE: [MoveId.POLLEN_PUFF, MoveId.CLANGOROUS_SOUL, MoveId.SPLASH],
  ENEMY_MOVESET_OVERRIDE: MoveId.SPLASH
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

</p>
</details> 

## Checklist

- [ ] ⚠️ If this is a PR for `main` (such as a hotfix), has the game version been updated (`npm run update-version:patch` / `npm run update version:minor`?
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [x] Have I made sure that any UI change works for both UI themes (dark and light)?

### CODE REVIEW

File: src/data/moves/move.ts [hunk 1]
```diff
@@ -253,16 +253,19 @@ export abstract class Move implements Localizable {
...
+  isStatusMove(user?: Pokemon, target?: Pokemon): this is StatusMove {
+    const moveCategory = !!user && !!target ? user.getMoveCategory(target, this) : this.category;
+    return moveCategory === MoveCategory.STATUS;
   }
 
-  isSelfStatusMove(): this is SelfStatusMove {
-    return this.category === MoveCategory.STATUS && this.moveTarget === MoveTarget.USER;
+  isSelfStatusMove(user?: Pokemon, target?: Pokemon): this is SelfStatusMove {
+    const moveCategory = !!user && !!target ? user.getMoveCategory(target, this) : this.category;
+    return moveCategory === MoveCategory.STATUS && this.moveTarget === MoveTarget.USER;
```
Comment (MokaStitcher) [inline src/data/moves/move.ts]: it's the same thing in the end so I don't really feel strongly about it but this could be simplified
```suggestion
    return this.isStatusMove(user, target) && this.moveTarget === MoveTarget.USER;
```

File: src/data/moves/move.ts [hunk 2]
```diff
@@ -253,16 +253,19 @@ export abstract class Move implements Localizable {
     return false;
   }
 
-  isAttackMove(): this is AttackMove {
-    return this.category === MoveCategory.PHYSICAL || this.category === MoveCategory.SPECIAL;
+  isAttackMove(user?: Pokemon, target?: Pokemon): this is AttackMove {
+    const moveCategory = !!user && !!target ? user.getMoveCategory(target, this) : this.category;
```
Comment (MokaStitcher) [inline src/data/moves/move.ts:264]: I'm not sure the double bangs are necessary, this would probably do the trick and be a bit less confusing to read?
`(user && target) ? user.getMoveCategory(target, this) : this.category;`

**Review by MokaStitcher — DISMISSED** [review]
lgtm
Of note, the Parental Bond flyout still happens when using Pollen Puff on an ally, but that whole flyout thing is a larger issue probably (for example the flyout also shows when attacking an enemy even if it gets killed on the first hit, which I'm not sure should happen either)

File: src/data/moves/move.ts (hunk 2 above)
Comment (innerthunder) [reply src/data/moves/move.ts:264]: The double bangs are necessary. They are interpreted as objects when part of a ternary

**Review by MokaStitcher — APPROVED** [review]
