### PR TITLE
[Move][Refactor] Reimplement "Frenzy" moves

### LINKED ISSUE #573: [Bug] Dancer Increments the Pokemon's Frenzy Counter when Copying a Frenzy Move
Copied over from PKR 4993

### Describe the bug

When copied by Dancer, Petal Dance increments the Frenzy counter of the Pokémon with Dancer.
This forces the Dancer user to enter a state where the Frenzy Counter is incremented, but it is not locked into a move.

While in this state, the Dancer Pokémon cannot:
-Switch out using the initial prompt (it is not offered)
-Meaningfully use Stat-dropping moves. (they are used, but the text and the effect of modifying stats does not occur.)

If Petal Dance is used by the Pokémon, through Dancer or from its own moveset, the counter increments again and it can become confused.

Link to Discord's Bug Report (Dancer breaks status moves after copying Petal Dance)
https://discord.com/channels/1125469663833370665/1317950121195081739

### Reproduction

Have a Pokemon with Dancer copy Petal Dance, then attempt to use a stat-modifying move

-Force Petal Dance on a wild Pokémon, then use an Oricorio with Quiver Dance

### Expected behavior

> If a Pokémon uses Petal Dance via Dancer while locked into Petal Dance, this usage does not count towards the 2-3 turn duration. If a Pokémon with Dancer is holding an Assault Vest, it can still successfully copy status dance moves.

and

> If a Pokémon copies Petal Dance via Dancer, it will not be locked into the move. 
-Bulba

### Screenshots / Videos

https://github.com/user-attachments/assets/8bbb5f97-a51c-4c3e-b4bd-979b0e4ada94

### Session export file

_No response_

### User data export file

_No response_

### Additional context

https://github.com/pagefaultgames/pokerogue/issues/4277
Ghost Frenzy bug that has been fixed.

### LINKED ISSUE #688: [Move][Checkup] Variations of Thrash
## Move Requirements

- [x] Documentation
- [x] Tests
- [x] Forces the user to repeat the move for 1-2 turns without consuming PP
- [x] Cancels move repetition if the move has no effect against its target or the user is otherwise interrupted
- [x] Confuses the user on the last turn of the move's execution, even if the move is interrupted on that turn

Note: Variations of Thrash = Petal Dance, Outrage, Raging Fury

## Related Bugs

- #573 

## Sources

[Bulbapedia - Thrash](https://bulbapedia.bulbagarden.net/wiki/Thrash_(move))
[Bulbapedia - Variations of Thrash](https://bulbapedia.bulbagarden.net/wiki/Move_variations#Variations_of_Thrash)

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

N/A

## Why am I making these changes?

Setting up for full implementations of Uproar, Rollout, and Ice Ball. Also fixes #573 

## What are the changes from a developer perspective?

- The logic for effects that force consecutive move use is now consolidated under the `MoveLockTag` abstract battler tag. `FrenzyTag` now inherits from this new tag to implement the effects of Thrash, Outrage, Petal Dance, and Raging Fury.
- Sky Drop is now set up to remove all move-locking effects instead of just Frenzy.

## How to test the changes?

`npm run test thrash`
`npm run test sky_drop` (1 new test)

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [?] Have I provided screenshots/videos of the changes (if applicable)?
  - [n/a] Have I made sure that any UI change works for both UI themes (dark and light)?

### CODE REVIEW

File: src/data/battler-tags.ts [hunk 1]
```diff
@@ -1105,15 +1107,69 @@ export class NightmareTag extends BattlerTag {
...
 
-export class FrenzyTag extends BattlerTag {
-  constructor(turnCount: number, sourceMoveId: MoveId, sourceId: number) {
-    super(BattlerTagType.FRENZY, BattlerTagLapseType.CUSTOM, turnCount, sourceMoveId, sourceId);
+/**
+ * Locks the source into using a move consecutively for `turnCount - 1` turns. If the move fails or is interrupted
+ * during any of these uses, this effect is removed.
+ * @extends BattlerTag
+ */
+export abstract class MoveLockTag extends BattlerTag {
```
Comment (torranx) [inline src/data/battler-tags.ts:1119]: think this'll need a `loadTag()`?

File: src/phases/move-phase.ts [hunk 2]
```diff
@@ -565,8 +564,6 @@ export class MovePhase extends BattlePhase {
    *     to lapse on move failure/cancellation.
    *
    *     TODO: ...this seems weird.
-   * - Lapses `AFTER_MOVE` tags:
-   *   - This handles the effects of {@link MoveId.SUBSTITUTE Substitute}
```
Comment (DayKev) [inline src/phases/move-phase.ts:571]: Was this changed at some point and this was missed?

File: src/data/battler-tags.ts (hunk 1 above)
Comment (innerthunder) [reply src/data/battler-tags.ts:1119]: This doesn't add any fields on top of `BattlerTag`, so it should be fine as is

File: src/phases/move-phase.ts (hunk 2 above)
Comment (innerthunder) [reply src/phases/move-phase.ts:571]: This, on top of the lapse call in `MoveEndPhase`, actually made `AFTER_MOVE` tags lapse twice. Substitute's animation wasn't affected by the double-lapse, though.

**Review by torranx — DISMISSED** [review]
code looks good to me (no playtest)

**Review by DayKev — DISMISSED** [review]

**Comment by DayKev** [comment]
Same as torranx, approval based on code review (tests look like they should cover the behavior).

**Review by torranx — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
