### PR TITLE
[P2] Fix Poltergeist's pre-move message triggering during enemy move evaluation

### LINKED ISSUE #692: [Bug] Poltergeist's "is about to be attacked by" Message is Played when Present in the Opponent's Moveset
### Describe the bug

The message is played even if the opponent selects a different move.

-Occurs due to enemy AI move selection

**Fixed by Pokerogue #5040**

Link to Discord (Slower opponent using Poltergeist plays item attack text out of order.)
https://discord.com/channels/1125469663833370665/1262803137295552664

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

It should only play when the move is executed

### Screenshots / Videos

Slower Opponent

https://github.com/user-attachments/assets/269f6b22-9a86-4168-9534-681bcbbf48cd

Faster Opponent

https://github.com/user-attachments/assets/3fd7a420-0a73-4aad-a3a4-f7d331225f99

Poketernity

https://github.com/user-attachments/assets/430f6f7d-b476-4349-8711-35aab334c122

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Innerthunder made a thread in the discord, which if implemented could fix this bug.
https://discord.com/channels/1125469663833370665/1176874654015684739/1264000392300335135

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

Poltergeist's message ("[Pokemon] is about to be attacked by its [item]!") no longer shows out of turn during the enemy move selection process.

## Why am I making these changes?

fixes #692 

## What are the changes from a developer perspective?

- `AttackedByItemAttr` now extends `PreMoveMessageAttr`
- Messages from `PreMoveMessageAttr` no longer play if the move fails to execute. **NOTE**: this diverges from Chilly Reception's message logic where the move is meant to play its message regardless of it failing, but for the sake of reusability I think this is the better approach to accommodate for both moves

## Screenshots/Videos

https://github.com/user-attachments/assets/da35bd6b-5215-4065-91db-5ae7069a27a9

## How to test the changes?

Using overrides:
1. Give enemies Poltergeist
2. Give your starting pokemon any transferrable held item
3. When the enemy selects Poltergeist, the pre-move message should only play during the move's execution

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [n/a] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [x] Have I made sure that any UI change works for both UI themes (dark and light)?

### CODE REVIEW

File: src/data/move-attrs/attacked-by-item-attr.ts [hunk 1]
```diff
@@ -1,30 +1,31 @@
...
-    return (_user: Pokemon, target: Pokemon, _move: Move) => {
+export class AttackedByItemAttr extends PreMoveMessageAttr {
+  constructor() {
+    super((_user, target, _move) => {
       const heldItems = target.getHeldItems().filter((i) => i.isTransferable);
-      if (heldItems.length === 0) {
-        return false;
-      }
-
       const itemName = heldItems[0]?.type?.name ?? "item";
```
Comment (innerthunder) [inline src/data/move-attrs/attacked-by-item-attr.ts:18]: "item" should be localizable here, but under normal circumstances this fallback should never show

File: src/data/move-attrs/attacked-by-item-attr.ts [hunk 2]
```diff
@@ -1,30 +1,31 @@
...
+        pokemonName: getPokemonNameWithAffix(target),
+        itemName,
+      });
+    });
+  }
+
+  /** Causes failure if the target isn't holding a transferable item */
+  override getCondition(): MoveConditionFunc {
+    return (_user: Pokemon, target: Pokemon, _move: Move) =>
+      target.getHeldItems().filter((i) => i.isTransferable).length > 0;
```
Comment (PigeonBar) [inline src/data/move-attrs/attacked-by-item-attr.ts]:
```suggestion
      target.getHeldItems().some((i) => i.isTransferable);
```

File: src/data/move-attrs/attacked-by-item-attr.ts (hunk 1 above)
Comment (Tempo-anon) [reply src/data/move-attrs/attacked-by-item-attr.ts:18]: Can just add a comment about it then
```suggestion
      // "Item" should be localizable here but under normal circumstances this fallback should never show
      const itemName = heldItems[0]?.type?.name ?? "item";
```

**Review by Tempo-anon — DISMISSED** [review]
Item reworking when :despair:

**Review by PigeonBar — APPROVED** [review]
