### PR TITLE
[P2][P3] Starter moveset for Pokemon with forms now updates properly

### LINKED ISSUE #517: [Bug] Some Form Changing Pokémon cannot swap current moves with other current moves in starter select
Copied over from PKR 3937

### Describe the bug

The bug consists of three pokémon which need a secondary pokémon to change forms... 
The first instance reported was in this bug report which reported Calyrex with a unusual behaviour I looked into further: https://discord.com/channels/1125469663833370665/1279222639092563989
The bug affects currently to my knowledge Calyrex, Necrozma, Hoopa and Kyurem.
It prevents the user from rearraging the moves that were already on like any other pokémon by putting the opposite move you want to arrange in a certain way, it doesn't seem to affect any moves not on the pokémon being egg or normal ones in the non set moves... 

### Session export file

Not needed, its in the main server and easy to replicate

### User data export file

_No response_

### Expected behavior

It should let the moves legit swap between each other.

### Screenshots / Videos

https://github.com/user-attachments/assets/266bd168-3f8a-4de3-af60-10779a12cb17

### What OS did you observe the bug on?

PC/Windows

### If other please specify

_No response_

### Which browser do you use?

Chrome

### If other please specify

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MokaStitcher**
## What are the changes the user will see?

- It is now possible to switch the order of moves in the current moveset of Pokemon with forms
- Switching the form of a starter after having added it to the team will no longer start the run with an empty moveset

## Why am I making these changes?

- Fixes #517 
- Having an empty moveset is not ideal

## What are the changes from a developer perspective?

- rewrote `switchMoveHandler` to streamline it. (The original issue was this 
https://github.com/Despair-Games/poketernity/blob/969326c4ba21961d2581b6b839c6d3c84539a4f5/src/ui/starter-select-ui-handler.ts#L2425
checking `starterMoveData[props.formIndex][existingMoveIndex]` instead of `starterMoveData[props.formIndex][i]`)
But that check wasn't really needed anyway, so it's gone now)
- put the code updating the current starters' moveset at the end of `switchMoveHandler` in its own function, and also call it in `setSpecies` when changing the form of a Pokemon, to make sure the moveset gets updated

## Screenshots/Videos

<details><summary>Move swaping</summary>

https://github.com/user-attachments/assets/5950d0f1-526a-4ecf-817e-086b9553ce30

https://github.com/user-attachments/assets/f63f4c56-2265-4c7d-a129-8b7330781286

</details> 

<details><summary>Empty moveset</summary>

https://github.com/user-attachments/assets/eb7d4ae8-6203-46c6-846e-3514b8e1017b

https://github.com/user-attachments/assets/7002249f-ebd7-46d6-a683-5eaeea2d5c67

</details> 

## How to test the changes?

<details><summary>Move Swapping</summary>

  - Starter select
  - Go to a mon with form specific movesets like Pikachu, Meowth, Oricorio or Calyrex [Full list of affected mons](<https://github.com/Despair-Games/poketernity/blob/beta/src/data/balance/pokemon-form-level-moves.ts>)
  - Try to swap around the moves in its moveset several time. 
</details>
<details><summary>Empty Moveset</summary>

1. Starter select
2. Go to a mon with form specific movesets and that you can change form for, like Pikachu, Rotom or Paldean Tauros
3. Add the mon to the team
4. While it's in the team, switch it to a different form. The shown moveset should change.
<sub> If it doesn't, either the mon doesn't fit the requirements, or you have legacy data of a time when the species didn't have form specific movesets. To fix it temove the mon from the team, make any change to the moveset, then go back to step 3
5. Do not update the moveset and start the run
6. The Pokemon should have the correct moveset 
</details>

## Checklist

- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes manually?

- [X] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [X] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

File: src/ui/starter-select-ui-handler.ts [hunk 1]
```diff
@@ -2391,56 +2391,50 @@ export default class StarterSelectUiHandler extends MessageUiHandler {
     this.checkIconId(this.starterIcons[index], species, props.female, props.formIndex, props.shiny, props.variant);
   }
 
-  switchMoveHandler(i: number, newMoveId: MoveId, moveId: MoveId) {
+  switchMoveHandler(targetIndex: number, newMoveId: MoveId, previousMoveId: MoveId): void {
```
Comment (Tempo-anon) [inline src/ui/starter-select-ui-handler.ts:2401]: function should have tsdoc

File: src/ui/starter-select-ui-handler.ts [hunk 2]
```diff
@@ -2391,56 +2391,50 @@ export default class StarterSelectUiHandler extends MessageUiHandler {
...
+  /**
+   * Update the starter moveset for the given species, if it is part of the selected starters.
+   * @param speciesId the {@linkcode Species} to consider
+   */
+  private updateSelectedStarterMoveset(speciesId: Species): void {
+    if (!this.starterMoveset) {
+      return;
+    }
+    // Find the index of that Pokemon species in the team, if it is present.
+    const starterIndex = this.starterSpecies.findIndex((species: PokemonSpecies) => species.speciesId === speciesId);
```
Comment (Tempo-anon) [inline src/ui/starter-select-ui-handler.ts]: This is operating under the assumption that there will only ever be one of that species on the team (in the starter-select) right? Would it be good to have some future proofing in case multiples of a species are wanted?

Comment (MokaStitcher) [reply src/ui/starter-select-ui-handler.ts]: The whole thing will have to be rewritten before we can even start thinking about that. And it will definitely not involve a 10 separate starterXXX attributes holding the data for the starters like now.
But sure, I'll add a foreach instead. But it will mean that even with several of the same mons they all have the same moveset, so it's not really future proof either way

**Review by torranx — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]
