### PR TITLE
[Bug] Fix crash with trapping move animations

### LINKED ISSUE #617: [Bug] Certain Partial Trapping Moves (Whirlpool, Sand Tomb) Crash when the User and Opponent Faints at the Same Time
Copied over from PKR 5122

### Describe the bug

When Animations are set to ON, and a damaging trapping move faints a Pokemon at the same time as the trappee to end-of-turn damage the game crashes.

- Whirlpool, Fire Spin, and Sand Tomb, crash the game while Infestation and Snap Trap does not.
- Replacing the animation for Sand Tomb for Infestation's in `battler-tags.ts` does not result in a Crash when Sand Tomb is used.
- Turning Move Animations OFF prevents a crash from occurring.
-Does not require Salt Cure, Leech Seed/Sappy Seed and cannot crash from taking Future Sight damage.

Link to Discord's Bug Report (Game crash on end-of-turn damage?)
https://discord.com/channels/1125469663833370665/1328079300112678954

**Pokerogue PR #5337**

### Reproduction

**Move Animations ON**

Choose a Starter weak to the Opposing Trapping move. Use Salt Cure.
-Using Infestation or Snap Trap does not Crash.

Modify OPP_HELD_ITEMS_OVERRIDE: type: Type.    to the type of the move used in OPP_MOVESET_OVERRIDE
```
	MOVESET_OVERRIDE: [Moves.SALT_CURE],
	ABILITY_OVERRIDE: Abilities.STURDY,

	OPP_LEVEL_OVERRIDE: 5,
	OPP_SPECIES_OVERRIDE: Species.FLETCHINDER,
	OPP_MOVESET_OVERRIDE: [Moves.FIRE_SPIN],
	OPP_IVS_OVERRIDE: [0, 31, 0, 31, 0, 0],
	OPP_ABILITY_OVERRIDE: Abilities.STURDY,

	STARTING_HELD_ITEMS_OVERRIDE: [{name: "ATTACK_TYPE_BOOSTER", type: Type.ROCK, count: 50}],
	OPP_HELD_ITEMS_OVERRIDE: [{name: "ATTACK_TYPE_BOOSTER", type: Type.FIRE, count: 50}],
```

Try replacing
```
super(BattlerTagType.FIRE_SPIN, CommonAnim.FIRE_SPIN, turnCount, Moves.FIRE_SPIN, sourceId);
```
With
```
super(BattlerTagType.FIRE_SPIN, CommonAnim.INFESTATION, turnCount, Moves.FIRE_SPIN, sourceId);
```

### Expected behavior

The game shouldn't crash when Pokemon faint to secondary damage while the Opponent faints to Partial Trapping. or vise-versa. Specifically Fire Spin, Sand Tomb, and Whirlpool. (There are probably others, and other exceptions.)

In addition, Pokemon should not take turn-end damage related to partial-trapping if the Trappee faints before them from turn-end damage due to having a higher Speed stat.

-Pokemon should also take turn-end damage in order of their Speed, with Leech Seed and Salt Cure going before Trapping Damage. Rather than it always starting with the Player's.
https://replay.pokemonshowdown.com/gen9customgame-2281249171

### Screenshots / Videos

Screenshot (543)

<details><summary>
Player and Opponent's side
</summary>
(Enemy Trapping Move, Player Chip Damage)

https://github.com/user-attachments/assets/d197d6ca-d979-48ee-8d16-d45b57c3edf5

Player Trapping Move (Whirlpool), Enemy Chip Damage. (Leech only works if the Enemy used it)

https://github.com/user-attachments/assets/f6a4a173-5868-4e01-92a2-c6db024cca53

</details>

<details><summary>
Player Salt Cure and Enemy Salt Cure does not Crash
</summary>

https://github.com/user-attachments/assets/2582f41f-e1d4-4016-96d1-709cefc05542

</details>

<details><summary>
Certain Moves Crash
</summary>
Player's Salt Cure and Enemy's Sand Tomb Crashes

https://github.com/user-attachments/assets/259a68e5-6768-4fea-8d09-67314709f86c

Player's Salt Cure and Enemy's Fire Spin Crashes

https://github.com/user-attachments/assets/f27250ef-3590-4c91-90a5-6e20850c6ef2

Player's Salt Cure and Enemy's Infestation does not Crash

https://github.com/user-attachments/assets/ec2032b7-bf76-4a31-9c55-82a87f40ab4b

Player's Salt Cure and Enemy's Snap Trap does not Crash

https://github.com/user-attachments/assets/3fb6aeda-e28c-4a83-a7e5-780be5170e09

</details>
<details><summary>
Move Animation OFF Fire Spin does not Crash
</summary>

Player Salt Cure Enemy Fire Spin Anims OFF

https://github.com/user-attachments/assets/f8c77c91-b4a7-40d8-91c1-8671ff6232cd

</details>

### Session export file

_No response_

### User data export file

_No response_

### Additional context

When a Faster Pokemon faints from Salt Cure, and the other Pokemon is bound by a Partial Trapping Move, the Partial Trapping effect should wear off the MOMENT the Pokemon (Trappee) faints, even if by passive damage (Salt Cure)

https://replay.pokemonshowdown.com/gen9customgame-2280390566

https://github.com/user-attachments/assets/b91506d3-f00d-406d-b8a7-2770230c2fed

Caterpie is 9 speed, Fletchling is 12

https://github.com/user-attachments/assets/694f8454-37c4-4589-bf34-53ec4708e16f

### LINKED ISSUE #992: [P1] Battle/Move animations crash game
### Describe the bug

When using any Move the game crashes 

Tested with:
- Ember
- Scratch
- Howl

### Reproduction

_No special overrides needed_

1. Make sure Move animation are enabled in the settings
2. Open the browser dev-tools console
3. Start a game e.g. with Charmander 
4. Use any move -> Crash

### Expected behavior

Seeing the move animation and not having the game crash

### Screenshots / Videos

https://github.com/user-attachments/assets/cf2056e7-c70d-4178-8ced-48ef0887da1e

### Session export file

n/a

### User data export file

n/a

### Additional context

n/a

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
If a Pokémon faints to the residual damage of a trapping move when both Pokémon are affected by trapping moves, the game will no longer crash.

## Why am I making these changes?
Fixes #617 
Fixes #992 

## What are the changes from a developer perspective?
(Copied from the original PR)
The `setSpritePriority` submethod within `src/data/battle-anims.ts`'s `BattleAnim.play` has been refactored and fixed.
The cause of the bug was due to `gameScene.field.moveBelow()` possibly being called with an undefined value. It may have also possible for it to be called with a value that did not exist in the `gameScene.field` container.
In either case, that method has now been rewritten to be substantially shorter (~20 lines WITH comments compared to ~40 beforehand, which didn't even have comments).

---

Additional changes not from the original PR:
- Renamed `AnimFrameTargets` to `AnimFrameTarget` to match the type name.
- Removed type casting from `MoveAnim#getAnim` and added a `TODO` note so that it can be fixed in the future.

## Screenshots/Videos
<details><summary>Before fix (crash)</summary>
<p>

https://github.com/user-attachments/assets/4c9796ce-3a9e-4705-b734-308278f838e6

</p>
</details> 
<details><summary>After fix (no crash)</summary>
<p>

https://github.com/user-attachments/assets/0689dc55-a13b-44d6-8ada-68741d8521f6

</p>
</details> 

## How to test the changes?
```ts
const overrides = {
  MOVESET_OVERRIDE: [ MoveId.SALT_CURE ],
  ABILITY_OVERRIDE: AbilityId.STURDY,

  ENEMY_LEVEL_OVERRIDE: 5,
  ENEMY_SPECIES_OVERRIDE: SpeciesId.FLETCHINDER,
  ENEMY_MOVESET_OVERRIDE: [ MoveId.FIRE_SPIN ],
  ENEMY_IVS_OVERRIDE: [ 0, 31, 0, 31, 0, 0 ],
  ENEMY_ABILITY_OVERRIDE: AbilityId.STURDY,

  STARTING_HELD_ITEMS_OVERRIDE: [{ name: "ATTACK_TYPE_BOOSTER", type: ElementalType.ROCK, count: 50 }],
  ENEMY_HELD_ITEMS_OVERRIDE: [{ name: "ATTACK_TYPE_BOOSTER", type: ElementalType.FIRE, count: 50 }],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

### CODE REVIEW

File: src/data/animations/move-anim.ts [hunk 1]
```diff
@@ -23,9 +23,8 @@ export class MoveAnim extends BattleAnim {
   }
 
   getAnim(): AnimConfig {
-    return moveAnims.get(this.moveId) instanceof AnimConfig
-      ? (moveAnims.get(this.moveId) as AnimConfig)
-      : (moveAnims.get(this.moveId)?.[this.user?.isPlayer() ? 0 : 1] as AnimConfig);
+    const anim = moveAnims.get(this.moveId);
+    return anim instanceof AnimConfig ? anim : anim?.[this.user?.isPlayer() ? 0 : 1]!; // TODO: resolve bang
```
Comment (Tempo-anon) [inline src/data/animations/move-anim.ts]: chained ternaries :pikamad:

File: src/enums/anim-frame-target.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /** Specifies the type of sprite affected by an animation */
-export const AnimFrameTargets = {
+export const AnimFrameTarget = {
```
Comment (Tempo-anon) [inline src/enums/anim-frame-target.ts:2]: nit: this rename adds a lot of changes to this PR

File: src/data/animations/battle-anims.ts [hunk 3]
```diff
@@ -385,50 +385,44 @@ export abstract class BattleAnim {
...
+                /** The method that is being used to move the sprite.*/
+                let moveFunc:
+                  | ((sprite: Phaser.GameObjects.GameObject, target: Phaser.GameObjects.GameObject) => void)
+                  | ((sprite: Phaser.GameObjects.GameObject) => void) = globalScene.field.bringToTop;
+
+                if (priority === 0) {
+                  // Place the sprite in front of the pokemon on the field.
+                  targetSprite =
+                    globalScene.getEnemyField().find((p) => p) ?? globalScene.getPlayerField().find((p) => p);
+                  console.log(typeof targetSprite);
```
Comment (Tempo-anon) [inline src/data/animations/battle-anims.ts]: nit: does this `console.log` need to be here? It's not in any of the other logic branches

File: src/data/animations/battle-anims.ts [hunk 4]
```diff
@@ -385,50 +385,44 @@ export abstract class BattleAnim {
...
+                  moveFunc = globalScene.field.moveBelow;
+                } else if (priority === 2 && this.bgSprite) {
+                  moveFunc = globalScene.field.moveAbove;
+                  targetSprite = this.bgSprite;
+                } else if (priority === 2 || priority === 3) {
+                  moveFunc = priority === 2 ? globalScene.field.moveBelow : globalScene.field.moveAbove;
+                  if (frame.focus === AnimFocus.USER) {
+                    targetSprite = this.user;
+                  } else if (frame.focus === AnimFocus.TARGET) {
```
Comment (Tempo-anon) [inline src/data/animations/battle-anims.ts]: will `frame.focus` only be USER or TARGET? I feel like lines 413-419 can be simplified a bit

File: src/data/animations/battle-anims.ts [hunk 5]
```diff
@@ -385,50 +385,44 @@ export abstract class BattleAnim {
...
+                    targetSprite = this.target;
+                  }
                 }
+                // If target sprite is not undefined and exists in the field container, then move the sprite using the moveFunc.
+                // Otherwise, default to just bringing it to the top.
+                targetSprite && globalScene.field.exists(targetSprite)
+                  ? moveFunc.bind(globalScene.field)(moveSprite as Phaser.GameObjects.GameObject, targetSprite)
+                  : globalScene.field.bringToTop(moveSprite as Phaser.GameObjects.GameObject);
```
Comment (Tempo-anon) [inline src/data/animations/battle-anims.ts]: nit: instead of another ternary I think an if/else looks cleaner

**Review by Tempo-anon — COMMENTED** [review]
I don't know much about animation so I'm only commenting on code style

File: src/data/animations/battle-anims.ts (hunk 3 above)
Comment (DayKev) [reply src/data/animations/battle-anims.ts]: Oh it's probably leftover from testing, I'll remove it.

File: src/data/animations/battle-anims.ts (hunk 4 above)
Comment (DayKev) [reply src/data/animations/battle-anims.ts]: If it's neither of those then `targetSprite` stays `undefined`, which is accounted for by the ternary at the bottom (which I'll change to an `if`/`else`).

File: src/enums/anim-frame-target.ts [hunk 6]
```diff
@@ -1,18 +1,18 @@
...
-  TARGET: "target",
+  TARGET: 1,
   /** Affects a component of the animation's visual effects */
-  IMAGE: "image",
+  IMAGE: 2,
 } as const;
 
 /** The sprite types affected by an animation */
-export type AnimFrameTarget = (typeof AnimFrameTargets)[keyof typeof AnimFrameTargets];
+export type AnimFrameTarget = (typeof AnimFrameTarget)[keyof typeof AnimFrameTarget];
```
Comment (flx-sta) [inline src/enums/anim-frame-target.ts:18]: Q: The type can have the same name as the const?

**Review by flx-sta — DISMISSED** [review]

File: src/enums/anim-frame-target.ts (hunk 6 above)
Comment (DayKev) [reply src/enums/anim-frame-target.ts:18]: Yeah, TS will automatically figure out which you're using depending on whether it's being used as a type or as a value.

Comment (flx-sta) [reply src/enums/anim-frame-target.ts:18]: Makes sense. I swear I’ve tried that but it complained. Might have been that I was having enum const or so idk. Good to know

**Comment by flx-sta** [comment]
@DayKev conflicts

**Review by flx-sta — APPROVED** [review]

**Review by innerthunder — APPROVED** [review]
