### PR TITLE
[P1] Fix consecutive-use moves infinitely queueing failing moves

### LINKED ISSUE #768: [Bug] Infinite loop after defeating a wild Pokemon with a "frenzy" move (e.g., Thrash)
### Describe the bug

If you defeat a wild Pokemon with a "frenzy" move, such as Thrash, and then you advance to the next wave while still locked into Thrash, it causes an infinite loop where Thrash fails over and over again.

In this state, refreshing and reloading the session causes a crash, so the save file is effectively bricked.

### Reproduction

One-shot a wild Pokemon using Thrash, then proceed to the next wave.

### Expected behavior

The Pokemon should remain locked into Thrash, and Thrash should successfully hit the next wave's wild Pokemon.

### Screenshots / Videos

<details><summary>The infinite loop</summary>
<p>

https://github.com/user-attachments/assets/65cfd896-30d8-4153-8e90-d3c81209dfc3

</p>
</details>
<details><summary>The crash log after reloading</summary>
<p>

Image

</p>
</details> 

### Session export file

_No response_

### User data export file

_No response_

### Additional context

`MoveLockTag` has a lapse type of `AFTER_MOVE`. This means that it determines Thrash's targets during the previous turn right after defeating the enemy Pokemon, which causes the tag to be unable to set Thrash's next targets. This causes Thrash to fail in a way that does not clear the Pokemon's move queue, so Thrash will continue failing indefinitely.

Reloading the session empties the Pokemon's move history, which then causes `MoveLockTag.lapse()` to crash.

(Also, this was discovered quite some time ago, but I forgot to open a GitHub issue, oops)

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

Frenzy moves (e.g. Outrage) should no longer infinitely fail after eligible targets are cleared from the field.

## Why am I making these changes?

fixes #768 

## What are the changes from a developer perspective?

- `MoveLockTag` no longer resolves follow-up moves' targeting immediately after using the associated move. Instead, follow-up moves' targeting is resolved at the start of the next turn, during forced move selection.
- Added a new test to `thrash.test.ts` to verify continued execution between waves

## Screenshots/Videos

https://github.com/user-attachments/assets/33c3bfb0-b933-49a4-90ee-75c1a806b287

## How to test the changes?

`npm run test thrash` - 1 new test

<details><summary>Overrides for manual testing</summary>
<p>

```
BATTLE_TYPE_OVERRIDE: "single",
STARTING_LEVEL_OVERRIDE: 50,
MOVESET_OVERRIDE: [MoveId.OUTRAGE, MoveId.SPLASH],
ENEMY_MOVESET_OVERRIDE: MoveId.SPLASH
```

You can also change the battle type to `"double"` to verify target redirection.

</p>
</details>

## Checklist

- [x] ⚠️ If this is a PR for `main` (such as a hotfix), has the game version been updated (`npm run update-version:patch` / `npm run update version:minor`?
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [n/a] Have I made sure that any UI change works for both UI themes (dark and light)?

#### If there are no locale changes:
- [x] Have I made sure **not** to commit any changes to the locale repo on this branch?

### CODE REVIEW

File: src/data/battler-tags.ts [hunk 1]
```diff
@@ -1121,35 +1138,72 @@ export abstract class MoveLockTag extends BattlerTag {
     }
 
     const ret =
-      super.lapse(pokemon, lapseType)
+      super.lapse(pokemon, BattlerTagLapseType.AFTER_MOVE)
       && !!lastTargets
       && lastTargets.length > 0
```
Comment (DayKev) [inline src/data/battler-tags.ts]:
```suggestion
      && lastTargets?.length > 0
```

File: src/data/battler-tags.ts [hunk 2]
```diff
@@ -1108,11 +1108,28 @@ export class NightmareTag extends BattlerTag {
...
+
+  /**
+   * Queues the tag's source move on all turns except this tag's last turn
+   * if the tag holder's last move was successful. The queued move initially
+   * has no targets; the move targeting is instead resolved by this tag's custom lapse.
+   * @param pokemon the {@linkcode Pokemon} with this tag
+   * @returns `true` if the tag is to be retained after lapsing
+   */
+  protected handleAfterMoveLapse(pokemon: Pokemon): boolean {
     const { move: lastMove, targets: lastTargets, result: lastMoveResult } = pokemon.getLastXMoves()?.[0];
```
Comment (DayKev) [inline src/data/battler-tags.ts]: There needs to be a `null` check for `lastMove` before L1136 when `lastMove.id` is checked.

File: src/data/battler-tags.ts [hunk 3]
```diff
@@ -1121,35 +1138,72 @@ export abstract class MoveLockTag extends BattlerTag {
...
    * Obtains the target(s) for move actions queued by this tag
    * @param pokemon the {@linkcode Pokemon} with this tag
    * @param move the {@linkcode Move} queued by this tag
-   * @param lastTargets the target(s), by {@linkcode BattlerIndex}, attacked by
-   * the source Pokemon's last use of the move.
    * @returns the target(s), by {@linkcode BattlerIndex}, for the next usage of this tag's move
    */
-  protected getNextTargets(pokemon: Pokemon, move: Move, lastTargets: BattlerIndex[]): BattlerIndex[] {
+  protected getNextTargets(pokemon: Pokemon, move: Move): BattlerIndex[] {
     if ((move.moveTarget = MoveTarget.RANDOM_NEAR_ENEMY)) {
```
Comment (DayKev) [inline src/data/battler-tags.ts]: Should this be `===`?

File: src/data/battler-tags.ts [hunk 4]
```diff
@@ -1108,48 +1108,105 @@ export class NightmareTag extends BattlerTag {
  * @extends BattlerTag
  */
 export abstract class MoveLockTag extends BattlerTag {
+  protected lastTargets: BattlerIndex[];
+
   constructor(tagType: BattlerTagType, turnCount: number, sourceMoveId: MoveId) {
     super(tagType, BattlerTagLapseType.AFTER_MOVE, turnCount, sourceMoveId);
```
Comment (PigeonBar) [inline src/data/battler-tags.ts:1114]:
```suggestion
    super(tagType, [BattlerTagLapseType.AFTER_MOVE, BattlerTagLapseType.CUSTOM], turnCount, sourceMoveId);
```

File: src/data/battler-tags.ts [hunk 5]
```diff
@@ -1108,48 +1108,105 @@ export class NightmareTag extends BattlerTag {
...
+
+  /**
+   * Queues the tag's source move on all turns except this tag's last turn
+   * if the tag holder's last move was successful. The queued move initially
+   * has no targets; the move targeting is instead resolved by this tag's custom lapse.
+   * @param pokemon the {@linkcode Pokemon} with this tag
+   * @returns `true` if the tag is to be retained after lapsing
+   */
+  protected handleAfterMoveLapse(pokemon: Pokemon): boolean {
     const { move: lastMove, targets: lastTargets, result: lastMoveResult } = pokemon.getLastXMoves()?.[0];
```
Comment (PigeonBar) [inline src/data/battler-tags.ts]:
```suggestion
    if (!pokemon.getLastXMoves()?.[0]) {
      return false;
    }
    const { move: lastMove, targets: lastTargets, result: lastMoveResult } = pokemon.getLastXMoves().[0];
```

File: src/data/battler-tags.ts [hunk 6]
```diff
@@ -1108,48 +1108,105 @@ export class NightmareTag extends BattlerTag {
...
+      if (
+        !lastTarget?.isActive(true)
+        && globalScene.currentBattle.double
+        && adjacentTarget?.isActive(true)
+        && adjacentTarget !== pokemon
+      ) {
+        return [adjacentIndex];
+      } else {
+        return this.lastTargets;
+      }
```
Comment (PigeonBar) [inline src/data/battler-tags.ts:1211]: Isn't this redirecting already handled by MovePhase?

Comment (innerthunder) [reply src/data/battler-tags.ts:1211]: No, MovePhase only handles redirection from abilities and moves, e.g. Lightning Rod and Follow Me

File: src/data/battler-tags.ts (hunk 4 above)
Comment (innerthunder) [reply src/data/battler-tags.ts:1114]: This isn't necessary; `lapseTag` doesn't look for matching tag lapse types when invoking a `CUSTOM` lapse, and `lapseTags` isn't used anywhere to do `CUSTOM` lapses in bulk.

File: src/data/battler-tags.ts [hunk 7]
```diff
@@ -1108,48 +1108,108 @@ export class NightmareTag extends BattlerTag {
...
+   * if the tag holder's last move was successful. The queued move initially
+   * has no targets; the move targeting is instead resolved by this tag's custom lapse.
+   * @param pokemon the {@linkcode Pokemon} with this tag
+   * @returns `true` if the tag is to be retained after lapsing
+   */
+  protected handleAfterMoveLapse(pokemon: Pokemon): boolean {
+    if (!pokemon.getLastXMoves()?.[0]) {
+      return false;
+    }
+    const { move: lastMove, targets: lastTargets, result: lastMoveResult } = pokemon.getLastXMoves().[0];
```
Comment (DayKev) [inline src/data/battler-tags.ts]:
```suggestion
    const { move: lastMove, targets: lastTargets, result: lastMoveResult } = pokemon.getLastXMoves()[0];
```

File: src/data/battler-tags.ts [hunk 8]
```diff
@@ -1108,48 +1108,108 @@ export class NightmareTag extends BattlerTag {
...
+
+    if (!lastMove) {
+      return false;
+    }
```
Comment (DayKev) [inline src/data/battler-tags.ts]:
```suggestion
```
With Pigeon's suggestion these `null` checks are no longer necessary.

File: src/data/battler-tags.ts [hunk 9]
```diff
@@ -1108,48 +1108,108 @@ export class NightmareTag extends BattlerTag {
...
     if (![this.sourceMoveId, MoveId.NONE].includes(lastMove.id)) {
       return true;
     }
 
     const ret =
-      super.lapse(pokemon, lapseType)
-      && !!lastTargets
-      && lastTargets.length > 0
+      super.lapse(pokemon, BattlerTagLapseType.AFTER_MOVE)
+      && lastTargets?.length > 0
```
Comment (DayKev) [inline src/data/battler-tags.ts]:
```suggestion
      && lastTargets.length > 0
```

**Review by DayKev — COMMENTED** [review]
Based on Pigeon's suggestion that was implemented.

File: src/data/battler-tags.ts [hunk 10]
```diff
@@ -1108,48 +1108,104 @@ export class NightmareTag extends BattlerTag {
  * @extends BattlerTag
  */
 export abstract class MoveLockTag extends BattlerTag {
+  protected lastTargets: BattlerIndex[];
```
Comment (PigeonBar) [inline src/data/battler-tags.ts]:
```suggestion
  protected lastTargets?: BattlerIndex[];
```

File: src/data/battler-tags.ts [hunk 11]
```diff
@@ -1108,48 +1108,104 @@ export class NightmareTag extends BattlerTag {
...
    * @returns the target(s), by {@linkcode BattlerIndex}, for the next usage of this tag's move
    */
-  protected getNextTargets(pokemon: Pokemon, move: Move, lastTargets: BattlerIndex[]): BattlerIndex[] {
-    if ((move.moveTarget = MoveTarget.RANDOM_NEAR_ENEMY)) {
+  protected getNextTargets(pokemon: Pokemon, move: Move): BattlerIndex[] {
+    if (move.moveTarget === MoveTarget.RANDOM_NEAR_ENEMY) {
       return getMoveTargets(pokemon, move.id).targets;
     } else {
-      return lastTargets;
+      // Note: this assumes the locked move is single-target
```
Comment (PigeonBar) [inline src/data/battler-tags.ts:1197]:
```suggestion
      // Failsafe if `this.lastTargets` has somehow not been set
      if (!this.lastTargets?.length > 0) {
        this.lastTargets = pokemon.isPlayer() ? [BattlerIndex.ENEMY] : [BattlerIndex.PLAYER];
      }
      
      // Note: this assumes the locked move is single-target
```

File: src/data/battler-tags.ts [hunk 12]
```diff
@@ -1108,48 +1108,109 @@ export class NightmareTag extends BattlerTag {
...
    */
-  protected getNextTargets(pokemon: Pokemon, move: Move, lastTargets: BattlerIndex[]): BattlerIndex[] {
-    if ((move.moveTarget = MoveTarget.RANDOM_NEAR_ENEMY)) {
+  protected getNextTargets(pokemon: Pokemon, move: Move): BattlerIndex[] {
+    if (move.moveTarget === MoveTarget.RANDOM_NEAR_ENEMY) {
       return getMoveTargets(pokemon, move.id).targets;
     } else {
-      return lastTargets;
+      // Failsafe if `this.lastTargets` has somehow not been set
+      if (!this.lastTargets) {
```
Comment (PigeonBar) [inline src/data/battler-tags.ts]:
```suggestion
      if (!this.lastTargets?.length) {
```

**Comment by PigeonBar** [comment]
As one final failsafe, `MoveLockTag.onRemove()` should probably also clear the Pokemon's move queue.

**Review by PigeonBar — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]
