### PR TITLE
[Bug] Fix HP bar rounding errors

### LINKED ISSUE #1007: [Bug] Occasional rounding errors in the HP bar UI
### Describe the bug

Due to rounding errors, the HP bar UI occasionally displays an HP value that is 1 larger than the Pokemon's true HP.

### Reproduction

For example: At certain HP values, surviving at 1 HP using Sturdy will cause the HP bar to display 2 HP.

### Expected behavior

The HP bar should always display the Pokemon's true HP.

### Screenshots / Videos

Geodude survives on 1 HP using Sturdy, but the HP bar displays 2 HP:

https://github.com/user-attachments/assets/8565adfd-75c2-4d08-88a4-e1358f6ccae6

### Session export file

[20250418 HP Bar Rounding.pkty.txt](https://github.com/user-attachments/files/19818450/20250418.HP.Bar.Rounding.pkty.txt)

### User data export file

_No response_

### Additional context

The code that updates the HP bar's numbers:
https://github.com/Despair-Games/poketernity/blob/f29b8c741817a3bbd090931d207c4e5da95e1cbf/src/ui/components/battle-info.ts#L664-L669

### PR DESCRIPTION
**Pull request by PigeonBar**
## What are the changes the user will see?

The HP bar should no longer have rounding errors.

## Why am I making these changes?

Fixes #1007.

## What are the changes from a developer perspective?

- Added a line to set the UI's HP numbers to the Pokemon's final HP during `onComplete`.
- `setHpNumbers()` now also updates `this.lastHp`, for some small cleanup.

## Screenshots/Videos

<details><summary>Before the changes: HP bar displays 2 HP after Sturdy</summary>
<p>

https://github.com/user-attachments/assets/dfa41b47-e1af-4968-b8d9-5bbebed3f438

</p>
</details> 
<details><summary>After the changes HP bar displays 1 HP after Sturdy</summary>
<p>

https://github.com/user-attachments/assets/5b71ff7f-d8f4-41cf-a1de-5b562cead4cc

</p>
</details> 

## How to test the changes?

Activate Sturdy on different player Pokemon with different max HP values.

## Checklist

- [x] Otherwise: **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR? (Same as #1008, except this PR also preserves the animation of the HP numbers increasing/decreasing alongside the HP bar)
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes? (N/A due to the tests mocking out all animations)
- [x] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

**Review by torranx — DISMISSED** [review]

File: src/ui/components/battle-info.ts [hunk 1]
```diff
@@ -830,6 +832,11 @@ export class BattleInfo extends Phaser.GameObjects.Container {
     this.levelContainer.setX((this.player ? -41 : -50) - 8 * Math.max(levelStr.length - 3, 0));
   }
 
+  /**
+   * Updates the UI to display the Pokemon's HP numbers.
+   * @param hp - The Pokemon's current HP
+   * @param maxHp - The Pokemon's maximum HP
```
Comment (DayKev) [inline src/ui/components/battle-info.ts]:
```suggestion
```
Instead of adding TSDocs for the params, just rename `hp` to `currentHp`. Then the names of both are fully self-explanatory and we don't have redundant docs.

**Review by innerthunder — DISMISSED** [review]
I prefer this over #1008

File: src/ui/components/battle-info.ts [hunk 2]
```diff
@@ -665,12 +666,13 @@ export class BattleInfo extends Phaser.GameObjects.Container {
             if (this.player && this.lastHp !== pokemon.hp) {
               const tweenHp = Math.ceil(this.hpBar.scaleX * pokemon.getMaxHp());
```
Comment (Tempo-anon) [inline src/ui/components/battle-info.ts:667]: Is this `Math.ceil` still needed here? My proposed solution just had this part changed for `pokemon.hp`

**Review by Tempo-anon — APPROVED** [review]
Happy to accept this one as the fix

File: src/ui/components/battle-info.ts (hunk 2 above)
Comment (innerthunder) [reply src/ui/components/battle-info.ts:667]: I'm worried that without it, intermediate HP text during the animation would be displayed as decimal

**Review by torranx — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

File: src/ui/components/battle-info.ts (hunk 2 above)
Comment (DayKev) [reply src/ui/components/battle-info.ts:667]: Wait, what exactly is this doing? What is `hpBar.scaleX`?

Comment (PigeonBar) [reply src/ui/components/battle-info.ts:667]: `hpBar.scaleX` represents how full the HP bar UI is during each frame of the HP bar's animation.

`pokemon.hp` is always equal to the Pokemon's final HP, so setting `tweenHp` to `pokemon.hp` kind of works, it just means that the displayed HP would not show intermediate values throughout the HP bar's animation.

Comment (DayKev) [reply src/ui/components/battle-info.ts:667]: So it's best to keep it like this then?
