### PR TITLE
[Checkup][Ability] Drizzle

### LINKED ISSUE #1183: [Ability][Checkup] Drizzle
# Drizzle
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Drizzle summons rain in battle as soon as a Pokémon with Drizzle enters the battle. 
- [x] The rain will last 5 turns.
- [x] Drizzle will also fail to activate if heavy rain, extremely harsh sunlight, or strong winds are already in effect. 

## References
- [Bulbapedia - Drizzle](https://bulbapedia.bulbagarden.net/wiki/Drizzle_(Ability))

### PR DESCRIPTION
**Pull request by flx-sta**
## What are the changes the user will see?

n/a

## Why am I making these changes?

Closes #1183 

## What are the changes from a developer perspective?

- Drizzle test coverage
- PostSummonWeatherChangeAbAttr table added to ts-doc

## Screenshots/Videos

n/a

## How to test the changes?

`npm run test:silent`

## Checklist

- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?

### CODE REVIEW

File: src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts [hunk 1]
```diff
@@ -4,7 +4,21 @@ import type { WeatherType } from "#enums/weather-type";
...
+ * |-------------------|--------------|-------|--------------------|
+ * | Drizzle           | Rain         |     5 | No primal override |
+ * | Drought           | Sunny        |     5 | No primal override |
+ * | Sand Stream       | Sandstorm    |     5 | No primal override |
+ * | Snow Warning      | Hail         |     5 | No primal override |
+ * | Desolate Land     | Harsh Sun    |     ∞ | Primal             |
+ * | Primordial Sea    | Heavy Rain   |     ∞ | Primal             |
+ * | Delta Stream      | Strong Winds |     ∞ | Primal             |
+ * | Air Lock          | NONE         |     - | Suppresses all     |
+ * | Cloud Nine        | NONE         |     - | Suppresses all     |
```
Comment (Tempo-anon) [inline src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts]: These two actually use the `SuppressWeatherEffectAbAttr` which is different. It negates the effects of weather but does not remove them.

File: test/abilities/drizzle.test.ts [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+      .battleType("single")
+      .disableCrits()
+      .enemySpecies(SpeciesId.MAGIKARP)
+      .enemyAbility(AbilityId.BALL_FETCH)
+      .enemyMoveset(MoveId.SPLASH)
+      .startingLevel(100)
+      .enemyLevel(100);
+  });
+
+  it("should cause rain weather", async () => {
```
Comment (Tempo-anon) [inline test/abilities/drizzle.test.ts]: This test is not needed as the next one tests for it as well

File: test/abilities/drizzle.test.ts [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+
+    await classicMode.runToSummon([SpeciesId.FEEBAS]);
+    game.scene.arena.trySetWeather(weatherType, false);
+    expect(game).toHaveWeather(weatherType);
+
+    await phaseInterceptor.to("PostSummonPhase");
+
+    expect(game).toHaveWeather(WeatherType.RAIN);
+  });
+});
```
Comment (Tempo-anon) [inline test/abilities/drizzle.test.ts:124]: maybe add a test for interaction with weather suppression?

Comment (flx-sta) [reply test/abilities/drizzle.test.ts:124]: For example ? Interaction with air lock or stuff ? I’d say that should be its own tests for those abilities

Comment (Tempo-anon) [reply test/abilities/drizzle.test.ts:124]: It's a weird line to draw. I think the test here would be to check that drizzle still triggers 5 turns of rain even if cloud nine is in effect. The test for cloud nine would then test that the effects of rain are negated.

File: test/abilities/drizzle.test.ts [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+  WeatherType.SNOW,
+  WeatherType.FOG,
+].map((weatherType) => ({
+  weatherName: capitalizeString(WeatherType[weatherType], "_", false, true),
+  weatherType,
+}));
+
+//#endregion
+
+describe("Ability - Drizzle", () => {
```
Comment (innerthunder) [inline test/abilities/drizzle.test.ts:38]: Can this be expanded to a `describe.each` for all of the weather-setting abilities?

Comment (flx-sta) [reply test/abilities/drizzle.test.ts:38]: Possibly yes, but I split those tasks into separate PRs to make them easier to review and easier to work on.
So I'd say we can apply that change as soon as someone starts working on a second weather-setting ability.

The reason for that is also that the primal ones have quite some unique behaviors to cover in tests where I'm not sure if the generic test coverage here would work for them

File: src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts [hunk 5]
```diff
@@ -4,7 +4,19 @@ import type { WeatherType } from "#enums/weather-type";
...
+ * | Ability           | Weather      | Turns | Notes              |
+ * |-------------------|--------------|-------|--------------------|
+ * | Drizzle           | Rain         |     5 | No primal override |
+ * | Drought           | Sunny        |     5 | No primal override |
+ * | Sand Stream       | Sandstorm    |     5 | No primal override |
+ * | Snow Warning      | Hail         |     5 | No primal override |
+ * | Desolate Land     | Harsh Sun    |     ∞ | Primal             |
+ * | Primordial Sea    | Heavy Rain   |     ∞ | Primal             |
+ * | Delta Stream      | Strong Winds |     ∞ | Primal             |
+ * | Orichalcum Pulse  | Harsh Sun    |     ∞ | Primal             |
```
Comment (Tempo-anon) [inline src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts]: This is incorrect. Orichalcum Pulse summons normal sun

**Review by Tempo-anon — DISMISSED** [review]
LGTM pending the incorrect comment

File: src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts [hunk 6]
```diff
@@ -4,7 +4,19 @@ import type { WeatherType } from "#enums/weather-type";
...
+ * | Ability           | Weather      | Turns | Notes              |
+ * |-------------------|--------------|-------|--------------------|
+ * | Drizzle           | Rain         |     5 | No primal override |
+ * | Drought           | Sunny        |     5 | No primal override |
+ * | Sand Stream       | Sandstorm    |     5 | No primal override |
+ * | Snow Warning      | Hail         |     5 | No primal override |
+ * | Desolate Land     | Harsh Sun    |     ∞ | Primal             |
+ * | Primordial Sea    | Heavy Rain   |     ∞ | Primal             |
+ * | Delta Stream      | Strong Winds |     ∞ | Primal             |
+ * | Orichalcum Pulse  | Sun          |     ∞ | Primal             |
```
Comment (DayKev) [inline src/data/abilities/ab-attrs/post-summon-weather-change-ab-attr.ts]:
```suggestion
 * | Drizzle           | Rain         |     5 |                    |
 * | Drought           | Sun          |     5 |                    |
 * | Sand Stream       | Sandstorm    |     5 |                    |
 * | Snow Warning      | Hail         |     5 |                    |
 * | Orichalcum Pulse  | Sun          |     5 |                    |
 * | Desolate Land     | Harsh Sun    |     ∞ | Primal (permanent) |
 * | Primordial Sea    | Heavy Rain   |     ∞ | Primal (permanent) |
 * | Delta Stream      | Strong Winds |     ∞ | Primal (permanent) |
```

File: test/abilities/drizzle.test.ts [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+    game.scene.arena.trySetWeather(weatherType, false);
+    expect(game).toHaveWeather(weatherType);
+
+    await phaseInterceptor.to("PostSummonPhase");
+
+    expect(game).toHaveWeather(WeatherType.RAIN);
+  });
+
+  it.each(weatherSuppressingAbilities)(
+    "should not be suppressed by $name ability and last the rain for 5 turns",
```
Comment (DayKev) [inline test/abilities/drizzle.test.ts]:
```suggestion
    "should not be stopped from setting weather by $name ability",
```

**Review by DayKev — DISMISSED** [review]
