### PR TITLE
[P2] Fog can be suppressed

### LINKED ISSUE #559: [Bug] Cloud Nine and Air Lock do not Suppress Fog Accuracy Reduction
Copied over from PKR 4932

### Describe the bug

Abilities that suppress the effects of weather do not suppress the accuracy reduction of fog.

Link to Discord's Bug Report (Cloud Nine doesn't remove fog's accuracy debuff)
https://discord.com/channels/1125469663833370665/1275901459418054778

### Reproduction

Use a move with 100 accuracy using a pokemon with Cloud Nine or Air Lock whilst in Fog

### Expected behavior

> Cloud Nine suppresses all effects brought on by weather, including move power increases, end-of-turn damage, accuracy changes, relevant abilities and so on.
-Pokemondb

### Screenshots / Videos

https://github.com/user-attachments/assets/badde3a7-6c3e-4e0c-a74c-d6775d31ef37

Fog and Cloud Nine

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes the user will see?

Fog no longer lowers accuracy if suppressed

## Why am I making these changes?

Fixes #559

## What are the changes from a developer perspective?

* Created a new constant for fog accuracy modifier if we want to tweak it
* Added an extra suppression check for fog
* Updated tests

## Screenshots/Videos

n/a

## How to test the changes?

`npm run test weather_fog`

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

Are there any localization additions or changes? If so:

- [ ] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [ ] If so, please leave a link to it here:
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -119,3 +119,6 @@ export const IV_MAX = 31;
  * Tweak this value if necessary for balancing purposes
  */
 export const DYNAMAX_DAMAGE_TAKEN_FACTOR = 2 / 3;
+
+// Custom implementation. Mainline is 0.6
```
Comment (DayKev) [inline src/constants.ts]:
```suggestion
/** Custom implementation. Mainline is 0.6 */
```

**Review by DayKev — DISMISSED** [review]

**Review by PigeonBar — DISMISSED** [review]

File: src/constants.ts [hunk 2]
```diff
@@ -119,3 +119,6 @@ export const IV_MAX = 31;
...
+export const FOG_ACCURACY_MODIFIER = 0.9;
```
Comment (innerthunder) [inline src/constants.ts]: nit: A more descriptive name for how it's applied:
```suggestion
export const FOG_ACCURACY_MULTIPLIER = 0.9;
```
