### PR TITLE
[Ability][Checkup][Bug] Move Flag Power Boost Abilities Checkup

### LINKED ISSUE #305: [Ability][Checkup] Iron Fist
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Iron Fist causes the power of affected punching moves to increase by 20%. 

### List of Affected Moves
- [x] Comet Punch
- [x] Mega Punch
- [x] Fire Punch
- [x] Ice Punch
- [x] Thunder Punch
- [x] Dizzy Punch
- [x] Mach Punch
- [x] Dynamic Punch
- [x] Focus Punch
- [x] Meteor Mash
- [x] Shadow Punch
- [x] Sky Uppercut
- [x] Hammer Arm
- [x] Drain Punch
- [x] Bullet Punch
- [x] Power-Up Punch
- [x] Ice Hammer
- [x] Plasma Fists
- [x] Double Iron Bash
- [x] Wicked Blow
- [x] Surging Strikes
- [x] Headlong Rush
- [x] Jet Punch
- [x] Rage Fist

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310

## References
- [Bulbapedia - Iron Fist](https://bulbapedia.bulbagarden.net/wiki/Iron_Fist_(Ability))

### LINKED ISSUE #307: [Ability][Checkup] Sharpness
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Sharpness boosts the strength of slicing moves used by a Pokémon with this Ability by 50%. 

### List of Affected Moves
- [x] Cut
- [x] Razor Leaf
- [x] Slash
- [x] Fury Cutter
- [x] Air Cutter
- [x] Aerial Ace
- [x] Leaf Blade
- [x] Night Slash
- [x] Air Slash
- [x] X-Scissor
- [x] Psycho Cut
- [x] Cross Poison
- [x] Sacred Sword
- [x] Razor Shell
- [x] Secret Sword
- [x] Solar Blade
- [x] Behemoth Blade
- [x] Stone Axe
- [x] Ceaseless Edge
- [x] Population Bomb
- [x] Kowtow Cleave
- [x] Psyblade
- [x] Bitter Blade
- [x] Aqua Cutter
- [x] Mighty Cleave
- [x] Tachyon Cutter

## References
- [Bulbapedia - Sharpness](https://bulbapedia.bulbagarden.net/wiki/Sharpness_(Ability))

### LINKED ISSUE #308: [Ability][Checkup] Mega Launcher
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Mega Launcher boosts the strength of aura and pulse moves used by a Pokémon with this Ability. Damage-dealing moves are boosted in power by 50%
- [x] Heal Pulse heals 75% of the target's maximum HP rather than the usual 50% 

### List of Affected Moves
- [x] Water Pulse
- [x] Aura Sphere
- [x] Dark Pulse
- [x] Dragon Pulse
- [x] Heal Pulse
- [x] Origin Pulse
- [x] Terrain Pulse

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310

## Related Bugs
- #310 fixes Mega Launcher's interaction with heal pulse. 

## References
- [Bulbapedia - Mega Launcher](https://bulbapedia.bulbagarden.net/wiki/Mega_Launcher_(Ability))

### LINKED ISSUE #309: [Ability][Checkup] Tough Claws
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Tough Claws boosts the power of the Pokémon's contact moves by approximately 30% 

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310

## References
- [Bulbapedia - Tough Claws](https://bulbapedia.bulbagarden.net/wiki/Tough_Claws_(Ability))

### LINKED ISSUE #320: [Ability][Checkup] Punk Rock
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Punk Rock boosts the power of the Pokémon's sound-based moves by 30%. 
- [x] A Pokémon with Punk Rock also takes half damage from damaging sound-based moves. 

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310

## References
- [Bulbapedia - Punk Rock](https://bulbapedia.bulbagarden.net/wiki/Punk_Rock_(Ability))

### LINKED ISSUE #321: [Ability][Checkup] Reckless
## Ability Requirements
- [ ] Documentation
- [ ] Tests
- [ ] Reckless increases the power of moves that have recoil or crash damage by 20% except for Struggle

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310 

## Related Bugs
- RECKLESS_MOVE does not seem to be an official flag used by mainline or Showdown. It's not technically a bug but it is something to keep in mind when we do eventually refactor move flags.

## References
- [Bulbapedia - Reckless](https://bulbapedia.bulbagarden.net/wiki/Reckless_(Ability))

### LINKED ISSUE #322: [Ability][Checkup] Strong Jaw
## Ability Requirements
- [x] Documentation
- [x] Tests
- [x] Strong Jaw increases the power of the Pokémon's biting moves by 50%. 

## Related PRs
- https://github.com/Despair-Games/poketernity/pull/310

## References
- [Bulbapedia - Strong Jaw](https://bulbapedia.bulbagarden.net/wiki/Strong_Jaw_(Ability))

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?

A Pokemon with Mega Launcher will have its Heal Pulse recovery boosted to 75% of the Pokemon's HP

## Why am I making these changes?

Ability Checkup for the abilities Iron Fist, Tough Claws, Mega Launcher, Strong Jaw, Punk Rock, Reckless, and Sharpness

## What are the changes from a developer perspective?

- New child ability attribute - MoveFlagPowerBoostAbAttr - created. 
- New ability attribute for Mega Launcher - RecoveryBoostAbAttr - created so that Heal Pulse was handled correctly. Technically, you could use MoveFlagPowerBoostAbAttr for it - however, I was concerned that it could lead to multipliers being incorrectly applied to certain moves in the future. 
- Tests created for move-flag-power-boost ability attribute
- Separate test created for Mega Launcher-Heal Pulse interaction

## How to test the changes?

`npm run test ability_name`

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

### CODE REVIEW

**Review by Tempo-anon — DISMISSED** [review]
Can probably group the iron fist, mega launcher, sharpness, and tough claws test into a single move flag power boost test

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * +---------------+---------------+------------+
+ * |    Ability    |   Move Flag   | Multiplier |
+ * +---------------+---------------+------------+
+ * | Iron Fist     | PUNCHING_MOVE |        1.2 |
+ * | Mega Launcher | PULSE_MOVE    |        1.5 |
+ * | Tough Claws   | MAKES_CONTACT |        1.3 |
+ * | Sharpness     | SLICING_MOVE  |        1.5 |
+ * +---------------+---------------+------------+
+ */
+export class MoveFlagPowerBoostAbAttr extends VariableMovePowerAbAttr {
```
Comment (PigeonBar) [inline src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]: This attr can also be used for the following abilities:
- Punk Rock (`MoveFlags.SOUND_BASED`)
- Strong Jaw (`MoveFlags.BITING_MOVE`)
- Reckless (`MoveFlags.RECKLESS_MOVE`, note that this does not seem to be an official flag in `all_moves.json`)

Comment (PigeonBar) [inline src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]: Also, is there a reason why this class is not extending `MovePowerBoostAbAttr`?

Comment (frutescens) [reply src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]: I knew I was forgetting some abilities, thank you :)

Comment (frutescens) [reply src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]: It could but MovePowerBoostAbAttr requires a conditional to be passed into its constructor while VariableMovePowerBoostAbAttr does not

File: test/abilities/mega_launcher.test.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    game.override
+      .ability(Abilities.MEGA_LAUNCHER)
+      .battleType("single")
+      .disableCrits()
+      .enemySpecies(Species.MAGIKARP)
+      .enemyAbility(Abilities.BALL_FETCH)
+      .enemyMoveset(Moves.SPLASH);
+  });
+
+  it("should boost the healing of Heal Pulse to 75% of the target's maximum HP", async () => {
```
Comment (innerthunder) [inline test/abilities/mega_launcher.test.ts:35]: `getHealRatio` should not be made public for the sake of tests. A better approach would be to damage the heal target (setting `target.hp` should be fine), mocking a return value for the target's max HP, and get results based on the amount healed after the move is used.

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts (hunk 1 above)
Comment (innerthunder) [reply src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]: I figure extending `MovePowerBoostAbAttr` would be cleaner. You could feed the condition into the constructor, e.g.:
```ts
constructor(flagRequired: MoveFlags, powerMultiplier: number, showAbility: boolean = true) {
  super(requireFlagCondition(flagRequired), powerMultiplier, showAbility); // requireFlagCondition is defined outside of the class
}
```
Then the class would no longer need to override `apply`, and the `flagRequired` and `powerMultiplier` fields don't need to be redefined.

File: src/data/move-attrs/heal-attr.ts [hunk 3]
```diff
@@ -33,8 +36,10 @@ export class HealAttr extends MoveEffectAttr {
    * Helper function to obtain this attribute's heal ratio
    * @returns a heal ratio in the interval [0, 1]
    */
-  protected getHealRatio(_user: Pokemon, _target: Pokemon, _move: Move): number {
-    return this.healRatio;
+  public getHealRatio(user: Pokemon, target: Pokemon, move: Move): number {
```
Comment (innerthunder) [inline src/data/move-attrs/heal-attr.ts]:
```suggestion
  protected getHealRatio(user: Pokemon, target: Pokemon, move: Move): number {
```

File: src/data/move-attrs/swallow-heal-attr.ts [hunk 4]
```diff
@@ -9,7 +9,7 @@ import { HealAttr } from "#app/data/move-attrs/heal-attr";
  * @extends HealAttr
  */
 export class SwallowHealAttr extends HealAttr {
-  protected override getHealRatio(user: Pokemon, _target: Pokemon, _move: Move): number {
+  public override getHealRatio(user: Pokemon, _target: Pokemon, _move: Move): number {
```
Comment (innerthunder) [inline src/data/move-attrs/swallow-heal-attr.ts]:
```suggestion
  protected override getHealRatio(user: Pokemon, _target: Pokemon, _move: Move): number {
```

File: src/data/move-attrs/weather-heal-attr.ts [hunk 5]
```diff
@@ -16,7 +16,7 @@ export abstract class WeatherHealAttr extends HealAttr {
     super(0.5);
   }
 
-  protected override getHealRatio(_user: Pokemon, _target: Pokemon, _move: Move): number {
+  public override getHealRatio(_user: Pokemon, _target: Pokemon, _move: Move): number {
```
Comment (innerthunder) [inline src/data/move-attrs/weather-heal-attr.ts]:
```suggestion
  protected override getHealRatio(_user: Pokemon, _target: Pokemon, _move: Move): number {
```

**Review by innerthunder — CHANGES_REQUESTED** [review]
You forgot to revert the changes to `getHealRatio`

File: src/data/move-attrs/boost-heal-attr.ts [hunk 6]
```diff
@@ -30,7 +30,7 @@ export class BoostHealAttr extends HealAttr {
     this.condition = condition;
   }
 
-  protected override getHealRatio(user: Pokemon, target: Pokemon, move: Move): number {
+  public override getHealRatio(user: Pokemon, target: Pokemon, move: Move): number {
```
Comment (PigeonBar) [inline src/data/move-attrs/boost-heal-attr.ts]:
```suggestion
  protected override getHealRatio(user: Pokemon, target: Pokemon, move: Move): number {
```

**Review by innerthunder — DISMISSED** [review]

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts [hunk 7]
```diff
@@ -0,0 +1,25 @@
+import type { PokemonAttackCondition } from "#app/@types/PokemonAttackCondition";
+import type { MoveFlags } from "#enums/move-flags";
+import { MovePowerBoostAbAttr } from "./move-power-boost-ab-attr";
+
+/**
+ * Ability attribute that boosts the power of a move by a factor if it has a specified flag
+ * +---------------+---------------+------------+
```
Comment (DayKev) [inline src/data/ab-attrs/move-flag-power-boost-ab-attr.ts:8]:
```suggestion
 * ```
 * +---------------+---------------+------------+
```
If you're going to put these tables in tsdocs they need to have the backticks above and below them, otherwise they look like this:
image

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+ * |    Ability    |   Move Flag   | Multiplier |
+ * +---------------+---------------+------------+
+ * | Iron Fist     | PUNCHING_MOVE |        1.2 |
+ * | Mega Launcher | PULSE_MOVE    |        1.5 |
+ * | Tough Claws   | MAKES_CONTACT |        1.3 |
+ * | Punk Rock     | SOUND_BASED   |        1.3 |
+ * | Strong Jaw    | BITING_MOVE   |        1.5 |
+ * | Reckless      | RECKLESS_MOVE |        1.2 |
+ * | Sharpness     | SLICING_MOVE  |        1.5 |
+ * +---------------+---------------+------------+
```
Comment (DayKev) [inline src/data/ab-attrs/move-flag-power-boost-ab-attr.ts:18]:
```suggestion
 * +---------------+---------------+------------+
 * ```
```

File: src/data/all-abilities.ts [hunk 9]
```diff
@@ -947,20 +937,18 @@ export function initAbilities() {
...
-    new Ability(Abilities.MEGA_LAUNCHER, 6).attr(
-      MovePowerBoostAbAttr,
-      (_user, _target, move) => !!move?.hasFlag(MoveFlags.PULSE_MOVE),
-      1.5,
-    ),
+    new Ability(Abilities.MEGA_LAUNCHER, 6)
+      .attr(MoveFlagPowerBoostAbAttr, MoveFlags.PULSE_MOVE, 1.5)
+      .attr(
+        RecoveryBoostAbAttr,
+        (pokemon, _target, move) => !!pokemon && !!move && move.checkFlag(MoveFlags.PULSE_MOVE, pokemon, null),
```
Comment (DayKev) [inline src/data/all-abilities.ts]:
```suggestion
        (pokemon, _target, move) => !!pokemon && !!move?.checkFlag(MoveFlags.PULSE_MOVE, pokemon, null),
```

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+ */
+export class MoveFlagPowerBoostAbAttr extends MovePowerBoostAbAttr {
+  constructor(flagRequired: MoveFlags, powerMultiplier: number) {
+    const moveFlagCondition: PokemonAttackCondition = (user, _target, move) =>
+      !!user && !!move && move.checkFlag(flagRequired, user, null);
```
Comment (DayKev) [inline src/data/ab-attrs/move-flag-power-boost-ab-attr.ts]:
```suggestion
      !!user && !!move?.checkFlag(flagRequired, user, null);
```

File: src/data/ab-attrs/move-flag-power-boost-ab-attr.ts (hunk 8 above)
Comment (innerthunder) [reply src/data/ab-attrs/move-flag-power-boost-ab-attr.ts:17]: line order's mixed up here

**Review by innerthunder — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
