### PR TITLE
fix(move): Normalize/etc shouldn't affect certain moves

### LINKED ISSUE #816: [Bug] Certain Moves Affected by Normalize (Multi Attack, Revelation Dance, Terrain Pulse)
### Describe the bug

Multi Attack, Revelation Dance, and Terrain Pulse are all incorrectly affected by Normalize.
-They have their type changed to Normal.

Link to Discord's Bug Report (Revelation Dance affected by type-change abilities incorrectly)
https://discord.com/channels/1125469663833370665/1281026326739816560

```
    new Ability(Abilities.NORMALIZE, 4)
      .attr(MoveTypeChangeAbAttr, PokemonType.NORMAL, 1.2, (user, target, move) => {
        return ![ Moves.HIDDEN_POWER, Moves.WEATHER_BALL, Moves.NATURAL_GIFT, Moves.JUDGMENT, Moves.TECHNO_BLAST ].includes(move.id);
      }),
```

### Reproduction

```
        STARTER_SPECIES_OVERRIDE: Species.SILVALLY,
	MOVESET_OVERRIDE: [Moves.MULTI_ATTACK, Moves.REVELATION_DANCE, Moves.WEATHER_BALL, Moves.TERRAIN_PULSE],
	PASSIVE_ABILITY_OVERRIDE: Abilities.NORMALIZE,


	OPP_LEVEL_OVERRIDE: 5,
	OPP_MOVESET_OVERRIDE: [Moves.SPLASH],
	OPP_ABILITY_OVERRIDE: Abilities.DRIZZLE,
	OPP_PASSIVE_ABILITY_OVERRIDE: Abilities.PSYCHIC_SURGE,

```

### Expected behavior

Multi-Attack, Terrain Pulse and damaging Z-Moves are not affected by Normalize.
 https://bulbapedia.bulbagarden.net/wiki/Normalize_(Ability)

Revelation Dance is unaffected by Normalize,
https://bulbapedia.bulbagarden.net/wiki/Revelation_Dance_(move)

### Screenshots / Videos

Normalize affects Revelation Dance, Multi-Attack, Terrain Pulse, and not Weather Ball

https://github.com/user-attachments/assets/e014c133-aca5-4fdf-9875-c4d0a5553122

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Revelation Dance, Judgement, Multi-Attack and Terrain Pulse are no longer incorrectly affected by abilities that change move types.

## Why am I making these changes?
- Fixes #816 

## What are the changes from a developer perspective?
`MoveTypeChangeAbAttr` returns early if the move has one of the following `MoveAttr`s: `MatchUserTypeAttr` (Revelation Dance), `FormChangeItemTypeAttr` (Judgement and Multi-Attack), `TerrainPulseTypeAttr` (Terrain Pulse).

## How to test the changes?
`pnpm test:silent revelation-dance`
`pnpm test:silent judgement`
`pnpm test:silent multi-attack`
`pnpm test:silent terrain-pulse`

## Checklist
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [x] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?

### CODE REVIEW

File: src/data/abilities/ab-attrs/move-type-change-ab-attr.ts [hunk 1]
```diff
@@ -29,16 +32,21 @@ export class MoveTypeChangeAbAttr extends PreAttackAbAttr {
...
-      return true;
+    // Revelation Dance, Judgement and Multi-Attack, and Terrain Pulse ignore ability-based move type changes
+    if (
+      move.hasAttr(MatchUserTypeAttr)
+      || move.hasAttr(FormChangeItemTypeAttr)
+      || move.hasAttr(TerrainPulseTypeAttr)
+      || !this.condition(pokemon, defender, move)
+    ) {
+      return false;
     }
```
Comment (innerthunder) [inline src/data/abilities/ab-attrs/move-type-change-ab-attr.ts:43]: 1. Checking `condition` here is completely unnecessary since it's already checked externally in `applyAbAttrs`
2. These attributes should probably be checked within the condition instead.

What's included vs. what's not included in ability conditions overall is kind of an inconsistent mess right now, but the main difference is that conditions are checked within `Pokemon.hasAbility` and similar methods.

Comment (DayKev) [reply src/data/abilities/ab-attrs/move-type-change-ab-attr.ts:43]: `applyAbAttrs` checks `AbAttr#extraCondition`:
```ts
// apply-ab-attrs.ts
    const matchingAttrs = ability.getAttrs<TAttr>(abAttrFlag).filter((attr) => {
      const condition = attr.getCondition();
      return !condition || condition(pokemon);
    });
// ab-attr.ts
  public getCondition(): AbAttrCondition | null {
    return this.extraCondition ?? null;
  }
// init-abilities.ts
    new Ability(AbilityId.GALVANIZE, 7) //
      // condition is passed in via the attr's constructor and not via `.conditionalAttr`
      .attr(MoveTypeChangeAbAttr, ElementalType.ELECTRIC, 1.2, normalTypeMoveConversionCondition),
```
The `MoveTypeChangeAbAttr#condition` field is separate from that, for whatever reason, and is defined/added outside of that framework.

Comment (innerthunder) [inline src/data/abilities/ab-attrs/move-type-change-ab-attr.ts:43]: Are we sure that `normalTypeMoveConversionCondition` doesn't also apply to Normalize? That already checks for these attributes via their parent attribute and excludes Tera Blast / Starstorm.

If it does, then all of the abilities with this attribute would have the same `condition`...

Comment (DayKev) [reply src/data/abilities/ab-attrs/move-type-change-ab-attr.ts:43]: The abilities with that condition only work on Normal type moves (which is checked in that condition), whereas Normalize changes all moves into Normal moves.

Comment (DayKev) [reply src/data/abilities/ab-attrs/move-type-change-ab-attr.ts:43]: Also Liquid Voice has this attr too and has its own separate condition.

**Review by innerthunder — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]
