### PR TITLE
[AI] Give all battler tags target benefit score

### LINKED ISSUE #546: [Bug] Moves that add Certain BattlerTags Return Score of NaN
Copied over from PKR 4748

### Describe the bug

Throat Chop returns a score of -20, Torment returns 0, Endure returns -20

Please Cross-reference Battlertags here

https://github.com/pagefaultgames/pokerogue/blob/5797f265a415cdaabdc639bdcf9ce949f01c24f7/src/enums/battler-tag-type.ts#L2

with the ones that currently have scoring here

https://github.com/pagefaultgames/pokerogue/blob/5797f265a415cdaabdc639bdcf9ce949f01c24f7/src/data/move.ts#L4991

### Reproduction

Look at the code please

### Expected behavior

It should be a move the enemy selects

### Screenshots / Videos

Throat Chop

Throat Chop Scores 0 for AI

Torment

Torment

Endure

Endure scores 0

### Session export file

_No response_

### User data export file

_No response_

### Additional context

https://github.com/pagefaultgames/pokerogue/blob/5797f265a415cdaabdc639bdcf9ce949f01c24f7/src/data/move.ts#L4990

Might be a list of current, it seems incomplete?

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes the user will see?

Certain moves/abilities will have their priorities changed

## Why am I making these changes?

All BattlerTagTypes now have a target benefit score
Closes #546

## What are the changes from a developer perspective?

* Added some documentation to the battler tag type enums

I didn't want to add any new target benefit score tiers so I've been using the existing scores:
* -16 (Extremely bad)
* -5 (Very bad)
* -3 (Bad)
* -2 (Minor bad)
* 0 (Neutral)
* 3 (Good)
* 5 (Very good)

## Screenshots/Videos

n/a

## How to test the changes?

`npm run start`

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes manually?

- [ ] Are all unit tests still passing? (`npm run test:silent`)
  - [ ] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (dark and light)?

Are there any localization additions or changes? If so:

- [ ] Has a locales PR been created on the [locales](https://github.com/despair-games/poketernity-locales) repo?
  - [ ] If so, please leave a link to it here:
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Comment by DayKev** [comment]
Does this affect abilities? I thought this was just for choosing moves based on what `BattlerTag`s they apply.

**Comment by Tempo-anon** [comment]
> Does this affect abilities? I thought this was just for choosing moves based on what `BattlerTag`s they apply.

There's some interactions (like skill swap + truant) for example

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 1]
```diff
@@ -100,19 +105,74 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
+      case BattlerTagType.IGNORE_DARK:
+      case BattlerTagType.BURNED_UP:
+      case BattlerTagType.DOUBLE_SHOCKED:
+      case BattlerTagType.AUTOTOMIZED:
+      case BattlerTagType.MYSTERY_ENCOUNTER_POST_SUMMON:
+      case BattlerTagType.POWER_TRICK:
+      case BattlerTagType.ELECTRIFIED:
+      case BattlerTagType.COMMANDED:
+      case BattlerTagType.PSYCHO_SHIFT:
+      case BattlerTagType.ENDURE_TOKEN:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts]: The `ENDURE_TOKEN` battler tag can likely be removed from the entire codebase since we removed all token items.

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 2]
```diff
@@ -100,19 +105,74 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
+      case BattlerTagType.POWDER:
         return -2;
       case BattlerTagType.MINIMIZED:
       case BattlerTagType.ALWAYS_GET_HIT:
+      case BattlerTagType.ENDURING:
+      case BattlerTagType.STURDY:
+      case BattlerTagType.BYPASS_SLEEP:
+      case BattlerTagType.IGNORE_FLYING:
+      case BattlerTagType.ROOSTED:
+      case BattlerTagType.DESTINY_BOND:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts]: Should be at least +3, next to Grudge

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 3]
```diff
@@ -100,19 +105,74 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
+      case BattlerTagType.CENTER_OF_ATTENTION:
+      case BattlerTagType.STOCKPILING:
+      case BattlerTagType.IGNORE_GHOST:
+      case BattlerTagType.IGNORE_DARK:
+      case BattlerTagType.BURNED_UP:
+      case BattlerTagType.DOUBLE_SHOCKED:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts]: Should be negative, since it causes the Pokemon to lose STAB

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 4]
```diff
@@ -100,19 +105,74 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
+      case BattlerTagType.AUTOTOMIZED:
+      case BattlerTagType.MYSTERY_ENCOUNTER_POST_SUMMON:
+      case BattlerTagType.POWER_TRICK:
+      case BattlerTagType.ELECTRIFIED:
+      case BattlerTagType.COMMANDED:
+      case BattlerTagType.PSYCHO_SHIFT:
+      case BattlerTagType.ENDURE_TOKEN:
+      case BattlerTagType.SKY_DROP:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts:142]:
```suggestion
      case BattlerTagType.SKY_DROP:
      case BattlerTagType.NONE:
```

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 5]
```diff
@@ -80,12 +83,14 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
       case BattlerTagType.HEAL_BLOCK:
       case BattlerTagType.RECEIVE_DOUBLE_DAMAGE:
+      case BattlerTagType.INTERRUPTED:
         return -5;
       case BattlerTagType.SEEDED:
       case BattlerTagType.SALT_CURED:
       case BattlerTagType.CURSED:
       case BattlerTagType.FRENZY:
       case BattlerTagType.TRAPPED:
+      case BattlerTagType.OCTOLOCK:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts:93]:
```suggestion
      case BattlerTagType.OCTOLOCK:
      case BattlerTagType.NO_RETREAT:
```

File: src/data/move-attrs/add-battler-tag-attr.ts [hunk 6]
```diff
@@ -100,19 +105,74 @@ export class AddBattlerTagAttr extends ChanceBasedMoveEffectAttr {
...
+      case BattlerTagType.HIDDEN:
+      case BattlerTagType.FIRE_BOOST:
       case BattlerTagType.CRIT_BOOST:
       case BattlerTagType.CRIT_BOOST_STACKABLE:
       case BattlerTagType.ALWAYS_CRIT:
+      case BattlerTagType.DRAGON_CHEER:
+      case BattlerTagType.ICE_FACE:
+      case BattlerTagType.DISGUISE:
         return 5;
       default:
```
Comment (PigeonBar) [inline src/data/move-attrs/add-battler-tag-attr.ts]: Once all battler tags are added above, the `default:` case can probably be removed (and then type checks will enforce adding new battler tags to this function).

File: src/data/move-attrs/add-battler-tag-attr.ts (hunk 3 above)
Comment (Tempo-anon) [reply src/data/move-attrs/add-battler-tag-attr.ts]: I put all the type removal ones (including the one that removes flying) because they're complex. While they remove STAB they also remove a weakness from the Pokemon

File: src/data/move-attrs/add-battler-tag-attr.ts (hunk 4 above)
Comment (Tempo-anon) [reply src/data/move-attrs/add-battler-tag-attr.ts:142]: we have a NONE battlertagtype :pikastare:

File: src/data/move-attrs/add-battler-tag-attr.ts (hunk 3 above)
Comment (DayKev) [reply src/data/move-attrs/add-battler-tag-attr.ts]: Can you put the ones that are based on attacks (Double Shock, Burn Up, dunno if others exist) at the top of the `case` chain and then put a `// TODO: add terastallization considerations` comment under them please? :prayja:

File: src/data/move-attrs/add-battler-tag-attr.ts (hunk 6 above)
Comment (innerthunder) [reply src/data/move-attrs/add-battler-tag-attr.ts]: ~~type checks will not enforce this (not strictly, anyway)~~ EDIT: nvm

Comment (PigeonBar) [reply src/data/move-attrs/add-battler-tag-attr.ts]: Type error when a battler tag is missing:
image

**Review by PigeonBar — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
