### PR TITLE
[P2] Fix Rattled activating at end of turn when intimidated

### LINKED ISSUE #833: [Bug] Rattled Speed Stat Increase Delayed until End of Turn
### Describe the bug

When activated by Intimidate, Rattled boosts Speed after all other Pokemon have been considered, instead of immediately.
- When switching, this results in the new Pokemon gaining the Speed boost instead of the Rattled Pokemon
- On Battle start, Rattled's speed boost is only handled after other Pokemon's stat modifications have been resolved.

Link to Discord's Bug Report (Rattled Intimidate Interaction)
https://discord.com/channels/1125469663833370665/1349072523756568607

### Reproduction

Start run with Gimmighoul - Chest, and 2 other Pokemon. 
Use False Swipe against an Opponent, and then use Trick Room.
- When the opponent switches, switch out Gimmighoul as well
```
    STARTING_WAVE_OVERRIDE: 25,

    STARTING_LEVEL_OVERRIDE: 100,

    MOVESET_OVERRIDE: [MoveId.FALSE_SWIPE, MoveId.TRICK_ROOM],

    ENEMY_ABILITY_OVERRIDE: Abilities.INTIMIDATE,	
	
    BATTLE_TYPE_OVERRIDE: "double",
```

```
    STARTING_WAVE_OVERRIDE: 8,

    STARTING_LEVEL_OVERRIDE: 100,

    MOVESET_OVERRIDE: [MoveId.FALSE_SWIPE, MoveId.TRICK_ROOM],

    ENEMY_ABILITY_OVERRIDE: Abilities.INTIMIDATE,
```

### Expected behavior

Rattled should boost speed immediately after it's triggered by Intimidate.

### Screenshots / Videos

Rattled 1v1

https://github.com/user-attachments/assets/8a16c73f-b489-4086-8b4d-2d425b8cd650

Rattled 2v2

https://github.com/user-attachments/assets/fdcd08a5-b385-4ef2-9f77-eb7cf6e907dc

Rattled Speed triggers after both Pokemon have Attack lowered by Intimidate

https://github.com/user-attachments/assets/1c87da67-9217-430e-bee6-52882c3101c8

<details><summary>Defiant is correct</summary>

Defiant 2v2

https://github.com/user-attachments/assets/13f7954a-c56e-44b1-9dcb-20d028e53773

Defiant Entry is correct

https://github.com/user-attachments/assets/1477a432-1a0f-4442-a381-a91b79abebf6

</details> 

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

Rattled and Guard Dog now apply their stat boost immediately after being intimidated instead of at the end of the turn.

## Why am I making these changes?

Fixes #833 

## What are the changes from a developer perspective?

- Rearranged some phase scheduling in `PostSummonStatStageChangeAbAttr` and `PostIntimidateStatStageChangeAbAttr`
- Created integration test suite for Rattled

## Screenshots/Videos

Provided on request

## How to test the changes?

`npm run test rattled`

## Checklist

- [ ] ⚠️ If this is a PR for `main` (such as a hotfix), has the game version been updated (`npm run update-version:patch` / `npm run update version:minor`?
- [x] Otherwise: **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?

- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run test:create`) or updated existing tests related to the PR's changes?
- [?] Have I provided screenshots/videos of the changes (if applicable)?
  - [?] Have I made sure that any UI change works for both UI themes (dark and light)?

### CODE REVIEW

**Review by DayKev — DISMISSED** [review]

File: src/data/abilities/ab-attrs/post-intimidate-stat-stage-change-ab-attr.ts [hunk 1]
```diff
@@ -1,31 +1,26 @@
...
     super(true);
     this._flags.add(AbAttrFlag.POST_INTIMIDATE_STAT_STAGE_CHANGE);
     this.stats = stats;
     this.stages = stages;
-    this.overwrites = overwrites;
   }
 
-  override apply(pokemon: Pokemon, simulated: boolean, cancelled: BooleanHolder): boolean {
+  override apply(pokemon: Pokemon, simulated: boolean): boolean {
+    const { phaseManager } = globalScene;
```
Comment (torranx) [inline src/data/abilities/ab-attrs/post-intimidate-stat-stage-change-ab-attr.ts]: nit: might be unnecessary destructuring since it's only being used once + extra unused `const` when `simulated` is true

Comment (DayKev) [reply src/data/abilities/ab-attrs/post-intimidate-stat-stage-change-ab-attr.ts]: Oh yeah, this should be moved inside the `if` or removed (since it's just a one-off the destructuring isn't too necessary).

File: src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts [hunk 2]
```diff
@@ -6,14 +6,21 @@ import { AbAttr } from "./ab-attr";
...
-    cancelled.value = true;
-    return true;
+    if (!cancelled.value) {
+      cancelled.value = true;
+      return true;
+    }
+    return false;
   }
 
   override getTriggerMessage(pokemon: Pokemon, abilityName: string, ..._args: any[]): string {
```
Comment (PigeonBar) [inline src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts:26]: Is this function supposed to check the new `hasTriggerMessage` variable?

File: src/data/abilities/ab-attrs/post-summon-stat-stage-change-ab-attr.ts [hunk 3]
```diff
@@ -30,34 +30,34 @@ export class PostSummonStatStageChangeAbAttr extends PostSummonAbAttr {
...
+        phaseManager.unshiftPhase(
           new StatStageChangePhase(opponent.getBattlerIndex(), pokemon, this.stats, this.stages),
         );
       }
+
+      applyAbAttrs<PostIntimidateStatStageChangeAbAttr>(
+        AbAttrFlag.POST_INTIMIDATE_STAT_STAGE_CHANGE,
+        opponent,
+        simulated,
+      );
```
Comment (PigeonBar) [inline src/data/abilities/ab-attrs/post-summon-stat-stage-change-ab-attr.ts]: This still needs to be placed inside  the `if (this.intimidate)` block (e.g., so that it does not activate against Supersweet Syrup).

File: src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts (hunk 2 above)
Comment (Tempo-anon) [reply src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts:26]: Looks like it's being checked on line 27 `    if (this.hasTriggerMessage) {`

Comment (innerthunder) [reply src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts:26]: Yeah, I just changed it lol

File: src/enums/ab-attr-flag.ts [hunk 4]
```diff
@@ -178,7 +178,7 @@ export enum AbAttrFlag {
   /** @see {@linkcode FieldPreventExplosionLikeAbAttr} */
   FIELD_PREVENT_EXPLOSION_LIKE,
   /** @see {@linkcode IntimidateImmunityAbAttr} */
-  INITIMIDATE_IMMUNITY,
+  INTIMIDATE_IMMUNITY,
```
Comment (Tempo-anon) [inline src/enums/ab-attr-flag.ts:181]: lol

File: test/abilities/rattled.test.ts [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+
+    const enemy = game.field.getEnemyPokemon();
+
+    game.move.use(moveId);
+    await game.toEndOfTurn();
+
+    expect(enemy.getStatStage(Stat.SPD)).toBe(1);
+  });
+
+  it("should not increase the source's Speed when hit by a Normal-type move", async () => {
```
Comment (Tempo-anon) [inline test/abilities/rattled.test.ts:51]: nit: I can think of two other test cases here, one for being behind a substitute, and one for being immune to astonish because the pokemon is normal

**Review by PigeonBar — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
