### PR TITLE
[Bug] Fix calculation of move base power

### LINKED ISSUE #862: [Bug] Variable move power is called after the power boost from abilities, overriding the boosts
Copied from PKR 5313, original issue filed by Mourouh

### Describe the bug

Moves with variable power (VariablePowerAttr) are called after the function for abilities that boost the move's power (VariableMovePowerAbAttr). This leads to the boost of those abilities being overriden, effectively making them not work. 

Moves affected include moves based on weight (Heavy Slam), HP (Flail, Wring Out), Friendship (Return, Frustration) or variable Power moves (Magnitude).

These affect all abilities that affect the power of the moves, like Aerilate or Tough Claws. 

### Reproduction

`const overrides = {ABILITY_OVERRIDE: Abilities.AERILATE, MOVESET_OVERRIDE: [Moves.CRUSH_GRIP, Moves.DOUBLE_EDGE], OPP_MOVESET_OVERRIDE: [Moves.SPLASH, Moves.SPLASH, Moves.SPLASH, Moves.SPLASH], OPP_LEVEL_OVERRIDE: 10} satisfies Partial<InstanceType<typeof DefaultOverrides>>;`

This will let you see Crush Grip's power in console not getting boosted. _Note: Crush Grip is only 120 BP when opponent is at full HP_

### Expected behavior

Variable Power Moves get boosted by abilities as intended. Proof of expected behaviour in Videos

### Screenshots / Videos

Showdown example of variable power moves getting the boost from Refrigerate. 

https://github.com/user-attachments/assets/46f74f01-8df1-4d0b-909b-f56756b89fd4

Screenshot of console. Crush Grip (120 BP) is not getting Aerilate boost, while Double-Edge (also 120 BP, x1.2=144 BP) is
Image

### Session export file

N/A

### User data export file

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Moves with variable base power like Crush Grip will calculate their base power correctly when the user is Terastallized.
The base power boost from Technician will now apply before the boost from Terastallization.

## Why am I making these changes?
Move base power calculation is incorrect.
> Additionally, moves of the Tera Type that have a [base power](https://bulbapedia.bulbagarden.net/wiki/Base_power) below 60 are increased to 60 base power; this is checked for after [Technician](https://bulbapedia.bulbagarden.net/wiki/Technician_(Ability))'s boost [[3]](https://bulbapedia.bulbagarden.net/wiki/Terastal_phenomenon#cite_note-3).

Also fixes #862 

## What are the changes from a developer perspective?
Moved application of `VariablePowerAttr` and `VariableMovePowerAbAttr` to before Terastallization base power boost.
Some tests added for base power calculation.

## How to test the changes?
`npm run test damage-calculation`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test:silent`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

### CODE REVIEW

**Comment by Snailman11** [comment]
Wondering if this fixes its interaction with Aerilate, where the damage increase is overwritten.

**Comment by DayKev** [comment]
It should.

**Comment by flx-sta** [comment]
@DayKev are you still actively working on this?

File: src/data/abilities/ab-attrs/move-power-boost-ab-attr.ts [hunk 1]
```diff
@@ -2,9 +2,9 @@ import type { PokemonAttackCondition } from "#app/@types/PokemonAttackCondition"
 import type { Move } from "#app/data/moves/move";
 import type { Pokemon } from "#app/field/pokemon";
 import type { NumberHolder } from "#app/utils";
-import { VariableMovePowerAbAttr } from "./variable-move-power-ab-attr";
+import { VariableMoveBasePowerAbAttr } from "./variable-move-base-power-ab-attr";
 
-export class MovePowerBoostAbAttr extends VariableMovePowerAbAttr {
+export class MovePowerBoostAbAttr extends VariableMoveBasePowerAbAttr {
```
Comment (MokaStitcher) [inline src/data/abilities/ab-attrs/move-power-boost-ab-attr.ts]: should this class also get renamed to Move**Base**PowerBoostAbAttr?

File: src/data/abilities/ab-attrs/variable-move-power-boost-ab-attr.ts [hunk 2]
```diff
@@ -1,16 +1,16 @@
...
 /**
  * Abilities which cause a variable amount of power increase.
  * @param multFunc A function which takes the user, target, and move, and returns the power multiplier. `1` means no multiplier.
  * @param showAbility Whether to show the ability when it activates. Default `true`
- * @extends VariableMovePowerAbAttr
+ * @extends VariableMoveBasePowerAbAttr
  * @see {@link applyPreAttack}
  */
-export class VariableMovePowerBoostAbAttr extends VariableMovePowerAbAttr {
+export class VariableMovePowerBoostAbAttr extends VariableMoveBasePowerAbAttr {
```
Comment (MokaStitcher) [inline src/data/abilities/ab-attrs/variable-move-power-boost-ab-attr.ts]: same, should it be VariableMoveBasePowerBoostAbAttr ?

File: src/data/moves/move-attrs/anti-sunlight-power-decrease-attr.ts [hunk 3]
```diff
@@ -3,15 +3,15 @@ import type { Pokemon } from "#app/field/pokemon";
...
 
 /**
  * Attribute to halve move power if Rain, Hail, Snow, or a Sandstorm is active.
  * Used for {@link https://bulbapedia.bulbagarden.net/wiki/Solar_Beam_(move) | Solar Beam}
  * and {@link https://bulbapedia.bulbagarden.net/wiki/Solar_Blade_(move) | Solar Blade}.
- * @extends VariablePowerAttr
+ * @extends VariableBasePowerAttr
  */
-export class AntiSunlightPowerDecreaseAttr extends VariablePowerAttr {
+export class AntiSunlightPowerDecreaseAttr extends VariableBasePowerAttr {
```
Comment (MokaStitcher) [inline src/data/moves/move-attrs/anti-sunlight-power-decrease-attr.ts:14]: AntiSunlightBasePowerDecreaseAttr?

**Review by MokaStitcher — COMMENTED** [review]
What's the reasoning behind renaming the base classes?
I've added comments for a few subclasses asking if `base` should also be added in their name. But there are too many so I stopped
<details><summary>Here's the full list though:</summary>

<sub> excluding the ones with individual comments</sub>
- AntiSunlightPowerDecreaseAttr 
- CombinedPledgePowerAttr
- CompareWeightPowerAttr
- DoublePowerChanceAttr
- ElectroBallPowerAttr 
- FirstAttackDoublePowerAttr 
- FriendshipPowerAttr 
- GMaxPowerAttr 
- GyroBallPowerAttr 
- HitCountPowerAttr 
- HpPowerAttr 
- LastMoveDoublePowerAttr 
- LessPPMorePowerAttr 
- LowHpPowerAttr 
- MagnitudePowerAttr 
- MovePowerMultiplierAttr
- MultiHitPowerIncrementAttr 
- OpponentHighHpPowerAttr 
- PositiveStatStagePowerAttr 
- PunishmentPowerAttr 
- PresentPowerAttr 
- RoundPowerAttr 
- SpitUpPowerAttr 
- TeraBlastPowerAttr 
- TurnDamagedDoublePowerAttr 
- WaterShurikenPowerAttr 
- WeightPowerAttr 

</details>

File: src/data/moves/move-attrs/positive-stat-stage-power-attr.ts [hunk 4]
```diff
@@ -31,7 +31,7 @@ export class PositiveStatStagePowerAttr extends VariablePowerAttr {
  * but gains 20 power for every increased stat stage the target has,
  * up to a maximum of 200 base power in total.
  */
-export class PunishmentPowerAttr extends VariablePowerAttr {
+export class PunishmentPowerAttr extends VariableBasePowerAttr {
```
Comment (MokaStitcher) [inline src/data/moves/move-attrs/positive-stat-stage-power-attr.ts]: huh, is there a reason this doesn't have its own file?

**Review by MokaStitcher — DISMISSED** [review]
lgtm
<sub>I wonder how correct Technician's behavior is in general. But that checkup is for a different PR

File: src/data/moves/move-attrs/positive-stat-stage-power-attr.ts (hunk 4 above)
Comment (DayKev) [reply src/data/moves/move-attrs/positive-stat-stage-power-attr.ts]: Interesting, I wonder how that happened.

Comment (MokaStitcher) [reply src/data/moves/move-attrs/positive-stat-stage-power-attr.ts]: probably was accidentally missed during the `move.ts` file split lol. I'll make a quick PR for it unless you want to fix it in this one

Comment (MokaStitcher) [reply src/data/moves/move-attrs/positive-stat-stage-power-attr.ts]: oh, maybe intentional actually, both use a helper function that's defined in that file seems like

File: src/data/abilities/ab-attrs/move-power-boost-ab-attr.ts (hunk 1 above)
Comment (DayKev) [reply src/data/abilities/ab-attrs/move-power-boost-ab-attr.ts]: Hm, maybe it would be better to just revert the renaming than to also rename a bunch of other [ab]attrs...

Comment (DayKev) [reply src/data/abilities/ab-attrs/move-power-boost-ab-attr.ts]: Actually after taking a quick look, this renaming has revealed that there might be more naming and/or execution order issues with these [ab]attrs, so I'm going to revert it for now and take a proper look at it later.

File: src/data/moves/move-attrs/positive-stat-stage-power-attr.ts (hunk 4 above)
Comment (DayKev) [reply src/data/moves/move-attrs/positive-stat-stage-power-attr.ts]: Ah, something to take care of in a different PR it seems.

**Review by MokaStitcher — APPROVED** [review]

**Review by innerthunder — APPROVED** [review]
